
// Generated by Cadence Encounter(R) RTL Compiler v10.10-s209_1

// Verification Directory fv/triangle 

module RC_CG_MOD(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (1'b0), .Q
       (ck_out));
endmodule

module RC_CG_MOD_1(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (1'b0), .Q
       (ck_out));
endmodule

module RC_CG_MOD_10(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (1'b0), .Q
       (ck_out));
endmodule

module RC_CG_MOD_11(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (1'b0), .Q
       (ck_out));
endmodule

module RC_CG_MOD_12(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (1'b0), .Q
       (ck_out));
endmodule

module RC_CG_MOD_13(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (1'b0), .Q
       (ck_out));
endmodule

module RC_CG_MOD_14(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (1'b0), .Q
       (ck_out));
endmodule

module RC_CG_MOD_15(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (1'b0), .Q
       (ck_out));
endmodule

module RC_CG_MOD_16(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (1'b0), .Q
       (ck_out));
endmodule

module RC_CG_MOD_17(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (1'b0), .Q
       (ck_out));
endmodule

module RC_CG_MOD_451(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLHQD1 RC_CGIC_INST(.E (enable), .CPN (ck_in), .TE (1'b0), .Q
       (ck_out));
endmodule

module RC_CG_MOD_451_1(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLHQD1 RC_CGIC_INST(.E (enable), .CPN (ck_in), .TE (1'b0), .Q
       (ck_out));
endmodule

module RC_CG_MOD_2(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (1'b0), .Q
       (ck_out));
endmodule

module RC_CG_MOD_3(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (1'b0), .Q
       (ck_out));
endmodule

module RC_CG_MOD_4(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (1'b0), .Q
       (ck_out));
endmodule

module RC_CG_MOD_5(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (1'b0), .Q
       (ck_out));
endmodule

module RC_CG_MOD_6(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (1'b0), .Q
       (ck_out));
endmodule

module RC_CG_MOD_7(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (1'b0), .Q
       (ck_out));
endmodule

module RC_CG_MOD_8(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (1'b0), .Q
       (ck_out));
endmodule

module RC_CG_MOD_9(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (1'b0), .Q
       (ck_out));
endmodule

module mult_signed(A, B, Z);
  input [6:0] A, B;
  output [6:0] Z;
  wire [6:0] A, B;
  wire [6:0] Z;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_62, n_63, n_64, n_66, n_68;
  XOR3D0 g1761(.A1 (n_63), .A2 (n_62), .A3 (n_68), .Z (Z[6]));
  FA1D0 g1762(.A (n_57), .B (n_58), .CI (n_66), .CO (n_68), .S (Z[5]));
  FA1D0 g1763(.A (n_64), .B (n_51), .CI (n_59), .CO (n_66), .S (Z[4]));
  FA1D0 g1764(.A (n_45), .B (n_52), .CI (n_60), .CO (n_64), .S (Z[3]));
  CKXOR2D0 g1765(.A1 (n_56), .A2 (n_48), .Z (n_63));
  XNR4D0 g1766(.A1 (n_31), .A2 (n_37), .A3 (n_49), .A4 (n_44), .ZN
       (n_62));
  HA1D0 g1767(.A (n_40), .B (n_55), .CO (n_60), .S (Z[2]));
  FA1D0 g1768(.A (n_39), .B (n_32), .CI (n_46), .CO (n_58), .S (n_59));
  FA1D0 g1769(.A (n_50), .B (n_43), .CI (n_47), .CO (n_56), .S (n_57));
  AO21D0 g1770(.A1 (n_29), .A2 (A[0]), .B (n_53), .Z (n_55));
  HA1D0 g1771(.A (n_27), .B (n_38), .CO (n_53), .S (Z[1]));
  HA1D0 g1772(.A (n_35), .B (n_41), .CO (n_51), .S (n_52));
  HA1D0 g1773(.A (n_36), .B (n_42), .CO (n_49), .S (n_50));
  MOAI22D0 g1774(.A1 (n_34), .A2 (n_15), .B1 (n_29), .B2 (n_16), .ZN
       (n_48));
  OAI22D0 g1775(.A1 (n_34), .A2 (n_21), .B1 (n_30), .B2 (n_15), .ZN
       (n_47));
  OAI22D0 g1776(.A1 (n_34), .A2 (n_18), .B1 (n_30), .B2 (n_21), .ZN
       (n_46));
  OAI22D0 g1777(.A1 (n_34), .A2 (n_26), .B1 (n_30), .B2 (n_18), .ZN
       (n_45));
  AOI22D0 g1778(.A1 (n_33), .A2 (n_13), .B1 (n_28), .B2 (n_24), .ZN
       (n_44));
  AO22D0 g1779(.A1 (n_33), .A2 (n_25), .B1 (n_13), .B2 (n_28), .Z
       (n_43));
  AO22D0 g1780(.A1 (n_17), .A2 (n_9), .B1 (B[0]), .B2 (n_19), .Z
       (n_42));
  AO22D0 g1781(.A1 (n_22), .A2 (n_9), .B1 (B[0]), .B2 (n_14), .Z
       (n_41));
  AO22D0 g1782(.A1 (n_20), .A2 (n_9), .B1 (B[0]), .B2 (n_22), .Z
       (n_40));
  AO22D0 g1783(.A1 (n_14), .A2 (n_9), .B1 (B[0]), .B2 (n_17), .Z
       (n_39));
  AO22D0 g1784(.A1 (n_20), .A2 (B[0]), .B1 (n_2), .B2 (n_9), .Z (n_38));
  AOI22D0 g1785(.A1 (n_19), .A2 (n_9), .B1 (n_23), .B2 (B[0]), .ZN
       (n_37));
  OA211D0 g1786(.A1 (n_2), .A2 (n_7), .B (n_11), .C (B[5]), .Z (n_36));
  OA211D0 g1787(.A1 (n_2), .A2 (n_8), .B (n_12), .C (B[3]), .Z (n_35));
  OAI211D0 g1788(.A1 (B[2]), .A2 (B[3]), .B (n_30), .C (n_10), .ZN
       (n_34));
  AOI211D0 g1789(.A1 (B[5]), .A2 (B[4]), .B (n_28), .C (n_4), .ZN
       (n_33));
  CKAN2D0 g1790(.A1 (n_28), .A2 (A[0]), .Z (n_32));
  OAI211D0 g1791(.A1 (B[6]), .A2 (B[5]), .B (n_5), .C (A[0]), .ZN
       (n_31));
  CKND0 g1792(.I (n_30), .ZN (n_29));
  IND2D0 g1793(.A1 (n_8), .B1 (n_12), .ZN (n_30));
  INR2D0 g1794(.A1 (n_11), .B1 (n_7), .ZN (n_28));
  NR2D0 g1795(.A1 (Z[0]), .A2 (n_1), .ZN (n_27));
  MUX2ND0 g1796(.I0 (A[0]), .I1 (n_2), .S (B[3]), .ZN (n_26));
  MUX2ND0 g1797(.I0 (n_2), .I1 (A[0]), .S (B[5]), .ZN (n_25));
  CKXOR2D0 g1798(.A1 (B[5]), .A2 (A[2]), .Z (n_24));
  MUX2ND0 g1799(.I0 (n_1), .I1 (B[1]), .S (A[6]), .ZN (n_23));
  MUX2ND0 g1800(.I0 (n_1), .I1 (B[1]), .S (A[2]), .ZN (n_22));
  MUX2ND0 g1801(.I0 (B[3]), .I1 (n_3), .S (A[2]), .ZN (n_21));
  MUX2ND0 g1802(.I0 (n_1), .I1 (B[1]), .S (A[1]), .ZN (n_20));
  MUX2ND0 g1803(.I0 (n_1), .I1 (B[1]), .S (A[5]), .ZN (n_19));
  MUX2ND0 g1804(.I0 (B[3]), .I1 (n_3), .S (A[1]), .ZN (n_18));
  MUX2ND0 g1805(.I0 (n_1), .I1 (B[1]), .S (A[4]), .ZN (n_17));
  MUX2ND0 g1806(.I0 (n_3), .I1 (B[3]), .S (A[4]), .ZN (n_16));
  MUX2ND0 g1807(.I0 (B[3]), .I1 (n_3), .S (A[3]), .ZN (n_15));
  MUX2ND0 g1808(.I0 (n_1), .I1 (B[1]), .S (A[3]), .ZN (n_14));
  CKXOR2D0 g1809(.A1 (B[5]), .A2 (A[1]), .Z (n_13));
  CKND2D0 g1810(.A1 (B[2]), .A2 (B[1]), .ZN (n_12));
  CKND2D0 g1811(.A1 (B[4]), .A2 (B[3]), .ZN (n_11));
  CKND2D0 g1812(.A1 (B[2]), .A2 (B[3]), .ZN (n_10));
  NR2D0 g1813(.A1 (n_1), .A2 (B[0]), .ZN (n_9));
  NR2D0 g1814(.A1 (B[1]), .A2 (B[2]), .ZN (n_8));
  NR2D0 g1815(.A1 (B[3]), .A2 (B[4]), .ZN (n_7));
  NR2D0 g1816(.A1 (n_2), .A2 (n_0), .ZN (Z[0]));
  CKND2D0 g1817(.A1 (B[6]), .A2 (B[5]), .ZN (n_5));
  NR2D0 g1818(.A1 (B[5]), .A2 (B[4]), .ZN (n_4));
  CKND0 g1819(.I (B[3]), .ZN (n_3));
  CKND0 g1820(.I (A[0]), .ZN (n_2));
  CKND0 g1821(.I (B[1]), .ZN (n_1));
  CKND0 g1822(.I (B[0]), .ZN (n_0));
endmodule

module triangle(clk, reset, nt, xi, yi, busy, po, xo, yo);
  input clk, reset, nt;
  input [2:0] xi, yi;
  output busy, po;
  output [2:0] xo, yo;
  wire clk, reset, nt;
  wire [2:0] xi, yi;
  wire busy, po;
  wire [2:0] xo, yo;
  wire [6:0] AD;
  wire [6:0] BC;
  wire [6:0] RLO;
  wire [2:0] x_min;
  wire [2:0] x;
  wire [2:0] \xi_ff[2] ;
  wire [2:0] \yi_ff[0] ;
  wire [2:0] \yi_ff[1] ;
  wire [2:0] \yi_ff[2] ;
  wire [6:0] sub_op0;
  wire [6:0] sub_op1;
  wire [2:0] x_max;
  wire [2:0] \xi_ff[0] ;
  wire [2:0] \xi_ff[1] ;
  wire [2:0] y_max;
  wire [2:0] y_min;
  wire [2:0] y;
  wire [3:0] control;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, check, good, inc_x;
  wire inc_y, mul_en, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_19;
  wire n_20, n_21, n_22, n_24, n_25, n_28, n_29, n_31;
  wire n_32, n_33, n_34, n_36, n_37, n_38, n_39, n_40;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_54, n_55, n_56, n_57, n_58, n_62;
  wire n_63, n_65, n_66, n_67, n_68, n_69, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_80, n_81;
  wire n_82, n_84, n_85, n_86, n_88, n_90, n_91, n_92;
  wire n_94, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_108, n_109, n_110, n_112, n_113, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_127, n_130;
  wire n_131, n_132, n_133, n_134, n_135, n_136, n_137, n_138;
  wire n_141, n_143, n_144, n_146, n_147, n_149, n_151, n_152;
  wire n_155, n_157, n_160, n_161, n_162, n_164, n_165, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_177, n_178, n_179, n_180, n_181, n_182, n_183, n_184;
  wire n_185, n_186, n_187, n_188, n_189, n_190, n_191, n_192;
  wire n_193, n_194, n_195, n_196, n_197, n_200, n_201, n_202;
  wire n_205, n_206, n_207, n_208, n_209, n_210, n_211, n_212;
  wire n_213, n_214, n_215, n_218, n_219, n_220, n_221, n_222;
  wire n_223, n_224, n_225, n_226, n_227, n_228, n_229, n_230;
  wire n_231, n_232, n_233, n_234, n_235, n_236, n_237, n_238;
  wire n_239, n_240, n_241, n_242, n_243, n_244, n_245, n_246;
  wire n_247, n_248, n_249, n_250, n_251, n_252, n_253, n_254;
  wire n_255, n_256, n_257, n_258, n_259, n_260, n_261, n_262;
  wire n_263, n_264, n_265, n_266, n_267, n_268, n_269, n_270;
  wire n_271, n_272, n_273, n_274, n_275, n_276, n_277, n_278;
  wire n_279, n_280, n_281, n_282, n_283, n_284, n_285, n_286;
  wire n_287, n_288, n_289, n_290, n_291, n_292, n_293, n_294;
  wire n_295, n_296, n_297, n_298, n_299, n_300, n_301, n_302;
  wire n_303, n_304, n_305, n_306, n_307, n_308, n_309, n_310;
  wire n_312, n_313, n_314, n_316, n_317, n_318, n_319, n_320;
  wire n_321, n_322, n_323, n_324, n_325, n_326, n_327, n_328;
  wire n_329, n_330, n_331, n_332, n_333, n_335, n_336, n_339;
  wire n_340, n_341, n_342, n_343, n_344, n_345, n_347, n_349;
  wire n_351, n_352, n_353, n_354, n_355, n_356, n_358, n_359;
  wire n_360, n_361, n_362, n_363, n_364, n_365, n_366, n_367;
  wire n_368, n_369, n_370, n_371, n_372, n_374, n_375, n_377;
  wire n_378, n_379, n_380, n_381, n_382, n_384, n_385, n_386;
  wire n_387, n_388, n_389, n_390, n_392, n_398, n_400, n_402;
  wire n_404, n_405, n_406, n_407, n_408, n_410, n_411, n_413;
  wire n_414, n_416, n_417, n_418, n_422, n_426, n_430, n_432;
  wire n_434, n_439, n_440, n_441, n_442, n_455, n_457, n_458;
  wire n_459, n_460, n_461, n_462, n_463, n_464, n_465, n_467;
  wire n_468, n_469, n_470, n_471, n_472, n_479, n_482, n_483;
  wire n_484, n_485, n_486, n_491, n_492, n_494, n_496, n_502;
  wire n_508, n_509, n_510, n_512, n_513, n_515, n_516, n_517;
  wire n_518, n_519, n_520, n_521, n_522, n_523, n_524, n_525;
  wire n_527, n_528, n_529, n_530, n_531, n_532, n_533, n_534;
  wire n_535, n_536, n_537, n_538, n_539, n_540, n_541, n_542;
  wire n_543, n_544, n_545, n_559, n_560, n_597, n_598, n_599;
  wire n_600, n_601, n_602, rc_gclk, rc_gclk_7484, rc_gclk_7488,
       rc_gclk_7492, rc_gclk_7496;
  wire rc_gclk_7500, rc_gclk_7504, rc_gclk_7508, rc_gclk_7512,
       rc_gclk_7516, rc_gclk_7520, rc_gclk_7524, rc_gclk_7528;
  wire rc_gclk_7532, rc_gclk_7536, rc_gclk_7540, rc_gclk_7544,
       rc_gclk_7548, rc_gclk_7552, rc_gclk_7558, rst_int;
  wire sub_en, top_line;
  RC_CG_MOD RC_CG_HIER_INST0(.enable (n_339), .ck_in (clk), .ck_out
       (rc_gclk), .test (1'b0));
  RC_CG_MOD_1 RC_CG_HIER_INST1(.enable (n_341), .ck_in (clk), .ck_out
       (rc_gclk_7484), .test (1'b0));
  RC_CG_MOD_10 RC_CG_HIER_INST10(.enable (n_532), .ck_in (clk), .ck_out
       (rc_gclk_7520), .test (1'b0));
  RC_CG_MOD_11 RC_CG_HIER_INST11(.enable (n_534), .ck_in (clk), .ck_out
       (rc_gclk_7524), .test (1'b0));
  RC_CG_MOD_12 RC_CG_HIER_INST12(.enable (n_336), .ck_in (clk), .ck_out
       (rc_gclk_7528), .test (1'b0));
  RC_CG_MOD_13 RC_CG_HIER_INST13(.enable (n_533), .ck_in (clk), .ck_out
       (rc_gclk_7532), .test (1'b0));
  RC_CG_MOD_14 RC_CG_HIER_INST14(.enable (n_375), .ck_in (clk), .ck_out
       (rc_gclk_7536), .test (1'b0));
  RC_CG_MOD_15 RC_CG_HIER_INST15(.enable (n_540), .ck_in (clk), .ck_out
       (rc_gclk_7540), .test (1'b0));
  RC_CG_MOD_16 RC_CG_HIER_INST16(.enable (n_374), .ck_in (clk), .ck_out
       (rc_gclk_7544), .test (1'b0));
  RC_CG_MOD_17 RC_CG_HIER_INST17(.enable (n_372), .ck_in (clk), .ck_out
       (rc_gclk_7548), .test (1'b0));
  RC_CG_MOD_451 RC_CG_HIER_INST18(.enable (n_333), .ck_in (clk),
       .ck_out (rc_gclk_7552), .test (1'b0));
  RC_CG_MOD_451_1 RC_CG_HIER_INST19(.enable (inc_y), .ck_in (clk),
       .ck_out (rc_gclk_7558), .test (1'b0));
  RC_CG_MOD_2 RC_CG_HIER_INST2(.enable (n_345), .ck_in (clk), .ck_out
       (rc_gclk_7488), .test (1'b0));
  RC_CG_MOD_3 RC_CG_HIER_INST3(.enable (n_335), .ck_in (clk), .ck_out
       (rc_gclk_7492), .test (1'b0));
  RC_CG_MOD_4 RC_CG_HIER_INST4(.enable (n_536), .ck_in (clk), .ck_out
       (rc_gclk_7496), .test (1'b0));
  RC_CG_MOD_5 RC_CG_HIER_INST5(.enable (n_528), .ck_in (clk), .ck_out
       (rc_gclk_7500), .test (1'b0));
  RC_CG_MOD_6 RC_CG_HIER_INST6(.enable (n_340), .ck_in (clk), .ck_out
       (rc_gclk_7504), .test (1'b0));
  RC_CG_MOD_7 RC_CG_HIER_INST7(.enable (n_344), .ck_in (clk), .ck_out
       (rc_gclk_7508), .test (1'b0));
  RC_CG_MOD_8 RC_CG_HIER_INST8(.enable (n_342), .ck_in (clk), .ck_out
       (rc_gclk_7512), .test (1'b0));
  RC_CG_MOD_9 RC_CG_HIER_INST9(.enable (n_343), .ck_in (clk), .ck_out
       (rc_gclk_7516), .test (1'b0));
  mult_signed mul_211_31(.A ({n_381, n_320, n_321, n_382, n_322, n_323,
       n_324}), .B ({n_377, n_317, n_378, n_318, n_319, n_379, n_380}),
       .Z ({n_390, n_389, n_388, n_387, n_386, n_385, n_384}));
  SDFQND1 \AD_reg[2] (.CP (rc_gclk), .D (n_353), .SI (1'b0), .SE
       (1'b0), .QN (n_368));
  SDFQND1 \AD_reg[3] (.CP (rc_gclk), .D (n_354), .SI (1'b0), .SE
       (1'b0), .QN (AD[3]));
  SDFQND1 \AD_reg[4] (.CP (rc_gclk), .D (n_356), .SI (1'b0), .SE
       (1'b0), .QN (AD[4]));
  SDFQND1 \AD_reg[5] (.CP (rc_gclk), .D (n_355), .SI (1'b0), .SE
       (1'b0), .QN (AD[5]));
  SDFQND1 \AD_reg[6] (.CP (rc_gclk), .D (n_358), .SI (1'b0), .SE
       (1'b0), .QN (AD[6]));
  SDFQND1 \BC_reg[3] (.CP (rc_gclk_7504), .D (n_354), .SI (1'b0), .SE
       (1'b0), .QN (BC[3]));
  SDFQND1 \BC_reg[4] (.CP (rc_gclk_7504), .D (n_356), .SI (1'b0), .SE
       (1'b0), .QN (BC[4]));
  SDFQND1 \BC_reg[5] (.CP (rc_gclk_7504), .D (n_355), .SI (1'b0), .SE
       (1'b0), .QN (BC[5]));
  SDFQND1 \BC_reg[6] (.CP (rc_gclk_7504), .D (n_358), .SI (1'b0), .SE
       (1'b0), .QN (BC[6]));
  SDFQND1 \D0_reg[0] (.CP (rc_gclk_7512), .D (n_404), .SI (1'b0), .SE
       (1'b0), .QN (n_367));
  SDFQND1 \D0_reg[1] (.CP (rc_gclk_7512), .D (n_405), .SI (1'b0), .SE
       (1'b0), .QN (n_365));
  SDFQND1 \D0_reg[4] (.CP (rc_gclk_7512), .D (n_407), .SI (1'b0), .SE
       (1'b0), .QN (n_363));
  SDFQND1 \D0_reg[6] (.CP (rc_gclk_7512), .D (n_408), .SI (1'b0), .SE
       (1'b0), .QN (n_361));
  SDFQND1 \D1_reg[0] (.CP (rc_gclk_7516), .D (n_404), .SI (1'b0), .SE
       (1'b0), .QN (n_366));
  SDFQND1 \D1_reg[1] (.CP (rc_gclk_7516), .D (n_405), .SI (1'b0), .SE
       (1'b0), .QN (n_364));
  SDFQND1 \D1_reg[4] (.CP (rc_gclk_7516), .D (n_407), .SI (1'b0), .SE
       (1'b0), .QN (n_362));
  SDFQND1 \D1_reg[6] (.CP (rc_gclk_7516), .D (n_408), .SI (1'b0), .SE
       (1'b0), .QN (n_360));
  SDFQND1 \RLO_reg[0] (.CP (rc_gclk_7492), .D (n_404), .SI (1'b0), .SE
       (1'b0), .QN (RLO[0]));
  SDFQND1 \RLO_reg[1] (.CP (rc_gclk_7492), .D (n_405), .SI (1'b0), .SE
       (1'b0), .QN (RLO[1]));
  SDFQND1 \RLO_reg[2] (.CP (rc_gclk_7492), .D (n_370), .SI (1'b0), .SE
       (1'b0), .QN (RLO[2]));
  SDFQND1 \RLO_reg[3] (.CP (rc_gclk_7492), .D (n_406), .SI (1'b0), .SE
       (1'b0), .QN (RLO[3]));
  SDFNSND4 \x_reg[0] (.SDN (1'b1), .CPN (rc_gclk_7552), .D (n_12), .SI
       (x_min[0]), .SE (inc_y), .Q (x[0]), .QN (UNCONNECTED));
  SDFQND0 \xi_ff_reg[2][0] (.CP (rc_gclk_7524), .D (n_441), .SI (1'b0),
       .SE (1'b0), .QN (\xi_ff[2] [0]));
  SDFQND4 \y_max_reg[0] (.CP (rc_gclk_7544), .D (n_471), .SI (1'b0),
       .SE (1'b0), .QN (n_417));
  SDFQND1 \yi_ff_reg[0][0] (.CP (rc_gclk_7520), .D (n_471), .SI (1'b0),
       .SE (1'b0), .QN (n_369));
  SDFQND1 \yi_ff_reg[0][1] (.CP (rc_gclk_7520), .D (n_413), .SI (1'b0),
       .SE (1'b0), .QN (n_359));
  SDFQND1 \yi_ff_reg[0][2] (.CP (rc_gclk_7520), .D (n_414), .SI (1'b0),
       .SE (1'b0), .QN (\yi_ff[0] [2]));
  SDFQND1 \yi_ff_reg[1][2] (.CP (rc_gclk_7496), .D (n_414), .SI (1'b0),
       .SE (1'b0), .QN (\yi_ff[1] [2]));
  SDFQND1 \yi_ff_reg[2][0] (.CP (rc_gclk_7524), .D (n_471), .SI (1'b0),
       .SE (1'b0), .QN (\yi_ff[2] [0]));
  SDFQND1 \yi_ff_reg[2][1] (.CP (rc_gclk_7524), .D (n_413), .SI (1'b0),
       .SE (1'b0), .QN (\yi_ff[2] [1]));
  SDFQND1 \yi_ff_reg[2][2] (.CP (rc_gclk_7524), .D (n_414), .SI (1'b0),
       .SE (1'b0), .QN (\yi_ff[2] [2]));
  CKND0 g3688(.I (n_402), .ZN (n_310));
  DFQD1 \A_reg[0] (.CP (rc_gclk_7484), .D (n_404), .Q (n_297));
  DFQD1 \A_reg[1] (.CP (rc_gclk_7484), .D (n_405), .Q (n_295));
  DFQD1 \A_reg[2] (.CP (rc_gclk_7484), .D (n_370), .Q (n_303));
  DFQD1 \A_reg[3] (.CP (rc_gclk_7484), .D (n_406), .Q (n_307));
  DFQD1 \A_reg[4] (.CP (rc_gclk_7484), .D (n_407), .Q (n_300));
  DFQD1 \A_reg[5] (.CP (rc_gclk_7484), .D (n_371), .Q (n_301));
  DFQD1 \A_reg[6] (.CP (rc_gclk_7484), .D (n_408), .Q (n_305));
  DFQD1 \BC_reg[0] (.CP (rc_gclk_7504), .D (n_351), .Q (n_273));
  DFD1 \BC_reg[1] (.CP (rc_gclk_7504), .D (n_352), .Q (UNCONNECTED0),
       .QN (n_274));
  DFQD1 \B_reg[0] (.CP (rc_gclk_7488), .D (n_404), .Q (n_298));
  DFQD1 \B_reg[1] (.CP (rc_gclk_7488), .D (n_405), .Q (n_296));
  DFQD1 \B_reg[2] (.CP (rc_gclk_7488), .D (n_370), .Q (n_304));
  DFQD1 \B_reg[3] (.CP (rc_gclk_7488), .D (n_406), .Q (n_308));
  DFQD1 \B_reg[4] (.CP (rc_gclk_7488), .D (n_407), .Q (n_299));
  DFQD1 \B_reg[5] (.CP (rc_gclk_7488), .D (n_371), .Q (n_302));
  DFQD1 \B_reg[6] (.CP (rc_gclk_7488), .D (n_408), .Q (n_306));
  DFQD1 \C0_reg[0] (.CP (rc_gclk_7500), .D (n_404), .Q (n_281));
  DFQD1 \C0_reg[1] (.CP (rc_gclk_7500), .D (n_405), .Q (n_279));
  DFQD1 \C0_reg[2] (.CP (rc_gclk_7500), .D (n_370), .Q (n_293));
  DFQD1 \C0_reg[3] (.CP (rc_gclk_7500), .D (n_406), .Q (n_285));
  DFQD1 \C0_reg[4] (.CP (rc_gclk_7500), .D (n_407), .Q (n_277));
  DFQD1 \C0_reg[5] (.CP (rc_gclk_7500), .D (n_371), .Q (n_289));
  DFQD1 \C0_reg[6] (.CP (rc_gclk_7500), .D (n_408), .Q (n_275));
  DFQD1 \C1_reg[0] (.CP (rc_gclk_7508), .D (n_404), .Q (n_282));
  DFQD1 \C1_reg[1] (.CP (rc_gclk_7508), .D (n_405), .Q (n_280));
  DFQD1 \C1_reg[2] (.CP (rc_gclk_7508), .D (n_370), .Q (n_294));
  DFQD1 \C1_reg[3] (.CP (rc_gclk_7508), .D (n_406), .Q (n_286));
  DFQD1 \C1_reg[4] (.CP (rc_gclk_7508), .D (n_407), .Q (n_278));
  DFQD1 \C1_reg[5] (.CP (rc_gclk_7508), .D (n_371), .Q (n_290));
  DFQD1 \C1_reg[6] (.CP (rc_gclk_7508), .D (n_408), .Q (n_276));
  DFD1 \D0_reg[2] (.CP (rc_gclk_7512), .D (n_370), .Q (UNCONNECTED1),
       .QN (n_291));
  DFD1 \D0_reg[3] (.CP (rc_gclk_7512), .D (n_406), .Q (UNCONNECTED2),
       .QN (n_283));
  DFD1 \D0_reg[5] (.CP (rc_gclk_7512), .D (n_371), .Q (UNCONNECTED3),
       .QN (n_287));
  DFD1 \D1_reg[2] (.CP (rc_gclk_7516), .D (n_370), .Q (UNCONNECTED4),
       .QN (n_292));
  DFD1 \D1_reg[3] (.CP (rc_gclk_7516), .D (n_406), .Q (UNCONNECTED5),
       .QN (n_284));
  DFD1 \D1_reg[5] (.CP (rc_gclk_7516), .D (n_371), .Q (UNCONNECTED6),
       .QN (n_288));
  DFQD1 busy_reg(.CP (rc_gclk_7496), .D (n_141), .Q (busy));
  LHQD1 \mul_op0_reg[0] (.E (n_392), .D (n_227), .Q (n_324));
  LHQD1 \mul_op0_reg[1] (.E (n_392), .D (n_233), .Q (n_323));
  LHQD1 \mul_op0_reg[2] (.E (n_392), .D (n_239), .Q (n_322));
  LHQD1 \mul_op0_reg[3] (.E (n_392), .D (n_245), .Q (n_382));
  LHQD1 \mul_op0_reg[4] (.E (n_392), .D (n_250), .Q (n_321));
  LHQD1 \mul_op0_reg[5] (.E (n_392), .D (n_254), .Q (n_320));
  LHQD1 \mul_op0_reg[6] (.E (n_392), .D (n_257), .Q (n_381));
  LHQD1 \mul_op1_reg[0] (.E (n_392), .D (n_229), .Q (n_380));
  LHQD1 \mul_op1_reg[1] (.E (n_392), .D (n_235), .Q (n_379));
  LHQD1 \mul_op1_reg[2] (.E (n_392), .D (n_241), .Q (n_319));
  LHQD1 \mul_op1_reg[3] (.E (n_392), .D (n_249), .Q (n_318));
  LHQD1 \mul_op1_reg[4] (.E (n_392), .D (n_253), .Q (n_378));
  LHQD1 \mul_op1_reg[5] (.E (n_392), .D (n_256), .Q (n_317));
  LHQD1 \mul_op1_reg[6] (.E (n_392), .D (n_259), .Q (n_377));
  LHQD1 \sub_ans_reg[0] (.E (sub_en), .D (n_224), .Q (n_272));
  LHQD1 \sub_ans_reg[1] (.E (sub_en), .D (n_226), .Q (n_271));
  LHQD1 \sub_ans_reg[2] (.E (sub_en), .D (n_232), .Q (n_270));
  LHQD1 \sub_ans_reg[3] (.E (sub_en), .D (n_238), .Q (n_269));
  LHQD1 \sub_ans_reg[4] (.E (sub_en), .D (n_244), .Q (n_268));
  LHQD1 \sub_ans_reg[5] (.E (sub_en), .D (n_248), .Q (n_267));
  LHQD1 \sub_ans_reg[6] (.E (sub_en), .D (n_252), .Q (n_266));
  LHQD1 sub_en_reg(.E (n_215), .D (n_197), .Q (sub_en));
  LND1 \sub_op0_reg[0] (.EN (n_208), .D (n_210), .Q (UNCONNECTED7), .QN
       (n_265));
  LND1 \sub_op0_reg[2] (.EN (n_208), .D (n_211), .Q (UNCONNECTED8), .QN
       (n_309));
  LND1 \sub_op0_reg[3] (.EN (n_208), .D (n_185), .Q (UNCONNECTED9), .QN
       (n_260));
  LNQD1 \sub_op0_reg[4] (.EN (n_208), .D (n_184), .Q (n_261));
  LNQD1 \sub_op0_reg[5] (.EN (n_208), .D (n_189), .Q (sub_op0[5]));
  LNQD1 \sub_op0_reg[6] (.EN (n_208), .D (n_186), .Q (sub_op0[6]));
  LHQD1 \sub_op1_reg[0] (.E (n_432), .D (n_221), .Q (sub_op1[0]));
  LHQD1 \sub_op1_reg[1] (.E (n_432), .D (n_220), .Q (n_264));
  LNQD1 \sub_op1_reg[3] (.EN (n_208), .D (n_183), .Q (n_263));
  LNQD1 \sub_op1_reg[4] (.EN (n_208), .D (n_188), .Q (n_262));
  LND1 \sub_op1_reg[5] (.EN (n_208), .D (n_182), .Q (UNCONNECTED10),
       .QN (sub_op1[5]));
  LNQD1 \sub_op1_reg[6] (.EN (n_208), .D (n_181), .Q (sub_op1[6]));
  DFQD4 \x_max_reg[1] (.CP (rc_gclk_7536), .D (n_410), .Q (x_max[1]));
  DFQD1 \x_max_reg[2] (.CP (rc_gclk_7536), .D (n_411), .Q (x_max[2]));
  DFQD4 \x_min_reg[0] (.CP (rc_gclk_7540), .D (n_175), .Q (x_min[0]));
  DFQD4 \x_min_reg[1] (.CP (rc_gclk_7540), .D (n_173), .Q (x_min[1]));
  DFQD1 \x_min_reg[2] (.CP (rc_gclk_7540), .D (n_170), .Q (x_min[2]));
  DFQD4 \xi_ff_reg[0][0] (.CP (rc_gclk_7520), .D (n_441), .Q
       (\xi_ff[0] [0]));
  DFQD4 \xi_ff_reg[0][1] (.CP (rc_gclk_7520), .D (n_410), .Q
       (\xi_ff[0] [1]));
  DFQD1 \xi_ff_reg[1][0] (.CP (rc_gclk_7496), .D (n_441), .Q
       (\xi_ff[1] [0]));
  DFQD1 \xi_ff_reg[1][2] (.CP (rc_gclk_7496), .D (n_411), .Q
       (\xi_ff[1] [2]));
  DFQD1 \xi_ff_reg[2][1] (.CP (rc_gclk_7524), .D (n_410), .Q
       (\xi_ff[2] [1]));
  DFKCNQD1 \xo_reg[0] (.CP (rc_gclk_7528), .CN (n_472), .D (x[0]), .Q
       (xo[0]));
  DFKCNQD1 \xo_reg[1] (.CP (rc_gclk_7528), .CN (n_141), .D (x[1]), .Q
       (xo[1]));
  DFKCNQD1 \xo_reg[2] (.CP (rc_gclk_7528), .CN (n_472), .D (x[2]), .Q
       (xo[2]));
  DFQD1 \y_max_reg[1] (.CP (rc_gclk_7544), .D (n_413), .Q (y_max[1]));
  DFQD1 \y_max_reg[2] (.CP (rc_gclk_7544), .D (n_414), .Q (y_max[2]));
  DFQD1 \y_min_reg[0] (.CP (rc_gclk_7548), .D (n_172), .Q (y_min[0]));
  DFQD1 \y_min_reg[1] (.CP (rc_gclk_7548), .D (n_171), .Q (y_min[1]));
  DFQD1 \y_min_reg[2] (.CP (rc_gclk_7548), .D (n_174), .Q (y_min[2]));
  DFQD1 \yi_ff_reg[1][0] (.CP (rc_gclk_7496), .D (n_471), .Q (n_430));
  DFKCNQD1 \yo_reg[0] (.CP (rc_gclk_7528), .CN (n_141), .D (y[0]), .Q
       (yo[0]));
  DFKCNQD1 \yo_reg[1] (.CP (rc_gclk_7528), .CN (n_141), .D (y[1]), .Q
       (yo[1]));
  DFKCNQD1 \yo_reg[2] (.CP (rc_gclk_7528), .CN (n_141), .D (y[2]), .Q
       (yo[2]));
  OAI221D0 g5879(.A1 (n_179), .A2 (n_361), .B1 (n_360), .B2 (n_180), .C
       (n_258), .ZN (n_259));
  AOI22D0 g5881(.A1 (n_190), .A2 (n_275), .B1 (n_191), .B2 (n_276), .ZN
       (n_258));
  AO22D0 g5882(.A1 (n_168), .A2 (n_306), .B1 (n_305), .B2 (n_165), .Z
       (n_257));
  AO221D0 g5884(.A1 (n_190), .A2 (n_289), .B1 (n_191), .B2 (n_290), .C
       (n_255), .Z (n_256));
  OAI22D0 g5886(.A1 (n_179), .A2 (n_287), .B1 (n_180), .B2 (n_288), .ZN
       (n_255));
  AO22D0 g5887(.A1 (n_168), .A2 (n_302), .B1 (n_301), .B2 (n_165), .Z
       (n_254));
  AN2XD1 g5892(.A1 (n_266), .A2 (n_472), .Z (n_408));
  OAI221D0 g5894(.A1 (n_179), .A2 (n_363), .B1 (n_362), .B2 (n_180), .C
       (n_251), .ZN (n_253));
  XNR3D0 g5903(.A1 (sub_op0[6]), .A2 (sub_op1[6]), .A3 (n_247), .ZN
       (n_252));
  AOI22D0 g5904(.A1 (n_190), .A2 (n_277), .B1 (n_191), .B2 (n_278), .ZN
       (n_251));
  AO22D0 g5905(.A1 (n_168), .A2 (n_299), .B1 (n_300), .B2 (n_165), .Z
       (n_250));
  CKAN2D1 g5906(.A1 (n_267), .A2 (n_141), .Z (n_371));
  AO221D0 g5909(.A1 (n_190), .A2 (n_285), .B1 (n_191), .B2 (n_286), .C
       (n_246), .Z (n_249));
  FA1D0 g5915(.A (sub_op1[5]), .B (sub_op0[5]), .CI (n_242), .CO
       (n_247), .S (n_248));
  OAI22D0 g5916(.A1 (n_179), .A2 (n_283), .B1 (n_180), .B2 (n_284), .ZN
       (n_246));
  AO22D0 g5917(.A1 (n_168), .A2 (n_308), .B1 (n_307), .B2 (n_165), .Z
       (n_245));
  AN2XD1 g5918(.A1 (n_268), .A2 (n_472), .Z (n_407));
  CKND0 g5926(.I (n_243), .ZN (n_244));
  XNR3D0 g5927(.A1 (n_262), .A2 (n_261), .A3 (n_237), .ZN (n_243));
  MAOI222D0 g5928(.A (n_237), .B (n_262), .C (n_212), .ZN (n_242));
  AN2XD1 g5929(.A1 (n_269), .A2 (n_472), .Z (n_406));
  AO221D0 g5931(.A1 (n_190), .A2 (n_293), .B1 (n_191), .B2 (n_294), .C
       (n_240), .Z (n_241));
  OAI22D0 g5934(.A1 (n_179), .A2 (n_291), .B1 (n_180), .B2 (n_292), .ZN
       (n_240));
  AO22D0 g5935(.A1 (n_168), .A2 (n_304), .B1 (n_303), .B2 (n_165), .Z
       (n_239));
  CKND0 g5936(.I (n_236), .ZN (n_238));
  FA1D0 g5937(.A (n_263), .B (n_260), .CI (n_230), .CO (n_237), .S
       (n_236));
  AN2XD1 g5944(.A1 (n_270), .A2 (n_472), .Z (n_370));
  OAI221D0 g5946(.A1 (n_179), .A2 (n_365), .B1 (n_364), .B2 (n_180), .C
       (n_234), .ZN (n_235));
  AOI22D0 g5949(.A1 (n_190), .A2 (n_279), .B1 (n_191), .B2 (n_280), .ZN
       (n_234));
  AO22D0 g5950(.A1 (n_168), .A2 (n_296), .B1 (n_295), .B2 (n_165), .Z
       (n_233));
  CKND0 g5951(.I (n_231), .ZN (n_232));
  FA1D0 g5952(.A (n_316), .B (n_309), .CI (n_225), .CO (n_230), .S
       (n_231));
  OAI221D0 g5954(.A1 (n_179), .A2 (n_367), .B1 (n_366), .B2 (n_180), .C
       (n_228), .ZN (n_229));
  AOI22D0 g5960(.A1 (n_190), .A2 (n_281), .B1 (n_191), .B2 (n_282), .ZN
       (n_228));
  AO22D0 g5961(.A1 (n_168), .A2 (n_298), .B1 (n_297), .B2 (n_165), .Z
       (n_227));
  AN2XD1 g5962(.A1 (n_271), .A2 (n_472), .Z (n_405));
  XNR3D0 g5968(.A1 (n_434), .A2 (n_264), .A3 (n_223), .ZN (n_226));
  MAOI222D0 g5969(.A (n_223), .B (n_434), .C (n_222), .ZN (n_225));
  AN2XD1 g5970(.A1 (n_272), .A2 (n_472), .Z (n_404));
  OAI21D0 g5972(.A1 (sub_op1[0]), .A2 (n_265), .B (n_223), .ZN (n_224));
  IOA21D1 g5973(.A1 (n_535), .A2 (n_219), .B (n_141), .ZN (n_375));
  OAI21D1 g5974(.A1 (n_160), .A2 (n_218), .B (n_141), .ZN (n_374));
  OAI21D1 g5975(.A1 (n_160), .A2 (n_545), .B (n_141), .ZN (n_372));
  CKND2D0 g5977(.A1 (sub_op1[0]), .A2 (n_265), .ZN (n_223));
  CKND0 g5978(.I (n_264), .ZN (n_222));
  OAI221D0 g5981(.A1 (n_312), .A2 (n_369), .B1 (\xi_ff[2] [0]), .B2
       (n_196), .C (n_213), .ZN (n_221));
  OAI221D0 g5982(.A1 (n_312), .A2 (n_359), .B1 (n_274), .B2 (n_418), .C
       (n_214), .ZN (n_220));
  OAI22D1 g5983(.A1 (n_206), .A2 (n_194), .B1 (x_max[2]), .B2 (n_537),
       .ZN (n_219));
  MAOI22D1 g5984(.A1 (n_205), .A2 (n_192), .B1 (y_max[2]), .B2 (n_143),
       .ZN (n_218));
  CKND2D0 g5988(.A1 (n_197), .A2 (n_208), .ZN (n_215));
  AOI21D0 g5989(.A1 (n_314), .A2 (\xi_ff[2] [1]), .B (n_209), .ZN
       (n_214));
  OA21D0 g5990(.A1 (n_313), .A2 (\yi_ff[2] [0]), .B (n_207), .Z
       (n_213));
  CKND0 g5996(.I (n_261), .ZN (n_212));
  OAI211D0 g6002(.A1 (\yi_ff[1] [2]), .A2 (n_347), .B (n_202), .C
       (n_177), .ZN (n_211));
  AO221D0 g6003(.A1 (n_529), .A2 (\xi_ff[1] [0]), .B1 (n_162), .B2
       (n_332), .C (n_201), .Z (n_210));
  OAI21D0 g6004(.A1 (\yi_ff[2] [1]), .A2 (n_313), .B (n_200), .ZN
       (n_209));
  CKND0 g6005(.I (n_432), .ZN (n_208));
  IND4D0 g6006(.A1 (n_529), .B1 (n_418), .B2 (n_347), .B3 (n_349), .ZN
       (n_432));
  AOI22D0 g6007(.A1 (n_195), .A2 (\xi_ff[0] [0]), .B1 (n_162), .B2
       (n_273), .ZN (n_207));
  AOI32D1 g6008(.A1 (n_137), .A2 (n_193), .A3 (xi[0]), .B1 (n_11), .B2
       (xi[1]), .ZN (n_206));
  MAOI222D0 g6009(.A (y_max[1]), .B (n_152), .C (n_541), .ZN (n_205));
  AOI221D0 g6012(.A1 (n_161), .A2 (y[2]), .B1 (n_529), .B2
       (\xi_ff[1] [2]), .C (n_187), .ZN (n_202));
  AO222D0 g6013(.A1 (n_178), .A2 (n_430), .B1 (n_164), .B2 (x[0]), .C1
       (n_161), .C2 (y[0]), .Z (n_201));
  CKND2D0 g6014(.A1 (\xi_ff[0] [1]), .A2 (n_195), .ZN (n_200));
  NR2D0 g6017(.A1 (n_416), .A2 (n_165), .ZN (n_197));
  OA21D0 g6018(.A1 (n_400), .A2 (n_151), .B (n_598), .Z (n_313));
  CKND0 g6019(.I (n_314), .ZN (n_196));
  OAI21D0 g6020(.A1 (n_151), .A2 (n_398), .B (n_463), .ZN (n_314));
  AOI21D0 g6021(.A1 (n_161), .A2 (n_151), .B (n_167), .ZN (n_312));
  CKND0 g6023(.I (n_530), .ZN (n_195));
  CKAN2D0 g6026(.A1 (x_max[2]), .A2 (n_537), .Z (n_194));
  CKND2D0 g6027(.A1 (x_max[1]), .A2 (n_144), .ZN (n_193));
  CKND2D0 g6028(.A1 (y_max[2]), .A2 (n_143), .ZN (n_192));
  NR2D0 g6031(.A1 (n_169), .A2 (n_151), .ZN (n_191));
  NR2D0 g6032(.A1 (n_169), .A2 (top_line), .ZN (n_190));
  CKND2D0 g6033(.A1 (n_402), .A2 (n_169), .ZN (n_416));
  CKND2D0 g6034(.A1 (n_422), .A2 (n_169), .ZN (n_392));
  NR2D0 g6035(.A1 (n_418), .A2 (AD[5]), .ZN (n_189));
  NR2D0 g6036(.A1 (n_418), .A2 (BC[4]), .ZN (n_188));
  NR2D0 g6037(.A1 (n_418), .A2 (n_368), .ZN (n_187));
  NR2D0 g6038(.A1 (n_418), .A2 (AD[6]), .ZN (n_186));
  NR2D0 g6039(.A1 (n_418), .A2 (AD[3]), .ZN (n_185));
  NR2D0 g6040(.A1 (n_418), .A2 (AD[4]), .ZN (n_184));
  NR2D0 g6041(.A1 (n_418), .A2 (BC[3]), .ZN (n_183));
  NR2D0 g6042(.A1 (n_418), .A2 (BC[5]), .ZN (n_182));
  NR2D0 g6043(.A1 (n_418), .A2 (BC[6]), .ZN (n_181));
  CKND2D0 g6044(.A1 (top_line), .A2 (n_165), .ZN (n_180));
  CKND2D0 g6045(.A1 (n_151), .A2 (n_165), .ZN (n_179));
  CKND0 g6046(.I (n_178), .ZN (n_347));
  IND2D0 g6047(.A1 (n_167), .B1 (n_598), .ZN (n_178));
  CKND2D0 g6048(.A1 (n_598), .A2 (n_141), .ZN (n_343));
  CKND2D0 g6049(.A1 (n_398), .A2 (n_141), .ZN (n_341));
  NR2XD3 g6050(.A1 (n_164), .A2 (n_161), .ZN (n_349));
  CKND2D0 g6051(.A1 (x[2]), .A2 (n_164), .ZN (n_177));
  CKND2D0 g6052(.A1 (n_492), .A2 (n_141), .ZN (n_342));
  CKND2D0 g6053(.A1 (n_402), .A2 (n_141), .ZN (n_336));
  CKND2D0 g6054(.A1 (n_169), .A2 (n_141), .ZN (n_340));
  CKND2D0 g6055(.A1 (n_400), .A2 (n_141), .ZN (n_345));
  CKND2D0 g6057(.A1 (n_463), .A2 (n_141), .ZN (n_344));
  CKND2D0 g6058(.A1 (n_422), .A2 (n_141), .ZN (n_339));
  CKND2D0 g6060(.A1 (n_418), .A2 (n_141), .ZN (n_335));
  CKAN2D0 g6092(.A1 (n_331), .A2 (n_141), .Z (n_351));
  CKAN2D0 g6093(.A1 (n_330), .A2 (n_141), .Z (n_352));
  IND2D0 g6094(.A1 (xi[0]), .B1 (n_141), .ZN (n_175));
  CKND2D0 g6095(.A1 (n_141), .A2 (n_143), .ZN (n_174));
  NR2XD0 g6096(.A1 (n_470), .A2 (n_537), .ZN (n_411));
  NR2XD0 g6097(.A1 (n_470), .A2 (n_144), .ZN (n_410));
  CKND2D0 g6098(.A1 (n_141), .A2 (n_144), .ZN (n_173));
  CKND2D0 g6099(.A1 (n_141), .A2 (n_146), .ZN (n_172));
  CKND2D0 g6100(.A1 (n_141), .A2 (n_541), .ZN (n_171));
  CKND2D0 g6101(.A1 (n_141), .A2 (n_537), .ZN (n_170));
  CKND0 g6102(.I (n_169), .ZN (n_168));
  CKND2D1 g6103(.A1 (n_491), .A2 (n_155), .ZN (n_169));
  ND3D2 g6104(.A1 (n_491), .A2 (control[3]), .A3 (control[2]), .ZN
       (n_402));
  CKND0 g6105(.I (n_492), .ZN (n_167));
  CKND0 g6108(.I (n_422), .ZN (n_165));
  CKND2D0 g6109(.A1 (n_155), .A2 (n_426), .ZN (n_422));
  CKND3 g6110(.I (n_398), .ZN (n_164));
  CKND2D2 g6111(.A1 (n_155), .A2 (n_597), .ZN (n_398));
  AN2XD1 g6113(.A1 (n_325), .A2 (n_141), .Z (n_358));
  AN2XD1 g6114(.A1 (n_328), .A2 (n_141), .Z (n_354));
  AN2XD1 g6115(.A1 (n_327), .A2 (n_141), .Z (n_356));
  AN2XD1 g6116(.A1 (n_329), .A2 (n_141), .Z (n_353));
  AN2XD1 g6117(.A1 (n_326), .A2 (n_141), .Z (n_355));
  CKND0 g6119(.I (n_418), .ZN (n_162));
  CKND2D2 g6120(.A1 (n_155), .A2 (n_524), .ZN (n_418));
  CKND2 g6121(.I (n_400), .ZN (n_161));
  ND2D3 g6122(.A1 (n_502), .A2 (n_524), .ZN (n_400));
  CKND1 g6123(.I (n_535), .ZN (n_160));
  NR2XD0 g6125(.A1 (n_470), .A2 (n_541), .ZN (n_413));
  NR2XD0 g6128(.A1 (n_470), .A2 (n_143), .ZN (n_414));
  OR2D0 g6130(.A1 (inc_y), .A2 (inc_x), .Z (n_333));
  NR2XD0 g6133(.A1 (control[3]), .A2 (control[1]), .ZN (n_157));
  NR2XD2 g6137(.A1 (n_479), .A2 (control[2]), .ZN (n_155));
  NR2XD2 g6141(.A1 (n_147), .A2 (control[0]), .ZN (n_426));
  CKND2D1 g6159(.A1 (n_417), .A2 (yi[0]), .ZN (n_152));
  CKND0 g6160(.I (top_line), .ZN (n_151));
  CKND3 g6162(.I (control[2]), .ZN (n_149));
  CKND2 g6164(.I (control[1]), .ZN (n_147));
  CKND0 g6166(.I (yi[0]), .ZN (n_146));
  CKND0 g6168(.I (xi[1]), .ZN (n_144));
  CKND0 g6169(.I (yi[2]), .ZN (n_143));
  DFD2 \x_max_reg[0] (.CP (rc_gclk_7536), .D (n_441), .Q (x_max[0]),
       .QN (n_137));
  CKND6 fopt6179(.I (n_470), .ZN (n_141));
  IND2D1 g6185(.A1 (x_min[1]), .B1 (xi[1]), .ZN (n_138));
  DFQD1 \AD_reg[0] (.CP (rc_gclk), .D (n_351), .Q (n_332));
  DFD1 \AD_reg[1] (.CP (rc_gclk), .D (n_352), .Q (UNCONNECTED11), .QN
       (n_133));
  DFD1 \BC_reg[2] (.CP (rc_gclk_7504), .D (n_353), .Q (UNCONNECTED12),
       .QN (n_134));
  DFD1 \RLO_reg[4] (.CP (rc_gclk_7492), .D (n_407), .Q (UNCONNECTED13),
       .QN (n_132));
  DFQD1 \RLO_reg[5] (.CP (rc_gclk_7492), .D (n_371), .Q (n_131));
  DFQD1 \RLO_reg[6] (.CP (rc_gclk_7492), .D (n_408), .Q (RLO[6]));
  DFQD1 check_reg(.CP (clk), .D (n_81), .Q (check));
  DFQD4 \control_reg[1] (.CP (rc_gclk_7532), .D (n_468), .Q
       (control[1]));
  DFQD4 \control_reg[2] (.CP (rc_gclk_7532), .D (n_601), .Q
       (control[2]));
  DFQD4 \control_reg[3] (.CP (rc_gclk_7532), .D (n_103), .Q
       (control[3]));
  DFQD1 good_reg(.CP (check), .D (n_121), .Q (good));
  DFQD1 inc_x_reg(.CP (clk), .D (n_483), .Q (inc_x));
  LHQD1 \mul_ans_reg[0] (.E (mul_en), .D (n_384), .Q (n_331));
  LHQD1 \mul_ans_reg[1] (.E (mul_en), .D (n_385), .Q (n_330));
  LHQD1 \mul_ans_reg[2] (.E (mul_en), .D (n_386), .Q (n_329));
  LHQD1 \mul_ans_reg[3] (.E (mul_en), .D (n_387), .Q (n_328));
  LHQD1 \mul_ans_reg[4] (.E (mul_en), .D (n_388), .Q (n_327));
  LHQD1 \mul_ans_reg[5] (.E (mul_en), .D (n_389), .Q (n_326));
  LHQD1 \mul_ans_reg[6] (.E (mul_en), .D (n_390), .Q (n_325));
  LHQD1 mul_en_reg(.E (n_80), .D (n_392), .Q (mul_en));
  DFNSND1 po__reg(.SDN (1'b1), .CPN (clk), .D (n_130), .Q (n_136), .QN
       (UNCONNECTED14));
  DFNSND1 po_reg(.SDN (1'b1), .CPN (clk), .D (n_127), .Q (po), .QN
       (UNCONNECTED15));
  LHQD1 \sub_op0_reg[1] (.E (n_432), .D (n_99), .Q (n_434));
  LHQD1 \sub_op1_reg[2] (.E (n_432), .D (n_91), .Q (n_316));
  DFQD1 top_line_reg(.CP (clk), .D (n_518), .Q (top_line));
  SDFNSND4 \x_reg[1] (.SDN (1'b1), .CPN (rc_gclk_7552), .D (n_58), .SI
       (x_min[1]), .SE (inc_y), .Q (x[1]), .QN (UNCONNECTED16));
  DFNSND4 \x_reg[2] (.SDN (1'b1), .CPN (rc_gclk_7552), .D (n_108), .Q
       (x[2]), .QN (n_15));
  DFQD1 \xi_ff_reg[1][1] (.CP (rc_gclk_7496), .D (n_410), .Q
       (\xi_ff[1] [1]));
  DFQD1 \xi_ff_reg[2][2] (.CP (rc_gclk_7524), .D (n_411), .Q
       (\xi_ff[2] [2]));
  DFNSND4 \y_reg[0] (.SDN (1'b1), .CPN (rc_gclk_7558), .D (n_599), .Q
       (y[0]), .QN (n_16));
  DFNSND4 \y_reg[1] (.SDN (1'b1), .CPN (rc_gclk_7558), .D (n_98), .Q
       (y[1]), .QN (n_13));
  DFNSND4 \y_reg[2] (.SDN (1'b1), .CPN (rc_gclk_7558), .D (n_516), .Q
       (y[2]), .QN (UNCONNECTED17));
  DFQD1 \yi_ff_reg[1][1] (.CP (rc_gclk_7496), .D (n_413), .Q (n_135));
  CKND2D0 g7156(.A1 (n_125), .A2 (n_124), .ZN (n_130));
  IOA21D0 g7161(.A1 (po), .A2 (n_122), .B (n_125), .ZN (n_127));
  OR2D0 g7163(.A1 (po), .A2 (n_122), .Z (n_125));
  CKND2D0 g7164(.A1 (n_136), .A2 (n_123), .ZN (n_124));
  IND2D0 g7165(.A1 (good), .B1 (check), .ZN (n_123));
  CKND2D0 g7166(.A1 (check), .A2 (good), .ZN (n_122));
  OAI31D0 g7168(.A1 (RLO[6]), .A2 (n_65), .A3 (n_22), .B (n_120), .ZN
       (n_121));
  AOI211D0 g7169(.A1 (n_519), .A2 (n_69), .B (n_119), .C (n_110), .ZN
       (n_120));
  OAI32D0 g7170(.A1 (n_40), .A2 (n_440), .A3 (n_118), .B1 (n_102), .B2
       (n_44), .ZN (n_119));
  OAI211D0 g7171(.A1 (\xi_ff[1] [1]), .A2 (n_14), .B (n_117), .C
       (n_28), .ZN (n_118));
  AOI211D0 g7173(.A1 (n_14), .A2 (\xi_ff[1] [1]), .B (n_112), .C
       (n_46), .ZN (n_117));
  AN3XD1 g7179(.A1 (n_101), .A2 (n_100), .A3 (n_458), .Z (n_113));
  OAI221D0 g7180(.A1 (n_67), .A2 (y[0]), .B1 (\xi_ff[1] [2]), .B2
       (n_15), .C (n_109), .ZN (n_112));
  OAI32D0 g7184(.A1 (n_72), .A2 (n_52), .A3 (n_56), .B1 (n_519), .B2
       (n_69), .ZN (n_110));
  AOI22D0 g7185(.A1 (n_94), .A2 (y[0]), .B1 (n_15), .B2 (\xi_ff[1]
       [2]), .ZN (n_109));
  MUX3D0 g7186(.I0 (n_15), .I1 (x[2]), .I2 (x_min[2]), .S0 (n_25), .S1
       (inc_y), .Z (n_108));
  MOAI22D1 g7194(.A1 (n_78), .A2 (n_88), .B1 (n_85), .B2 (n_76), .ZN
       (n_103));
  ND4D0 g7195(.A1 (n_86), .A2 (n_71), .A3 (n_57), .A4 (n_55), .ZN
       (n_102));
  CKND2D1 g7196(.A1 (n_519), .A2 (n_84), .ZN (n_101));
  OAI22D1 g7197(.A1 (n_485), .A2 (n_24), .B1 (n_7), .B2 (y_max[2]), .ZN
       (n_100));
  AO221D0 g7202(.A1 (n_529), .A2 (\xi_ff[1] [1]), .B1 (n_164), .B2
       (x[1]), .C (n_90), .Z (n_99));
  MUX2D0 g7203(.I0 (y_min[1]), .I1 (n_54), .S (n_598), .Z (n_98));
  OAI21D0 g7204(.A1 (control[0]), .A2 (n_75), .B (n_78), .ZN (n_97));
  IOA21D0 g7207(.A1 (n_513), .A2 (n_135), .B (n_430), .ZN (n_94));
  OAI21D1 g7209(.A1 (n_66), .A2 (n_16), .B (n_39), .ZN (n_92));
  AO211D0 g7211(.A1 (n_314), .A2 (\xi_ff[2] [2]), .B (n_82), .C (n_63),
       .Z (n_91));
  OAI222D0 g7212(.A1 (n_400), .A2 (n_13), .B1 (n_133), .B2 (n_418), .C1
       (n_19), .C2 (n_347), .ZN (n_90));
  NR3D2 g7215(.A1 (n_48), .A2 (n_50), .A3 (n_47), .ZN (n_88));
  AOI221D0 g7217(.A1 (x[0]), .A2 (\xi_ff[2] [0]), .B1 (y[2]), .B2
       (\yi_ff[2] [2]), .C (n_73), .ZN (n_86));
  AO21D0 g7218(.A1 (n_524), .A2 (control[2]), .B (control[3]), .Z
       (n_85));
  ND3D1 g7219(.A1 (n_43), .A2 (n_512), .A3 (n_486), .ZN (n_84));
  OAI222D0 g7223(.A1 (n_418), .A2 (n_134), .B1 (\yi_ff[2] [2]), .B2
       (n_313), .C1 (\yi_ff[0] [2]), .C2 (n_312), .ZN (n_82));
  NR2XD0 g7224(.A1 (n_62), .A2 (n_464), .ZN (n_81));
  IND4D0 g7225(.A1 (n_416), .B1 (n_422), .B2 (n_418), .B3 (n_349), .ZN
       (n_80));
  CKND1 g7227(.I (n_77), .ZN (n_78));
  NR2XD1 g7228(.A1 (n_455), .A2 (n_491), .ZN (n_77));
  CKND2 g7229(.I (n_75), .ZN (n_76));
  OAI21D1 g7230(.A1 (n_491), .A2 (n_21), .B (n_472), .ZN (n_75));
  NR2XD0 g7231(.A1 (n_51), .A2 (n_442), .ZN (n_74));
  OAI22D0 g7232(.A1 (n_15), .A2 (\xi_ff[2] [2]), .B1 (n_14), .B2
       (\xi_ff[2] [1]), .ZN (n_73));
  MUX2ND0 g7233(.I0 (n_15), .I1 (x[2]), .S (\xi_ff[0] [2]), .ZN (n_72));
  MAOI22D0 g7234(.A1 (n_15), .A2 (\xi_ff[2] [2]), .B1 (x[0]), .B2
       (\xi_ff[2] [0]), .ZN (n_71));
  XNR2D0 g7236(.A1 (RLO[6]), .A2 (top_line), .ZN (n_69));
  IOA21D2 g7237(.A1 (n_20), .A2 (\xi_ff[1] [2]), .B (n_38), .ZN (n_68));
  CKND0 g7238(.I (n_66), .ZN (n_67));
  OAI21D1 g7239(.A1 (y[1]), .A2 (n_19), .B (n_8), .ZN (n_66));
  IND4D0 g7240(.A1 (n_131), .B1 (n_132), .B2 (RLO[2]), .B3 (RLO[3]),
       .ZN (n_65));
  NR2D0 g7243(.A1 (n_530), .A2 (n_20), .ZN (n_63));
  AOI21D1 g7244(.A1 (n_349), .A2 (check), .B (n_310), .ZN (n_62));
  OAI22D0 g7249(.A1 (x[1]), .A2 (n_12), .B1 (n_14), .B2 (x[0]), .ZN
       (n_58));
  MAOI22D0 g7250(.A1 (n_14), .A2 (\xi_ff[2] [1]), .B1 (y[2]), .B2
       (\yi_ff[2] [2]), .ZN (n_57));
  MUX2ND0 g7251(.I0 (n_14), .I1 (x[1]), .S (\xi_ff[0] [1]), .ZN (n_56));
  MUX2ND0 g7252(.I0 (n_16), .I1 (y[0]), .S (\yi_ff[2] [0]), .ZN (n_55));
  MUX2ND0 g7253(.I0 (n_16), .I1 (y[0]), .S (y[1]), .ZN (n_54));
  MUX2ND0 g7255(.I0 (n_12), .I1 (x[0]), .S (\xi_ff[0] [0]), .ZN (n_52));
  OAI22D1 g7256(.A1 (x[2]), .A2 (n_9), .B1 (x[1]), .B2 (n_11), .ZN
       (n_51));
  OAI22D2 g7257(.A1 (n_14), .A2 (x_min[1]), .B1 (n_15), .B2 (x_min[2]),
       .ZN (n_50));
  AOI22D1 g7258(.A1 (x[1]), .A2 (n_11), .B1 (x[2]), .B2 (n_9), .ZN
       (n_49));
  OAI22D1 g7259(.A1 (x[2]), .A2 (n_4), .B1 (x[1]), .B2 (n_5), .ZN
       (n_48));
  MOAI22D1 g7260(.A1 (x[0]), .A2 (n_6), .B1 (x[0]), .B2 (n_6), .ZN
       (n_47));
  MUX2ND0 g7261(.I0 (n_12), .I1 (x[0]), .S (\xi_ff[1] [0]), .ZN (n_46));
  CKND2D0 g7262(.A1 (n_484), .A2 (y_max[1]), .ZN (n_45));
  MUX2ND0 g7263(.I0 (y[1]), .I1 (n_13), .S (\yi_ff[2] [1]), .ZN (n_44));
  MUX2ND0 g7265(.I0 (x_max[1]), .I1 (n_11), .S (xo[1]), .ZN (n_43));
  CKND0 g7268(.I (n_39), .ZN (n_40));
  CKND2D1 g7269(.A1 (y[1]), .A2 (n_19), .ZN (n_39));
  CKND2D1 g7270(.A1 (n_10), .A2 (\xi_ff[1] [1]), .ZN (n_38));
  OR2D1 g7271(.A1 (n_20), .A2 (\xi_ff[1] [2]), .Z (n_37));
  NR2XD0 g7272(.A1 (n_10), .A2 (\xi_ff[1] [1]), .ZN (n_36));
  CKND2D1 g7274(.A1 (n_400), .A2 (inc_y), .ZN (n_34));
  CKND2D1 g7275(.A1 (n_535), .A2 (top_line), .ZN (n_33));
  IND2D0 g7276(.A1 (n_426), .B1 (n_457), .ZN (n_32));
  INR2XD0 g7277(.A1 (inc_x), .B1 (n_464), .ZN (n_31));
  CKND0 g7279(.I (n_28), .ZN (n_29));
  CKND2D0 g7280(.A1 (y[2]), .A2 (\yi_ff[1] [2]), .ZN (n_28));
  CKND2D1 g7283(.A1 (x[1]), .A2 (x[0]), .ZN (n_25));
  CKAN2D0 g7284(.A1 (n_7), .A2 (y_max[2]), .Z (n_24));
  CKND2D0 g7287(.A1 (RLO[1]), .A2 (RLO[0]), .ZN (n_22));
  CKND2D1 g7288(.A1 (control[3]), .A2 (control[2]), .ZN (n_21));
  CKND1 g7297(.I (\xi_ff[0] [2]), .ZN (n_20));
  CKND2 g7301(.I (n_135), .ZN (n_19));
  CKND1 g7313(.I (x[1]), .ZN (n_14));
  CKND2 g7316(.I (x[0]), .ZN (n_12));
  CKND1 g7317(.I (x_max[1]), .ZN (n_11));
  CKND1 g7319(.I (\xi_ff[0] [1]), .ZN (n_10));
  CKND1 g7320(.I (x_max[2]), .ZN (n_9));
  CKND2 g7322(.I (n_430), .ZN (n_8));
  CKND0 g7323(.I (yo[2]), .ZN (n_7));
  CKND0 g7324(.I (x_min[0]), .ZN (n_6));
  CKND0 g7325(.I (x_min[1]), .ZN (n_5));
  CKND0 g7326(.I (x_min[2]), .ZN (n_4));
  IND2D1 g7327(.A1 (inc_y), .B1 (n_458), .ZN (n_559));
  NR2D0 g7331(.A1 (n_136), .A2 (n_519), .ZN (n_560));
  DFD4 rst_int_reg(.CP (clk), .D (n_113), .Q (rst_int), .QN
       (UNCONNECTED18));
  OR2D0 g7337(.A1 (y[2]), .A2 (\yi_ff[1] [2]), .Z (n_439));
  NR2D0 g7338(.A1 (y[2]), .A2 (\yi_ff[1] [2]), .ZN (n_440));
  AN2XD1 g7340(.A1 (n_472), .A2 (xi[0]), .Z (n_441));
  MUX2ND0 g7341(.I0 (n_12), .I1 (x[0]), .S (x_max[0]), .ZN (n_442));
  CKND0 g620(.I (n_458), .ZN (n_459));
  NR2XD1 g621(.A1 (n_455), .A2 (n_457), .ZN (n_458));
  IND2D2 g625(.A1 (n_21), .B1 (n_472), .ZN (n_455));
  CKND1 g627(.I (n_597), .ZN (n_457));
  MAOI22D1 g616(.A1 (n_460), .A2 (n_462), .B1 (n_463), .B2 (n_464), .ZN
       (n_465));
  CKND2D2 g626(.A1 (n_164), .A2 (inc_x), .ZN (n_460));
  NR2D1 g618(.A1 (n_34), .A2 (n_461), .ZN (n_462));
  CKND2D2 g623(.A1 (n_598), .A2 (n_472), .ZN (n_461));
  CKND2D1 g624(.A1 (n_597), .A2 (n_502), .ZN (n_463));
  CKND1 g629(.I (n_472), .ZN (n_464));
  IOA21D1 g16(.A1 (n_76), .A2 (n_32), .B (n_467), .ZN (n_468));
  CKND2D2 g17(.A1 (n_88), .A2 (n_77), .ZN (n_467));
  NR2XD0 g18(.A1 (n_470), .A2 (n_146), .ZN (n_471));
  INVD3 g19(.I (n_469), .ZN (n_470));
  NR2XD2 g20(.A1 (rst_int), .A2 (reset), .ZN (n_469));
  NR2XD3 g21(.A1 (rst_int), .A2 (reset), .ZN (n_472));
  CKND2 g11(.I (control[3]), .ZN (n_479));
  OAI21D1 g23(.A1 (n_559), .A2 (n_560), .B (n_482), .ZN (n_483));
  CKND2D1 g24(.A1 (n_31), .A2 (n_349), .ZN (n_482));
  MAOI22D1 g35(.A1 (n_45), .A2 (yo[1]), .B1 (n_484), .B2 (y_max[1]),
       .ZN (n_485));
  NR2XD1 g36(.A1 (yo[0]), .A2 (n_417), .ZN (n_484));
  MOAI22D1 g15(.A1 (xo[0]), .A2 (x_max[0]), .B1 (xo[0]), .B2
       (x_max[0]), .ZN (n_486));
  CKND2D0 g14(.A1 (n_491), .A2 (n_502), .ZN (n_492));
  NR2D3 g7353(.A1 (control[1]), .A2 (control[0]), .ZN (n_491));
  MUX2ND0 g7354(.I0 (n_494), .I1 (n_524), .S (control[2]), .ZN (n_496));
  INVD1 fopt24(.I (n_524), .ZN (n_494));
  NR2XD3 g7358(.A1 (n_149), .A2 (control[3]), .ZN (n_502));
  NR2XD1 g50(.A1 (n_36), .A2 (n_509), .ZN (n_510));
  CKND2D1 g51(.A1 (n_508), .A2 (\xi_ff[1] [0]), .ZN (n_509));
  CKND1 g52(.I (\xi_ff[0] [0]), .ZN (n_508));
  MOAI22D1 g13(.A1 (xo[2]), .A2 (x_max[2]), .B1 (xo[2]), .B2
       (x_max[2]), .ZN (n_512));
  CKMUX2D1 g38(.I0 (y_min[2]), .I1 (n_515), .S (n_598), .Z (n_516));
  MOAI22D1 g39(.A1 (n_513), .A2 (y[2]), .B1 (n_513), .B2 (y[2]), .ZN
       (n_515));
  CKND2D1 g40(.A1 (y[1]), .A2 (y[0]), .ZN (n_513));
  OAI32D1 g95(.A1 (n_464), .A2 (n_535), .A3 (n_517), .B1 (n_464), .B2
       (n_33), .ZN (n_518));
  AOI21D1 g96(.A1 (n_92), .A2 (n_439), .B (n_29), .ZN (n_517));
  OAI21D1 g126(.A1 (n_459), .A2 (n_522), .B (n_465), .ZN (n_523));
  AOI22D2 g127(.A1 (n_520), .A2 (n_521), .B1 (n_74), .B2 (n_49), .ZN
       (n_522));
  CKND2 g128(.I (n_519), .ZN (n_520));
  OAI21D4 g129(.A1 (n_510), .A2 (n_68), .B (n_37), .ZN (n_519));
  CKND0 g130(.I (good), .ZN (n_521));
  AN2D4 g111(.A1 (control[0]), .A2 (control[1]), .Z (n_524));
  OR2D0 g104(.A1 (n_527), .A2 (n_470), .Z (n_528));
  NR2XD0 g106(.A1 (n_494), .A2 (n_525), .ZN (n_527));
  CKND2D2 g109(.A1 (n_479), .A2 (n_149), .ZN (n_525));
  IND2D0 g100(.A1 (n_527), .B1 (n_463), .ZN (n_529));
  AOI21D0 g99(.A1 (n_164), .A2 (n_151), .B (n_527), .ZN (n_530));
  AO31D0 g105(.A1 (n_531), .A2 (n_491), .A3 (nt), .B (n_470), .Z
       (n_532));
  CKND1 g108(.I (n_525), .ZN (n_531));
  IND4D0 g102(.A1 (nt), .B1 (n_141), .B2 (n_531), .B3 (n_491), .ZN
       (n_533));
  IOA21D0 g103(.A1 (n_531), .A2 (n_426), .B (n_141), .ZN (n_534));
  IND2D2 g107(.A1 (n_157), .B1 (n_525), .ZN (n_535));
  OAI21D0 g101(.A1 (n_457), .A2 (n_525), .B (n_141), .ZN (n_536));
  CKND0 g58(.I (xi[2]), .ZN (n_537));
  OAI21D1 g55(.A1 (n_160), .A2 (n_539), .B (n_141), .ZN (n_540));
  MOAI22D0 g56(.A1 (x_min[2]), .A2 (n_537), .B1 (n_602), .B2 (n_538),
       .ZN (n_539));
  AOI22D1 g57(.A1 (x_min[2]), .A2 (n_537), .B1 (x_min[1]), .B2 (n_144),
       .ZN (n_538));
  CKND1 g7360(.I (yi[1]), .ZN (n_541));
  FCICOND1 g7361(.A (y_min[2]), .B (n_544), .CI (n_143), .CON (n_545));
  ND2D1 g7362(.A1 (n_542), .A2 (n_543), .ZN (n_544));
  OAI211D1 g7363(.A1 (n_541), .A2 (y_min[1]), .B (y_min[0]), .C
       (n_146), .ZN (n_542));
  CKND2D0 g7364(.A1 (y_min[1]), .A2 (n_541), .ZN (n_543));
  DFD2 inc_y_reg(.CP (clk), .D (n_523), .Q (inc_y), .QN
       (UNCONNECTED19));
  INR2XD4 g7408(.A1 (control[0]), .B1 (control[1]), .ZN (n_597));
  MUX2D0 g7409(.I0 (y_min[0]), .I1 (n_16), .S (n_598), .Z (n_599));
  ND2D4 g22(.A1 (n_426), .A2 (n_502), .ZN (n_598));
  ND2D1 g7410(.A1 (n_467), .A2 (n_600), .ZN (n_601));
  CKND2D0 g7411(.A1 (n_496), .A2 (n_76), .ZN (n_600));
  IND3D1 g2(.A1 (xi[0]), .B1 (x_min[0]), .B2 (n_138), .ZN (n_602));
  DFQD4 \control_reg[0] (.CP (rc_gclk_7532), .D (n_97), .Q
       (control[0]));
  DFQD4 \xi_ff_reg[0][2] (.CP (rc_gclk_7520), .D (n_411), .Q
       (\xi_ff[0] [2]));
endmodule

