
// Generated by Cadence Encounter(R) RTL Compiler v12.10-s012_1

// Verification Directory fv/Elevator 

module Elevator(clk, rst, req, up, dwn, trigger, complete);
  input clk, rst;
  input [3:0] req;
  output up, dwn, trigger, complete;
  wire clk, rst;
  wire [3:0] req;
  wire up, dwn, trigger, complete;
  wire [3:0] floor;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_22, n_23, n_24, n_26;
  wire n_27, n_28, n_29, n_34, n_40;
  SDFQND0 \floor_reg[3] (.CP (clk), .D (n_28), .SI (n_27), .SE (n_29),
       .QN (floor[3]));
  AO222D0 g814(.A1 (n_23), .A2 (n_27), .B1 (n_24), .B2 (floor[3]), .C1
       (n_40), .C2 (floor[2]), .Z (n_28));
  SDFQND0 \floor_reg[1] (.CP (clk), .D (n_15), .SI (n_5), .SE (n_29),
       .QN (floor[1]));
  AO221D0 g816(.A1 (n_22), .A2 (floor[2]), .B1 (n_40), .B2 (n_19), .C
       (n_24), .Z (n_26));
  SDFQND0 \floor_reg[0] (.CP (clk), .D (n_4), .SI (n_6), .SE (n_29),
       .QN (floor[0]));
  AO211D0 g818(.A1 (n_20), .A2 (floor[2]), .B (n_22), .C (n_17), .Z
       (n_23));
  DFKCNQD1 trigger_reg(.CP (clk), .CN (n_34), .D (n_29), .Q (trigger));
  SDFQND0 complete_reg(.CP (clk), .D (complete), .SI (n_9), .SE (rst),
       .QN (n_34));
  DFKCNQD1 dwn_reg(.CP (clk), .CN (n_12), .D (n_20), .Q (dwn));
  AN3D1 g822(.A1 (n_20), .A2 (n_18), .A3 (n_19), .Z (n_24));
  MOAI22D0 g823(.A1 (n_14), .A2 (n_18), .B1 (n_17), .B2 (n_16), .ZN
       (n_22));
  MOAI22D0 g824(.A1 (n_14), .A2 (n_13), .B1 (n_17), .B2 (n_13), .ZN
       (n_15));
  NR2D0 g827(.A1 (n_14), .A2 (n_12), .ZN (n_29));
  DFQD1 up_reg(.CP (clk), .D (n_17), .Q (up));
  CKND0 g828(.I (n_14), .ZN (n_20));
  NR2D0 g831(.A1 (n_10), .A2 (n_3), .ZN (n_17));
  ND2D0 g829(.A1 (rst), .A2 (n_10), .ZN (n_14));
  INR2D0 g832(.A1 (n_10), .B1 (n_12), .ZN (n_9));
  MAOI222D0 g833(.A (n_8), .B (floor[3]), .C (req[3]), .ZN (n_10));
  MAOI222D0 g834(.A (n_7), .B (floor[2]), .C (n_0), .ZN (n_8));
  OAI221D0 g835(.A1 (n_18), .A2 (req[1]), .B1 (req[0]), .B2 (n_1), .C
       (n_16), .ZN (n_7));
  OAI221D0 g836(.A1 (floor[3]), .A2 (req[3]), .B1 (req[2]), .B2 (n_19),
       .C (n_2), .ZN (n_12));
  INR2D0 g837(.A1 (n_16), .B1 (n_18), .ZN (n_13));
  ND2D0 g840(.A1 (n_6), .A2 (n_5), .ZN (n_16));
  NR2D0 g841(.A1 (n_6), .A2 (n_5), .ZN (n_18));
  NR2D0 g842(.A1 (n_6), .A2 (n_3), .ZN (n_4));
  OA22D0 g838(.A1 (floor[0]), .A2 (req[0]), .B1 (req[1]), .B2
       (floor[1]), .Z (n_2));
  CKAN2D1 g839(.A1 (floor[1]), .A2 (req[1]), .Z (n_1));
  CKND0 g843(.I (req[2]), .ZN (n_0));
  CKND0 g844(.I (floor[3]), .ZN (n_27));
  CKND0 g846(.I (rst), .ZN (n_3));
  CKND0 g849(.I (floor[1]), .ZN (n_5));
  CKND0 g845(.I (n_34), .ZN (complete));
  CKND0 g848(.I (floor[0]), .ZN (n_6));
  DFXD1 \floor_reg[2] (.CP (clk), .DA (floor[2]), .DB (n_26), .SA
       (n_29), .Q (floor[2]), .QN (n_19));
  INR2D1 g2(.A1 (n_17), .B1 (n_16), .ZN (n_40));
endmodule

