/*
###############################################################
#  Generated by:      Cadence Encounter 10.12-s181_1
#  OS:                Linux x86_64(Host ID co2046-06.ece.iastate.edu)
#  Generated on:      Thu Dec 10 21:14:57 2015
#  Design:            triangle
#  Command:           saveNetlist -excludeLeafCell design_pr.v
###############################################################
*/
// Generated by Cadence Encounter(R) RTL Compiler v10.10-s209_1
// Verification Directory fv/triangle 
module RC_CG_MOD (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   CKLNQD1 RC_CGIC_INST (.TE(1'b0), 
	.Q(ck_out), 
	.E(enable), 
	.CP(ck_in));
endmodule

module RC_CG_MOD_1 (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   CKLNQD1 RC_CGIC_INST (.TE(1'b0), 
	.Q(ck_out), 
	.E(enable), 
	.CP(ck_in));
endmodule

module RC_CG_MOD_10 (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   CKLNQD1 RC_CGIC_INST (.TE(1'b0), 
	.Q(ck_out), 
	.E(enable), 
	.CP(ck_in));
endmodule

module RC_CG_MOD_11 (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   CKLNQD1 RC_CGIC_INST (.TE(1'b0), 
	.Q(ck_out), 
	.E(enable), 
	.CP(ck_in));
endmodule

module RC_CG_MOD_12 (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   CKLNQD1 RC_CGIC_INST (.TE(1'b0), 
	.Q(ck_out), 
	.E(enable), 
	.CP(ck_in));
endmodule

module RC_CG_MOD_13 (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   CKLNQD1 RC_CGIC_INST (.TE(1'b0), 
	.Q(ck_out), 
	.E(enable), 
	.CP(ck_in));
endmodule

module RC_CG_MOD_14 (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   CKLNQD1 RC_CGIC_INST (.TE(1'b0), 
	.Q(ck_out), 
	.E(enable), 
	.CP(ck_in));
endmodule

module RC_CG_MOD_15 (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   CKLNQD1 RC_CGIC_INST (.TE(1'b0), 
	.Q(ck_out), 
	.E(enable), 
	.CP(ck_in));
endmodule

module RC_CG_MOD_16 (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   CKLNQD1 RC_CGIC_INST (.TE(1'b0), 
	.Q(ck_out), 
	.E(enable), 
	.CP(ck_in));
endmodule

module RC_CG_MOD_17 (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   CKLNQD1 RC_CGIC_INST (.TE(1'b0), 
	.Q(ck_out), 
	.E(enable), 
	.CP(ck_in));
endmodule

module RC_CG_MOD_451 (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   CKLHQD1 RC_CGIC_INST (.TE(1'b0), 
	.Q(ck_out), 
	.E(enable), 
	.CPN(ck_in));
endmodule

module RC_CG_MOD_451_1 (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   CKLHQD1 RC_CGIC_INST (.TE(1'b0), 
	.Q(ck_out), 
	.E(enable), 
	.CPN(ck_in));
endmodule

module RC_CG_MOD_2 (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   CKLNQD1 RC_CGIC_INST (.TE(1'b0), 
	.Q(ck_out), 
	.E(enable), 
	.CP(ck_in));
endmodule

module RC_CG_MOD_3 (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   CKLNQD1 RC_CGIC_INST (.TE(1'b0), 
	.Q(ck_out), 
	.E(enable), 
	.CP(ck_in));
endmodule

module RC_CG_MOD_4 (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   CKLNQD1 RC_CGIC_INST (.TE(1'b0), 
	.Q(ck_out), 
	.E(enable), 
	.CP(ck_in));
endmodule

module RC_CG_MOD_5 (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   CKLNQD1 RC_CGIC_INST (.TE(1'b0), 
	.Q(ck_out), 
	.E(enable), 
	.CP(ck_in));
endmodule

module RC_CG_MOD_6 (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   CKLNQD1 RC_CGIC_INST (.TE(1'b0), 
	.Q(ck_out), 
	.E(enable), 
	.CP(ck_in));
endmodule

module RC_CG_MOD_7 (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   CKLNQD1 RC_CGIC_INST (.TE(1'b0), 
	.Q(ck_out), 
	.E(enable), 
	.CP(ck_in));
endmodule

module RC_CG_MOD_8 (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   CKLNQD1 RC_CGIC_INST (.TE(1'b0), 
	.Q(ck_out), 
	.E(enable), 
	.CP(ck_in));
endmodule

module RC_CG_MOD_9 (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   CKLNQD1 RC_CGIC_INST (.TE(1'b0), 
	.Q(ck_out), 
	.E(enable), 
	.CP(ck_in));
endmodule

module mult_signed (
	A, 
	B, 
	Z);
   input [6:0] A;
   input [6:0] B;
   output [6:0] Z;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_66;
   wire n_68;

   XOR3D0 g1761 (.Z(Z[6]), 
	.A3(n_68), 
	.A2(n_62), 
	.A1(n_63));
   FA1D0 g1762 (.S(Z[5]), 
	.CO(n_68), 
	.CI(n_66), 
	.B(n_58), 
	.A(n_57));
   FA1D0 g1763 (.S(Z[4]), 
	.CO(n_66), 
	.CI(n_59), 
	.B(n_51), 
	.A(n_64));
   FA1D0 g1764 (.S(Z[3]), 
	.CO(n_64), 
	.CI(n_60), 
	.B(n_52), 
	.A(n_45));
   CKXOR2D0 g1765 (.Z(n_63), 
	.A2(n_48), 
	.A1(n_56));
   XNR4D0 g1766 (.ZN(n_62), 
	.A4(n_44), 
	.A3(n_49), 
	.A2(n_37), 
	.A1(n_31));
   HA1D0 g1767 (.S(Z[2]), 
	.CO(n_60), 
	.B(n_55), 
	.A(n_40));
   FA1D0 g1768 (.S(n_59), 
	.CO(n_58), 
	.CI(n_46), 
	.B(n_32), 
	.A(n_39));
   FA1D0 g1769 (.S(n_57), 
	.CO(n_56), 
	.CI(n_47), 
	.B(n_43), 
	.A(n_50));
   AO21D0 g1770 (.Z(n_55), 
	.B(n_53), 
	.A2(A[0]), 
	.A1(n_29));
   HA1D0 g1771 (.S(Z[1]), 
	.CO(n_53), 
	.B(n_38), 
	.A(n_27));
   HA1D0 g1772 (.S(n_52), 
	.CO(n_51), 
	.B(n_41), 
	.A(n_35));
   HA1D0 g1773 (.S(n_50), 
	.CO(n_49), 
	.B(n_42), 
	.A(n_36));
   MOAI22D0 g1774 (.ZN(n_48), 
	.B2(n_16), 
	.B1(n_29), 
	.A2(n_15), 
	.A1(n_34));
   OAI22D0 g1775 (.ZN(n_47), 
	.B2(n_15), 
	.B1(n_30), 
	.A2(n_21), 
	.A1(n_34));
   OAI22D0 g1776 (.ZN(n_46), 
	.B2(n_21), 
	.B1(n_30), 
	.A2(n_18), 
	.A1(n_34));
   OAI22D0 g1777 (.ZN(n_45), 
	.B2(n_18), 
	.B1(n_30), 
	.A2(n_26), 
	.A1(n_34));
   AOI22D0 g1778 (.ZN(n_44), 
	.B2(n_24), 
	.B1(n_28), 
	.A2(n_13), 
	.A1(n_33));
   AO22D0 g1779 (.Z(n_43), 
	.B2(n_28), 
	.B1(n_13), 
	.A2(n_25), 
	.A1(n_33));
   AO22D0 g1780 (.Z(n_42), 
	.B2(n_19), 
	.B1(B[0]), 
	.A2(n_9), 
	.A1(n_17));
   AO22D0 g1781 (.Z(n_41), 
	.B2(n_14), 
	.B1(B[0]), 
	.A2(n_9), 
	.A1(n_22));
   AO22D0 g1782 (.Z(n_40), 
	.B2(n_22), 
	.B1(B[0]), 
	.A2(n_9), 
	.A1(n_20));
   AO22D0 g1783 (.Z(n_39), 
	.B2(n_17), 
	.B1(B[0]), 
	.A2(n_9), 
	.A1(n_14));
   AO22D0 g1784 (.Z(n_38), 
	.B2(n_9), 
	.B1(n_2), 
	.A2(B[0]), 
	.A1(n_20));
   AOI22D0 g1785 (.ZN(n_37), 
	.B2(B[0]), 
	.B1(n_23), 
	.A2(n_9), 
	.A1(n_19));
   OA211D0 g1786 (.Z(n_36), 
	.C(B[5]), 
	.B(n_11), 
	.A2(n_7), 
	.A1(n_2));
   OA211D0 g1787 (.Z(n_35), 
	.C(B[3]), 
	.B(n_12), 
	.A2(n_8), 
	.A1(n_2));
   OAI211D0 g1788 (.ZN(n_34), 
	.C(n_10), 
	.B(n_30), 
	.A2(B[3]), 
	.A1(B[2]));
   AOI211D0 g1789 (.ZN(n_33), 
	.C(n_4), 
	.B(n_28), 
	.A2(B[4]), 
	.A1(B[5]));
   CKAN2D0 g1790 (.Z(n_32), 
	.A2(A[0]), 
	.A1(n_28));
   OAI211D0 g1791 (.ZN(n_31), 
	.C(A[0]), 
	.B(n_5), 
	.A2(B[5]), 
	.A1(B[6]));
   CKND0 g1792 (.ZN(n_29), 
	.I(n_30));
   IND2D0 g1793 (.ZN(n_30), 
	.B1(n_12), 
	.A1(n_8));
   INR2D0 g1794 (.ZN(n_28), 
	.B1(n_7), 
	.A1(n_11));
   NR2D0 g1795 (.ZN(n_27), 
	.A2(n_1), 
	.A1(Z[0]));
   MUX2ND0 g1796 (.ZN(n_26), 
	.S(B[3]), 
	.I1(n_2), 
	.I0(A[0]));
   MUX2ND0 g1797 (.ZN(n_25), 
	.S(B[5]), 
	.I1(A[0]), 
	.I0(n_2));
   CKXOR2D0 g1798 (.Z(n_24), 
	.A2(A[2]), 
	.A1(B[5]));
   MUX2ND0 g1799 (.ZN(n_23), 
	.S(A[6]), 
	.I1(B[1]), 
	.I0(n_1));
   MUX2ND0 g1800 (.ZN(n_22), 
	.S(A[2]), 
	.I1(B[1]), 
	.I0(n_1));
   MUX2ND0 g1801 (.ZN(n_21), 
	.S(A[2]), 
	.I1(n_3), 
	.I0(B[3]));
   MUX2ND0 g1802 (.ZN(n_20), 
	.S(A[1]), 
	.I1(B[1]), 
	.I0(n_1));
   MUX2ND0 g1803 (.ZN(n_19), 
	.S(A[5]), 
	.I1(B[1]), 
	.I0(n_1));
   MUX2ND0 g1804 (.ZN(n_18), 
	.S(A[1]), 
	.I1(n_3), 
	.I0(B[3]));
   MUX2ND0 g1805 (.ZN(n_17), 
	.S(A[4]), 
	.I1(B[1]), 
	.I0(n_1));
   MUX2ND0 g1806 (.ZN(n_16), 
	.S(A[4]), 
	.I1(B[3]), 
	.I0(n_3));
   MUX2ND0 g1807 (.ZN(n_15), 
	.S(A[3]), 
	.I1(n_3), 
	.I0(B[3]));
   MUX2ND0 g1808 (.ZN(n_14), 
	.S(A[3]), 
	.I1(B[1]), 
	.I0(n_1));
   CKXOR2D0 g1809 (.Z(n_13), 
	.A2(A[1]), 
	.A1(B[5]));
   CKND2D0 g1810 (.ZN(n_12), 
	.A2(B[1]), 
	.A1(B[2]));
   CKND2D0 g1811 (.ZN(n_11), 
	.A2(B[3]), 
	.A1(B[4]));
   CKND2D0 g1812 (.ZN(n_10), 
	.A2(B[3]), 
	.A1(B[2]));
   NR2D0 g1813 (.ZN(n_9), 
	.A2(B[0]), 
	.A1(n_1));
   NR2D0 g1814 (.ZN(n_8), 
	.A2(B[2]), 
	.A1(B[1]));
   NR2D0 g1815 (.ZN(n_7), 
	.A2(B[4]), 
	.A1(B[3]));
   NR2D0 g1816 (.ZN(Z[0]), 
	.A2(n_0), 
	.A1(n_2));
   CKND2D0 g1817 (.ZN(n_5), 
	.A2(B[5]), 
	.A1(B[6]));
   NR2D0 g1818 (.ZN(n_4), 
	.A2(B[4]), 
	.A1(B[5]));
   CKND0 g1819 (.ZN(n_3), 
	.I(B[3]));
   CKND0 g1820 (.ZN(n_2), 
	.I(A[0]));
   CKND0 g1821 (.ZN(n_1), 
	.I(B[1]));
   CKND0 g1822 (.ZN(n_0), 
	.I(B[0]));
endmodule

module triangle (
	clk, 
	reset, 
	nt, 
	xi, 
	yi, 
	busy, 
	po, 
	xo, 
	yo);
   input clk;
   input reset;
   input nt;
   input [2:0] xi;
   input [2:0] yi;
   output busy;
   output po;
   output [2:0] xo;
   output [2:0] yo;

   // Internal wires
   wire FE_PSN28_n_598;
   wire FE_PSN27_n_457;
   wire FE_PSN26_n_470;
   wire FE_PSN25_FE_OCP_RBN13_n_470;
   wire FE_PSN24_n_598;
   wire FE_PSN23_n_527;
   wire FE_OCP_RBN22_control_3_;
   wire FE_RN_18_0;
   wire FE_RN_17_0;
   wire FE_OCP_RBN13_n_470;
   wire FE_RN_16_0;
   wire FE_RN_15_0;
   wire FE_RN_14_0;
   wire clk__L6_N1;
   wire clk__L6_N0;
   wire clk__L5_N3;
   wire clk__L5_N2;
   wire clk__L5_N1;
   wire clk__L5_N0;
   wire clk__L4_N5;
   wire clk__L4_N4;
   wire clk__L4_N3;
   wire clk__L4_N2;
   wire clk__L4_N1;
   wire clk__L4_N0;
   wire clk__L3_N9;
   wire clk__L3_N8;
   wire clk__L3_N7;
   wire clk__L3_N6;
   wire clk__L3_N5;
   wire clk__L3_N4;
   wire clk__L3_N3;
   wire clk__L3_N2;
   wire clk__L3_N1;
   wire clk__L3_N0;
   wire clk__L2_N6;
   wire clk__L2_N5;
   wire clk__L2_N4;
   wire clk__L2_N3;
   wire clk__L2_N2;
   wire clk__L2_N1;
   wire clk__L2_N0;
   wire clk__L1_N0;
   wire FE_OCPN2_n_169;
   wire FE_OCPN1_n_418;
   wire FE_OCPN0_x_0_;
   wire [6:0] AD;
   wire [6:0] BC;
   wire [6:0] RLO;
   wire [2:0] x_min;
   wire [2:0] x;
   wire [2:0] \xi_ff[2] ;
   wire [2:0] \yi_ff[0] ;
   wire [2:0] \yi_ff[1] ;
   wire [2:0] \yi_ff[2] ;
   wire [6:0] sub_op0;
   wire [6:0] sub_op1;
   wire [2:0] x_max;
   wire [2:0] \xi_ff[0] ;
   wire [2:0] \xi_ff[1] ;
   wire [2:0] y_max;
   wire [2:0] y_min;
   wire [2:0] y;
   wire [3:0] control;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;
   wire UNCONNECTED7;
   wire UNCONNECTED8;
   wire UNCONNECTED9;
   wire UNCONNECTED10;
   wire UNCONNECTED11;
   wire UNCONNECTED12;
   wire UNCONNECTED13;
   wire UNCONNECTED14;
   wire UNCONNECTED15;
   wire UNCONNECTED16;
   wire UNCONNECTED17;
   wire UNCONNECTED18;
   wire UNCONNECTED19;
   wire check;
   wire good;
   wire inc_x;
   wire inc_y;
   wire mul_en;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_24;
   wire n_25;
   wire n_28;
   wire n_29;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_62;
   wire n_63;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_88;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_94;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_112;
   wire n_113;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_127;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_143;
   wire n_144;
   wire n_146;
   wire n_149;
   wire n_151;
   wire n_152;
   wire n_155;
   wire n_157;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_164;
   wire n_165;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_175;
   wire n_177;
   wire n_178;
   wire n_179;
   wire n_180;
   wire n_181;
   wire n_182;
   wire n_183;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_191;
   wire n_192;
   wire n_193;
   wire n_194;
   wire n_195;
   wire n_196;
   wire n_197;
   wire n_200;
   wire n_201;
   wire n_202;
   wire n_205;
   wire n_206;
   wire n_207;
   wire n_208;
   wire n_209;
   wire n_210;
   wire n_211;
   wire n_212;
   wire n_213;
   wire n_214;
   wire n_215;
   wire n_218;
   wire n_219;
   wire n_220;
   wire n_221;
   wire n_222;
   wire n_223;
   wire n_224;
   wire n_225;
   wire n_226;
   wire n_227;
   wire n_228;
   wire n_229;
   wire n_230;
   wire n_231;
   wire n_232;
   wire n_233;
   wire n_234;
   wire n_235;
   wire n_236;
   wire n_237;
   wire n_238;
   wire n_239;
   wire n_240;
   wire n_241;
   wire n_242;
   wire n_243;
   wire n_244;
   wire n_245;
   wire n_246;
   wire n_247;
   wire n_248;
   wire n_249;
   wire n_250;
   wire n_251;
   wire n_252;
   wire n_253;
   wire n_254;
   wire n_255;
   wire n_256;
   wire n_257;
   wire n_258;
   wire n_259;
   wire n_260;
   wire n_261;
   wire n_262;
   wire n_263;
   wire n_264;
   wire n_265;
   wire n_266;
   wire n_267;
   wire n_268;
   wire n_269;
   wire n_270;
   wire n_271;
   wire n_272;
   wire n_273;
   wire n_274;
   wire n_275;
   wire n_276;
   wire n_277;
   wire n_278;
   wire n_279;
   wire n_280;
   wire n_281;
   wire n_282;
   wire n_283;
   wire n_284;
   wire n_285;
   wire n_286;
   wire n_287;
   wire n_288;
   wire n_289;
   wire n_290;
   wire n_291;
   wire n_292;
   wire n_293;
   wire n_294;
   wire n_295;
   wire n_296;
   wire n_297;
   wire n_298;
   wire n_299;
   wire n_300;
   wire n_301;
   wire n_302;
   wire n_303;
   wire n_304;
   wire n_305;
   wire n_306;
   wire n_307;
   wire n_308;
   wire n_309;
   wire n_310;
   wire n_312;
   wire n_313;
   wire n_314;
   wire n_316;
   wire n_317;
   wire n_318;
   wire n_319;
   wire n_320;
   wire n_321;
   wire n_322;
   wire n_323;
   wire n_324;
   wire n_325;
   wire n_326;
   wire n_327;
   wire n_328;
   wire n_329;
   wire n_330;
   wire n_331;
   wire n_332;
   wire n_333;
   wire n_335;
   wire n_336;
   wire n_339;
   wire n_340;
   wire n_341;
   wire n_342;
   wire n_343;
   wire n_344;
   wire n_345;
   wire n_347;
   wire n_349;
   wire n_351;
   wire n_352;
   wire n_353;
   wire n_354;
   wire n_355;
   wire n_356;
   wire n_358;
   wire n_359;
   wire n_360;
   wire n_361;
   wire n_362;
   wire n_363;
   wire n_364;
   wire n_365;
   wire n_366;
   wire n_367;
   wire n_368;
   wire n_369;
   wire n_370;
   wire n_371;
   wire n_372;
   wire n_374;
   wire n_375;
   wire n_377;
   wire n_378;
   wire n_379;
   wire n_380;
   wire n_381;
   wire n_382;
   wire n_384;
   wire n_385;
   wire n_386;
   wire n_387;
   wire n_388;
   wire n_389;
   wire n_390;
   wire n_392;
   wire n_398;
   wire n_400;
   wire n_402;
   wire n_404;
   wire n_405;
   wire n_406;
   wire n_407;
   wire n_408;
   wire n_410;
   wire n_411;
   wire n_413;
   wire n_414;
   wire n_416;
   wire n_417;
   wire n_418;
   wire n_422;
   wire n_426;
   wire n_430;
   wire n_432;
   wire n_434;
   wire n_439;
   wire n_440;
   wire n_441;
   wire n_442;
   wire n_455;
   wire n_457;
   wire n_458;
   wire n_459;
   wire n_460;
   wire n_461;
   wire n_462;
   wire n_463;
   wire n_464;
   wire n_465;
   wire n_467;
   wire n_468;
   wire n_469;
   wire n_470;
   wire n_471;
   wire n_472;
   wire n_482;
   wire n_483;
   wire n_484;
   wire n_485;
   wire n_486;
   wire n_491;
   wire n_492;
   wire n_494;
   wire n_496;
   wire n_502;
   wire n_508;
   wire n_509;
   wire n_510;
   wire n_512;
   wire n_513;
   wire n_515;
   wire n_516;
   wire n_517;
   wire n_518;
   wire n_519;
   wire n_520;
   wire n_521;
   wire n_522;
   wire n_523;
   wire n_524;
   wire n_525;
   wire n_527;
   wire n_528;
   wire n_529;
   wire n_530;
   wire n_531;
   wire n_532;
   wire n_533;
   wire n_534;
   wire n_535;
   wire n_536;
   wire n_537;
   wire n_538;
   wire n_539;
   wire n_540;
   wire n_541;
   wire n_542;
   wire n_543;
   wire n_544;
   wire n_545;
   wire n_559;
   wire n_560;
   wire n_597;
   wire n_598;
   wire n_599;
   wire n_600;
   wire n_601;
   wire n_602;
   wire rc_gclk;
   wire rc_gclk_7484;
   wire rc_gclk_7488;
   wire rc_gclk_7492;
   wire rc_gclk_7496;
   wire rc_gclk_7500;
   wire rc_gclk_7504;
   wire rc_gclk_7508;
   wire rc_gclk_7512;
   wire rc_gclk_7516;
   wire rc_gclk_7520;
   wire rc_gclk_7524;
   wire rc_gclk_7528;
   wire rc_gclk_7532;
   wire rc_gclk_7536;
   wire rc_gclk_7540;
   wire rc_gclk_7544;
   wire rc_gclk_7548;
   wire rc_gclk_7552;
   wire rc_gclk_7558;
   wire rst_int;
   wire sub_en;
   wire top_line;

   BUFFD0 FE_PSC28_n_598 (.Z(FE_PSN28_n_598), 
	.I(FE_PSN24_n_598));
   BUFFD1 FE_PSC27_n_457 (.Z(FE_PSN27_n_457), 
	.I(n_457));
   CKBD1 FE_PSC26_n_470 (.Z(FE_PSN26_n_470), 
	.I(n_470));
   CKBD1 FE_PSC25_FE_OCP_RBN13_n_470 (.Z(FE_PSN25_FE_OCP_RBN13_n_470), 
	.I(FE_OCP_RBN13_n_470));
   BUFFD2 FE_PSC24_n_598 (.Z(FE_PSN24_n_598), 
	.I(n_598));
   BUFFD0 FE_PSC23_n_527 (.Z(FE_PSN23_n_527), 
	.I(n_527));
   CKND4 FE_OCP_RBC22_control_3_ (.ZN(FE_OCP_RBN22_control_3_), 
	.I(control[3]));
   INR2XD2 FE_RC_46_0 (.ZN(n_426), 
	.B1(control[0]), 
	.A1(control[1]));
   INVD1 FE_RC_45_0 (.ZN(FE_RN_18_0), 
	.I(control[1]));
   NR2D2 FE_RC_44_0 (.ZN(FE_RN_17_0), 
	.A2(control[0]), 
	.A1(FE_RN_18_0));
   CKND2D3 FE_RC_43_0 (.ZN(n_422), 
	.A2(n_155), 
	.A1(FE_RN_17_0));
   ND2D1 FE_RC_42_0 (.ZN(n_494), 
	.A2(control[0]), 
	.A1(control[1]));
   AN2D4 FE_RC_41_0 (.Z(n_524), 
	.A2(control[1]), 
	.A1(control[0]));
   NR2XD4 FE_RC_40_0 (.ZN(n_469), 
	.A2(reset), 
	.A1(rst_int));
   AOI32D2 FE_RC_39_0 (.ZN(n_206), 
	.B2(xi[1]), 
	.B1(n_11), 
	.A3(xi[0]), 
	.A2(n_193), 
	.A1(n_137));
   CKND16 FE_OCP_RBC13_n_470 (.ZN(FE_OCP_RBN13_n_470), 
	.I(n_470));
   OAI21D4 FE_RC_38_0 (.ZN(n_536), 
	.B(FE_OCP_RBN13_n_470), 
	.A2(n_525), 
	.A1(n_457));
   CKND2D4 FE_RC_37_0 (.ZN(n_402), 
	.A2(FE_RN_14_0), 
	.A1(FE_RN_16_0));
   NR2XD1 FE_RC_36_0 (.ZN(FE_RN_16_0), 
	.A2(control[0]), 
	.A1(FE_RN_15_0));
   ND2D2 FE_RC_35_0 (.ZN(FE_RN_15_0), 
	.A2(control[3]), 
	.A1(control[2]));
   INVD1 FE_RC_34_0 (.ZN(FE_RN_14_0), 
	.I(control[1]));
   NR2XD2 FE_RC_33_0 (.ZN(n_491), 
	.A2(control[0]), 
	.A1(control[1]));
   INVD1 clk__L6_I1 (.ZN(clk__L6_N1), 
	.I(clk__L5_N3));
   INVD1 clk__L6_I0 (.ZN(clk__L6_N0), 
	.I(clk__L5_N3));
   BUFFD2 clk__L5_I3 (.Z(clk__L5_N3), 
	.I(clk__L4_N5));
   BUFFD8 clk__L5_I2 (.Z(clk__L5_N2), 
	.I(clk__L4_N3));
   BUFFD8 clk__L5_I1 (.Z(clk__L5_N1), 
	.I(clk__L4_N2));
   BUFFD8 clk__L5_I0 (.Z(clk__L5_N0), 
	.I(clk__L4_N1));
   BUFFD12 clk__L4_I5 (.Z(clk__L4_N5), 
	.I(clk__L3_N9));
   INVD16 clk__L4_I4 (.ZN(clk__L4_N4), 
	.I(clk__L3_N7));
   INVD6 clk__L4_I3 (.ZN(clk__L4_N3), 
	.I(clk__L3_N6));
   INVD6 clk__L4_I2 (.ZN(clk__L4_N2), 
	.I(clk__L3_N4));
   INVD6 clk__L4_I1 (.ZN(clk__L4_N1), 
	.I(clk__L3_N1));
   INVD12 clk__L4_I0 (.ZN(clk__L4_N0), 
	.I(clk__L3_N0));
   INVD4 clk__L3_I9 (.ZN(clk__L3_N9), 
	.I(clk__L2_N6));
   INVD12 clk__L3_I8 (.ZN(clk__L3_N8), 
	.I(clk__L2_N5));
   INVD12 clk__L3_I7 (.ZN(clk__L3_N7), 
	.I(clk__L2_N4));
   INVD12 clk__L3_I6 (.ZN(clk__L3_N6), 
	.I(clk__L2_N3));
   BUFFD3 clk__L3_I5 (.Z(clk__L3_N5), 
	.I(clk__L2_N3));
   INVD3 clk__L3_I4 (.ZN(clk__L3_N4), 
	.I(clk__L2_N3));
   BUFFD1 clk__L3_I3 (.Z(clk__L3_N3), 
	.I(clk__L2_N3));
   BUFFD2 clk__L3_I2 (.Z(clk__L3_N2), 
	.I(clk__L2_N3));
   INVD6 clk__L3_I1 (.ZN(clk__L3_N1), 
	.I(clk__L2_N2));
   INVD12 clk__L3_I0 (.ZN(clk__L3_N0), 
	.I(clk__L2_N1));
   INVD3 clk__L2_I6 (.ZN(clk__L2_N6), 
	.I(clk__L1_N0));
   BUFFD8 clk__L2_I5 (.Z(clk__L2_N5), 
	.I(clk__L1_N0));
   INVD12 clk__L2_I4 (.ZN(clk__L2_N4), 
	.I(clk__L1_N0));
   INVD24 clk__L2_I3 (.ZN(clk__L2_N3), 
	.I(clk__L1_N0));
   INVD12 clk__L2_I2 (.ZN(clk__L2_N2), 
	.I(clk__L1_N0));
   INVD20 clk__L2_I1 (.ZN(clk__L2_N1), 
	.I(clk__L1_N0));
   INVD4 clk__L2_I0 (.ZN(clk__L2_N0), 
	.I(clk__L1_N0));
   INVD24 clk__L1_I0 (.ZN(clk__L1_N0), 
	.I(clk));
   BUFFD1 FE_OCPC2_n_169 (.Z(FE_OCPN2_n_169), 
	.I(n_169));
   BUFFD1 FE_OCPC1_n_418 (.Z(FE_OCPN1_n_418), 
	.I(n_418));
   BUFFD3 FE_OCPC0_x_0_ (.Z(FE_OCPN0_x_0_), 
	.I(x[0]));
   RC_CG_MOD RC_CG_HIER_INST0 (.enable(n_339), 
	.ck_in(clk__L4_N4), 
	.ck_out(rc_gclk), 
	.test(1'b0));
   RC_CG_MOD_1 RC_CG_HIER_INST1 (.enable(n_341), 
	.ck_in(clk__L3_N8), 
	.ck_out(rc_gclk_7484), 
	.test(1'b0));
   RC_CG_MOD_10 RC_CG_HIER_INST10 (.enable(n_532), 
	.ck_in(clk__L4_N0), 
	.ck_out(rc_gclk_7520), 
	.test(1'b0));
   RC_CG_MOD_11 RC_CG_HIER_INST11 (.enable(n_534), 
	.ck_in(clk__L4_N4), 
	.ck_out(rc_gclk_7524), 
	.test(1'b0));
   RC_CG_MOD_12 RC_CG_HIER_INST12 (.enable(n_336), 
	.ck_in(clk__L2_N0), 
	.ck_out(rc_gclk_7528), 
	.test(1'b0));
   RC_CG_MOD_13 RC_CG_HIER_INST13 (.enable(n_533), 
	.ck_in(clk__L3_N8), 
	.ck_out(rc_gclk_7532), 
	.test(1'b0));
   RC_CG_MOD_14 RC_CG_HIER_INST14 (.enable(n_375), 
	.ck_in(clk__L3_N3), 
	.ck_out(rc_gclk_7536), 
	.test(1'b0));
   RC_CG_MOD_15 RC_CG_HIER_INST15 (.enable(n_540), 
	.ck_in(clk__L5_N1), 
	.ck_out(rc_gclk_7540), 
	.test(1'b0));
   RC_CG_MOD_16 RC_CG_HIER_INST16 (.enable(n_374), 
	.ck_in(clk__L5_N2), 
	.ck_out(rc_gclk_7544), 
	.test(1'b0));
   RC_CG_MOD_17 RC_CG_HIER_INST17 (.enable(n_372), 
	.ck_in(clk__L5_N0), 
	.ck_out(rc_gclk_7548), 
	.test(1'b0));
   RC_CG_MOD_451 RC_CG_HIER_INST18 (.enable(n_333), 
	.ck_in(clk__L3_N5), 
	.ck_out(rc_gclk_7552), 
	.test(1'b0));
   RC_CG_MOD_451_1 RC_CG_HIER_INST19 (.enable(inc_y), 
	.ck_in(clk__L3_N2), 
	.ck_out(rc_gclk_7558), 
	.test(1'b0));
   RC_CG_MOD_2 RC_CG_HIER_INST2 (.enable(n_345), 
	.ck_in(clk__L4_N4), 
	.ck_out(rc_gclk_7488), 
	.test(1'b0));
   RC_CG_MOD_3 RC_CG_HIER_INST3 (.enable(n_335), 
	.ck_in(clk__L4_N4), 
	.ck_out(rc_gclk_7492), 
	.test(1'b0));
   RC_CG_MOD_4 RC_CG_HIER_INST4 (.enable(n_536), 
	.ck_in(clk__L2_N2), 
	.ck_out(rc_gclk_7496), 
	.test(1'b0));
   RC_CG_MOD_5 RC_CG_HIER_INST5 (.enable(n_528), 
	.ck_in(clk__L4_N0), 
	.ck_out(rc_gclk_7500), 
	.test(1'b0));
   RC_CG_MOD_6 RC_CG_HIER_INST6 (.enable(n_340), 
	.ck_in(clk__L4_N4), 
	.ck_out(rc_gclk_7504), 
	.test(1'b0));
   RC_CG_MOD_7 RC_CG_HIER_INST7 (.enable(n_344), 
	.ck_in(clk__L4_N4), 
	.ck_out(rc_gclk_7508), 
	.test(1'b0));
   RC_CG_MOD_8 RC_CG_HIER_INST8 (.enable(n_342), 
	.ck_in(clk__L2_N0), 
	.ck_out(rc_gclk_7512), 
	.test(1'b0));
   RC_CG_MOD_9 RC_CG_HIER_INST9 (.enable(n_343), 
	.ck_in(clk__L2_N0), 
	.ck_out(rc_gclk_7516), 
	.test(1'b0));
   mult_signed mul_211_31 (.A({ n_381,
		n_320,
		n_321,
		n_382,
		n_322,
		n_323,
		n_324 }), 
	.B({ n_377,
		n_317,
		n_378,
		n_318,
		n_319,
		n_379,
		n_380 }), 
	.Z({ n_390,
		n_389,
		n_388,
		n_387,
		n_386,
		n_385,
		n_384 }));
   SDFD1 \AD_reg[2]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(n_368), 
	.D(n_353), 
	.CP(rc_gclk));
   SDFQND1 \AD_reg[3]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(AD[3]), 
	.D(n_354), 
	.CP(rc_gclk));
   SDFQND1 \AD_reg[4]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(AD[4]), 
	.D(n_356), 
	.CP(rc_gclk));
   SDFQND1 \AD_reg[5]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(AD[5]), 
	.D(n_355), 
	.CP(rc_gclk));
   SDFQND1 \AD_reg[6]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(AD[6]), 
	.D(n_358), 
	.CP(rc_gclk));
   SDFQND1 \BC_reg[3]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(BC[3]), 
	.D(n_354), 
	.CP(rc_gclk_7504));
   SDFQND1 \BC_reg[4]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(BC[4]), 
	.D(n_356), 
	.CP(rc_gclk_7504));
   SDFQND1 \BC_reg[5]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(BC[5]), 
	.D(n_355), 
	.CP(rc_gclk_7504));
   SDFQND1 \BC_reg[6]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(BC[6]), 
	.D(n_358), 
	.CP(rc_gclk_7504));
   SDFD4 \D0_reg[0]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(n_367), 
	.D(n_404), 
	.CP(rc_gclk_7512));
   SDFD4 \D0_reg[1]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(n_365), 
	.D(n_405), 
	.CP(rc_gclk_7512));
   SDFD4 \D0_reg[4]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(n_363), 
	.D(n_407), 
	.CP(rc_gclk_7512));
   SDFQND1 \D0_reg[6]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(n_361), 
	.D(n_408), 
	.CP(rc_gclk_7512));
   SDFD4 \D1_reg[0]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(n_366), 
	.D(n_404), 
	.CP(rc_gclk_7516));
   SDFD4 \D1_reg[1]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(n_364), 
	.D(n_405), 
	.CP(rc_gclk_7516));
   SDFD4 \D1_reg[4]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(n_362), 
	.D(n_407), 
	.CP(rc_gclk_7516));
   SDFQND1 \D1_reg[6]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(n_360), 
	.D(n_408), 
	.CP(rc_gclk_7516));
   SDFD4 \RLO_reg[0]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(RLO[0]), 
	.D(n_404), 
	.CP(rc_gclk_7492));
   SDFD4 \RLO_reg[1]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(RLO[1]), 
	.D(n_405), 
	.CP(rc_gclk_7492));
   SDFD4 \RLO_reg[2]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(RLO[2]), 
	.D(n_370), 
	.CP(rc_gclk_7492));
   SDFD1 \RLO_reg[3]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(RLO[3]), 
	.D(n_406), 
	.CP(rc_gclk_7492));
   SDFNSND4 \x_reg[0]  (.SI(x_min[0]), 
	.SE(inc_y), 
	.SDN(1'b1), 
	.QN(UNCONNECTED), 
	.Q(x[0]), 
	.D(n_12), 
	.CPN(rc_gclk_7552));
   SDFD1 \xi_ff_reg[2][0]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(\xi_ff[2] [0]), 
	.D(n_441), 
	.CP(rc_gclk_7524));
   SDFQND2 \y_max_reg[0]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(n_417), 
	.D(n_471), 
	.CP(rc_gclk_7544));
   SDFQND1 \yi_ff_reg[0][0]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(n_369), 
	.D(n_471), 
	.CP(rc_gclk_7520));
   SDFQND1 \yi_ff_reg[0][1]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(n_359), 
	.D(n_413), 
	.CP(rc_gclk_7520));
   SDFQND1 \yi_ff_reg[0][2]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(\yi_ff[0] [2]), 
	.D(n_414), 
	.CP(rc_gclk_7520));
   SDFQND1 \yi_ff_reg[1][2]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(\yi_ff[1] [2]), 
	.D(n_414), 
	.CP(rc_gclk_7496));
   SDFQND1 \yi_ff_reg[2][0]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(\yi_ff[2] [0]), 
	.D(n_471), 
	.CP(rc_gclk_7524));
   SDFQND1 \yi_ff_reg[2][1]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(\yi_ff[2] [1]), 
	.D(n_413), 
	.CP(rc_gclk_7524));
   SDFQND1 \yi_ff_reg[2][2]  (.SI(1'b0), 
	.SE(1'b0), 
	.QN(\yi_ff[2] [2]), 
	.D(n_414), 
	.CP(rc_gclk_7524));
   INVD1 g3688 (.ZN(n_310), 
	.I(n_402));
   DFQD1 \A_reg[0]  (.Q(n_297), 
	.D(n_404), 
	.CP(rc_gclk_7484));
   DFQD1 \A_reg[1]  (.Q(n_295), 
	.D(n_405), 
	.CP(rc_gclk_7484));
   DFQD1 \A_reg[2]  (.Q(n_303), 
	.D(n_370), 
	.CP(rc_gclk_7484));
   DFQD1 \A_reg[3]  (.Q(n_307), 
	.D(n_406), 
	.CP(rc_gclk_7484));
   DFQD1 \A_reg[4]  (.Q(n_300), 
	.D(n_407), 
	.CP(rc_gclk_7484));
   DFQD1 \A_reg[5]  (.Q(n_301), 
	.D(n_371), 
	.CP(rc_gclk_7484));
   DFQD1 \A_reg[6]  (.Q(n_305), 
	.D(n_408), 
	.CP(rc_gclk_7484));
   DFQD1 \BC_reg[0]  (.Q(n_273), 
	.D(n_351), 
	.CP(rc_gclk_7504));
   DFD1 \BC_reg[1]  (.QN(n_274), 
	.Q(UNCONNECTED0), 
	.D(n_352), 
	.CP(rc_gclk_7504));
   DFQD1 \B_reg[0]  (.Q(n_298), 
	.D(n_404), 
	.CP(rc_gclk_7488));
   DFQD1 \B_reg[1]  (.Q(n_296), 
	.D(n_405), 
	.CP(rc_gclk_7488));
   DFQD1 \B_reg[2]  (.Q(n_304), 
	.D(n_370), 
	.CP(rc_gclk_7488));
   DFQD1 \B_reg[3]  (.Q(n_308), 
	.D(n_406), 
	.CP(rc_gclk_7488));
   DFQD1 \B_reg[4]  (.Q(n_299), 
	.D(n_407), 
	.CP(rc_gclk_7488));
   DFQD1 \B_reg[5]  (.Q(n_302), 
	.D(n_371), 
	.CP(rc_gclk_7488));
   DFQD1 \B_reg[6]  (.Q(n_306), 
	.D(n_408), 
	.CP(rc_gclk_7488));
   DFQD1 \C0_reg[0]  (.Q(n_281), 
	.D(n_404), 
	.CP(rc_gclk_7500));
   DFQD1 \C0_reg[1]  (.Q(n_279), 
	.D(n_405), 
	.CP(rc_gclk_7500));
   DFQD1 \C0_reg[2]  (.Q(n_293), 
	.D(n_370), 
	.CP(rc_gclk_7500));
   DFQD1 \C0_reg[3]  (.Q(n_285), 
	.D(n_406), 
	.CP(rc_gclk_7500));
   DFQD1 \C0_reg[4]  (.Q(n_277), 
	.D(n_407), 
	.CP(rc_gclk_7500));
   DFQD1 \C0_reg[5]  (.Q(n_289), 
	.D(n_371), 
	.CP(rc_gclk_7500));
   DFQD1 \C0_reg[6]  (.Q(n_275), 
	.D(n_408), 
	.CP(rc_gclk_7500));
   DFQD1 \C1_reg[0]  (.Q(n_282), 
	.D(n_404), 
	.CP(rc_gclk_7508));
   DFQD1 \C1_reg[1]  (.Q(n_280), 
	.D(n_405), 
	.CP(rc_gclk_7508));
   DFQD1 \C1_reg[2]  (.Q(n_294), 
	.D(n_370), 
	.CP(rc_gclk_7508));
   DFQD1 \C1_reg[3]  (.Q(n_286), 
	.D(n_406), 
	.CP(rc_gclk_7508));
   DFQD1 \C1_reg[4]  (.Q(n_278), 
	.D(n_407), 
	.CP(rc_gclk_7508));
   DFQD1 \C1_reg[5]  (.Q(n_290), 
	.D(n_371), 
	.CP(rc_gclk_7508));
   DFQD1 \C1_reg[6]  (.Q(n_276), 
	.D(n_408), 
	.CP(rc_gclk_7508));
   DFD1 \D0_reg[2]  (.QN(n_291), 
	.Q(UNCONNECTED1), 
	.D(n_370), 
	.CP(rc_gclk_7512));
   DFD1 \D0_reg[3]  (.QN(n_283), 
	.Q(UNCONNECTED2), 
	.D(n_406), 
	.CP(rc_gclk_7512));
   DFD1 \D0_reg[5]  (.QN(n_287), 
	.Q(UNCONNECTED3), 
	.D(n_371), 
	.CP(rc_gclk_7512));
   DFD1 \D1_reg[2]  (.QN(n_292), 
	.Q(UNCONNECTED4), 
	.D(n_370), 
	.CP(rc_gclk_7516));
   DFD1 \D1_reg[3]  (.QN(n_284), 
	.Q(UNCONNECTED5), 
	.D(n_406), 
	.CP(rc_gclk_7516));
   DFD1 \D1_reg[5]  (.QN(n_288), 
	.Q(UNCONNECTED6), 
	.D(n_371), 
	.CP(rc_gclk_7516));
   DFQD1 busy_reg (.Q(busy), 
	.D(FE_PSN25_FE_OCP_RBN13_n_470), 
	.CP(rc_gclk_7496));
   LHQD1 \mul_op0_reg[0]  (.Q(n_324), 
	.E(n_392), 
	.D(n_227));
   LHQD1 \mul_op0_reg[1]  (.Q(n_323), 
	.E(n_392), 
	.D(n_233));
   LHQD1 \mul_op0_reg[2]  (.Q(n_322), 
	.E(n_392), 
	.D(n_239));
   LHQD1 \mul_op0_reg[3]  (.Q(n_382), 
	.E(n_392), 
	.D(n_245));
   LHQD1 \mul_op0_reg[4]  (.Q(n_321), 
	.E(n_392), 
	.D(n_250));
   LHQD1 \mul_op0_reg[5]  (.Q(n_320), 
	.E(n_392), 
	.D(n_254));
   LHQD1 \mul_op0_reg[6]  (.Q(n_381), 
	.E(n_392), 
	.D(n_257));
   LHQD1 \mul_op1_reg[0]  (.Q(n_380), 
	.E(n_392), 
	.D(n_229));
   LHQD1 \mul_op1_reg[1]  (.Q(n_379), 
	.E(n_392), 
	.D(n_235));
   LHQD1 \mul_op1_reg[2]  (.Q(n_319), 
	.E(n_392), 
	.D(n_241));
   LHQD1 \mul_op1_reg[3]  (.Q(n_318), 
	.E(n_392), 
	.D(n_249));
   LHQD1 \mul_op1_reg[4]  (.Q(n_378), 
	.E(n_392), 
	.D(n_253));
   LHQD1 \mul_op1_reg[5]  (.Q(n_317), 
	.E(n_392), 
	.D(n_256));
   LHQD1 \mul_op1_reg[6]  (.Q(n_377), 
	.E(n_392), 
	.D(n_259));
   LHQD1 \sub_ans_reg[0]  (.Q(n_272), 
	.E(sub_en), 
	.D(n_224));
   LHQD1 \sub_ans_reg[1]  (.Q(n_271), 
	.E(sub_en), 
	.D(n_226));
   LHQD1 \sub_ans_reg[2]  (.Q(n_270), 
	.E(sub_en), 
	.D(n_232));
   LHQD1 \sub_ans_reg[3]  (.Q(n_269), 
	.E(sub_en), 
	.D(n_238));
   LHQD1 \sub_ans_reg[4]  (.Q(n_268), 
	.E(sub_en), 
	.D(n_244));
   LHQD1 \sub_ans_reg[5]  (.Q(n_267), 
	.E(sub_en), 
	.D(n_248));
   LHQD1 \sub_ans_reg[6]  (.Q(n_266), 
	.E(sub_en), 
	.D(n_252));
   LHQD1 sub_en_reg (.Q(sub_en), 
	.E(n_215), 
	.D(n_197));
   LND1 \sub_op0_reg[0]  (.QN(n_265), 
	.Q(UNCONNECTED7), 
	.EN(n_208), 
	.D(n_210));
   LND1 \sub_op0_reg[2]  (.QN(n_309), 
	.Q(UNCONNECTED8), 
	.EN(n_208), 
	.D(n_211));
   LND1 \sub_op0_reg[3]  (.QN(n_260), 
	.Q(UNCONNECTED9), 
	.EN(n_208), 
	.D(n_185));
   LNQD1 \sub_op0_reg[4]  (.Q(n_261), 
	.EN(n_208), 
	.D(n_184));
   LNQD1 \sub_op0_reg[5]  (.Q(sub_op0[5]), 
	.EN(n_208), 
	.D(n_189));
   LNQD1 \sub_op0_reg[6]  (.Q(sub_op0[6]), 
	.EN(n_208), 
	.D(n_186));
   LHQD1 \sub_op1_reg[0]  (.Q(sub_op1[0]), 
	.E(n_432), 
	.D(n_221));
   LHQD1 \sub_op1_reg[1]  (.Q(n_264), 
	.E(n_432), 
	.D(n_220));
   LNQD1 \sub_op1_reg[3]  (.Q(n_263), 
	.EN(n_208), 
	.D(n_183));
   LNQD1 \sub_op1_reg[4]  (.Q(n_262), 
	.EN(n_208), 
	.D(n_188));
   LND1 \sub_op1_reg[5]  (.QN(sub_op1[5]), 
	.Q(UNCONNECTED10), 
	.EN(n_208), 
	.D(n_182));
   LNQD1 \sub_op1_reg[6]  (.Q(sub_op1[6]), 
	.EN(n_208), 
	.D(n_181));
   DFQD4 \x_max_reg[1]  (.Q(x_max[1]), 
	.D(n_410), 
	.CP(rc_gclk_7536));
   DFQD4 \x_max_reg[2]  (.Q(x_max[2]), 
	.D(n_411), 
	.CP(rc_gclk_7536));
   DFQD4 \x_min_reg[0]  (.Q(x_min[0]), 
	.D(n_175), 
	.CP(rc_gclk_7540));
   DFQD4 \x_min_reg[1]  (.Q(x_min[1]), 
	.D(n_173), 
	.CP(rc_gclk_7540));
   DFQD4 \x_min_reg[2]  (.Q(x_min[2]), 
	.D(n_170), 
	.CP(rc_gclk_7540));
   DFQD4 \xi_ff_reg[0][0]  (.Q(\xi_ff[0] [0]), 
	.D(n_441), 
	.CP(rc_gclk_7520));
   DFQD4 \xi_ff_reg[0][1]  (.Q(\xi_ff[0] [1]), 
	.D(n_410), 
	.CP(rc_gclk_7520));
   DFQD1 \xi_ff_reg[1][0]  (.Q(\xi_ff[1] [0]), 
	.D(n_441), 
	.CP(rc_gclk_7496));
   DFQD4 \xi_ff_reg[1][2]  (.Q(\xi_ff[1] [2]), 
	.D(n_411), 
	.CP(rc_gclk_7496));
   DFQD1 \xi_ff_reg[2][1]  (.Q(\xi_ff[2] [1]), 
	.D(n_410), 
	.CP(rc_gclk_7524));
   DFKCNQD1 \xo_reg[0]  (.Q(xo[0]), 
	.D(FE_OCPN0_x_0_), 
	.CP(rc_gclk_7528), 
	.CN(n_472));
   DFKCNQD1 \xo_reg[1]  (.Q(xo[1]), 
	.D(x[1]), 
	.CP(rc_gclk_7528), 
	.CN(FE_OCP_RBN13_n_470));
   DFKCNQD1 \xo_reg[2]  (.Q(xo[2]), 
	.D(x[2]), 
	.CP(rc_gclk_7528), 
	.CN(n_472));
   DFQD4 \y_max_reg[1]  (.Q(y_max[1]), 
	.D(n_413), 
	.CP(rc_gclk_7544));
   DFQD1 \y_max_reg[2]  (.Q(y_max[2]), 
	.D(n_414), 
	.CP(rc_gclk_7544));
   DFQD4 \y_min_reg[0]  (.Q(y_min[0]), 
	.D(n_172), 
	.CP(rc_gclk_7548));
   DFQD4 \y_min_reg[1]  (.Q(y_min[1]), 
	.D(n_171), 
	.CP(rc_gclk_7548));
   DFQD1 \y_min_reg[2]  (.Q(y_min[2]), 
	.D(n_174), 
	.CP(rc_gclk_7548));
   DFQD4 \yi_ff_reg[1][0]  (.Q(n_430), 
	.D(n_471), 
	.CP(rc_gclk_7496));
   DFKCNQD1 \yo_reg[0]  (.Q(yo[0]), 
	.D(y[0]), 
	.CP(rc_gclk_7528), 
	.CN(FE_OCP_RBN13_n_470));
   DFKCNQD1 \yo_reg[1]  (.Q(yo[1]), 
	.D(y[1]), 
	.CP(rc_gclk_7528), 
	.CN(FE_OCP_RBN13_n_470));
   DFKCNQD1 \yo_reg[2]  (.Q(yo[2]), 
	.D(y[2]), 
	.CP(rc_gclk_7528), 
	.CN(FE_OCP_RBN13_n_470));
   OAI221D0 g5879 (.ZN(n_259), 
	.C(n_258), 
	.B2(n_180), 
	.B1(n_360), 
	.A2(n_361), 
	.A1(n_179));
   AOI22D0 g5881 (.ZN(n_258), 
	.B2(n_276), 
	.B1(n_191), 
	.A2(n_275), 
	.A1(n_190));
   AO22D0 g5882 (.Z(n_257), 
	.B2(n_165), 
	.B1(n_305), 
	.A2(n_306), 
	.A1(n_168));
   AO221D0 g5884 (.Z(n_256), 
	.C(n_255), 
	.B2(n_290), 
	.B1(n_191), 
	.A2(n_289), 
	.A1(n_190));
   OAI22D0 g5886 (.ZN(n_255), 
	.B2(n_288), 
	.B1(n_180), 
	.A2(n_287), 
	.A1(n_179));
   AO22D0 g5887 (.Z(n_254), 
	.B2(n_165), 
	.B1(n_301), 
	.A2(n_302), 
	.A1(n_168));
   AN2XD1 g5892 (.Z(n_408), 
	.A2(n_472), 
	.A1(n_266));
   OAI221D0 g5894 (.ZN(n_253), 
	.C(n_251), 
	.B2(n_180), 
	.B1(n_362), 
	.A2(n_363), 
	.A1(n_179));
   XNR3D0 g5903 (.ZN(n_252), 
	.A3(n_247), 
	.A2(sub_op1[6]), 
	.A1(sub_op0[6]));
   AOI22D0 g5904 (.ZN(n_251), 
	.B2(n_278), 
	.B1(n_191), 
	.A2(n_277), 
	.A1(n_190));
   AO22D0 g5905 (.Z(n_250), 
	.B2(n_165), 
	.B1(n_300), 
	.A2(n_299), 
	.A1(n_168));
   AN2D2 g5906 (.Z(n_371), 
	.A2(FE_OCP_RBN13_n_470), 
	.A1(n_267));
   AO221D0 g5909 (.Z(n_249), 
	.C(n_246), 
	.B2(n_286), 
	.B1(n_191), 
	.A2(n_285), 
	.A1(n_190));
   FA1D0 g5915 (.S(n_248), 
	.CO(n_247), 
	.CI(n_242), 
	.B(sub_op0[5]), 
	.A(sub_op1[5]));
   OAI22D0 g5916 (.ZN(n_246), 
	.B2(n_284), 
	.B1(n_180), 
	.A2(n_283), 
	.A1(n_179));
   AO22D0 g5917 (.Z(n_245), 
	.B2(n_165), 
	.B1(n_307), 
	.A2(n_308), 
	.A1(n_168));
   AN2XD1 g5918 (.Z(n_407), 
	.A2(n_472), 
	.A1(n_268));
   CKND0 g5926 (.ZN(n_244), 
	.I(n_243));
   XNR3D0 g5927 (.ZN(n_243), 
	.A3(n_237), 
	.A2(n_261), 
	.A1(n_262));
   MAOI222D0 g5928 (.ZN(n_242), 
	.C(n_212), 
	.B(n_262), 
	.A(n_237));
   AN2XD1 g5929 (.Z(n_406), 
	.A2(n_472), 
	.A1(n_269));
   AO221D0 g5931 (.Z(n_241), 
	.C(n_240), 
	.B2(n_294), 
	.B1(n_191), 
	.A2(n_293), 
	.A1(n_190));
   OAI22D0 g5934 (.ZN(n_240), 
	.B2(n_292), 
	.B1(n_180), 
	.A2(n_291), 
	.A1(n_179));
   AO22D0 g5935 (.Z(n_239), 
	.B2(n_165), 
	.B1(n_303), 
	.A2(n_304), 
	.A1(n_168));
   CKND0 g5936 (.ZN(n_238), 
	.I(n_236));
   FA1D0 g5937 (.S(n_236), 
	.CO(n_237), 
	.CI(n_230), 
	.B(n_260), 
	.A(n_263));
   AN2XD1 g5944 (.Z(n_370), 
	.A2(n_472), 
	.A1(n_270));
   OAI221D0 g5946 (.ZN(n_235), 
	.C(n_234), 
	.B2(n_180), 
	.B1(n_364), 
	.A2(n_365), 
	.A1(n_179));
   AOI22D0 g5949 (.ZN(n_234), 
	.B2(n_280), 
	.B1(n_191), 
	.A2(n_279), 
	.A1(n_190));
   AO22D0 g5950 (.Z(n_233), 
	.B2(n_165), 
	.B1(n_295), 
	.A2(n_296), 
	.A1(n_168));
   CKND0 g5951 (.ZN(n_232), 
	.I(n_231));
   FA1D0 g5952 (.S(n_231), 
	.CO(n_230), 
	.CI(n_225), 
	.B(n_309), 
	.A(n_316));
   OAI221D0 g5954 (.ZN(n_229), 
	.C(n_228), 
	.B2(n_180), 
	.B1(n_366), 
	.A2(n_367), 
	.A1(n_179));
   AOI22D0 g5960 (.ZN(n_228), 
	.B2(n_282), 
	.B1(n_191), 
	.A2(n_281), 
	.A1(n_190));
   AO22D0 g5961 (.Z(n_227), 
	.B2(n_165), 
	.B1(n_297), 
	.A2(n_298), 
	.A1(n_168));
   CKAN2D2 g5962 (.Z(n_405), 
	.A2(n_472), 
	.A1(n_271));
   XNR3D0 g5968 (.ZN(n_226), 
	.A3(n_223), 
	.A2(n_264), 
	.A1(n_434));
   MAOI222D0 g5969 (.ZN(n_225), 
	.C(n_222), 
	.B(n_434), 
	.A(n_223));
   AN2XD1 g5970 (.Z(n_404), 
	.A2(n_472), 
	.A1(n_272));
   OAI21D0 g5972 (.ZN(n_224), 
	.B(n_223), 
	.A2(n_265), 
	.A1(sub_op1[0]));
   IOA21D1 g5973 (.ZN(n_375), 
	.B(FE_OCP_RBN13_n_470), 
	.A2(n_219), 
	.A1(n_535));
   OAI21D1 g5974 (.ZN(n_374), 
	.B(FE_OCP_RBN13_n_470), 
	.A2(n_218), 
	.A1(n_160));
   OAI21D2 g5975 (.ZN(n_372), 
	.B(FE_OCP_RBN13_n_470), 
	.A2(n_545), 
	.A1(n_160));
   CKND2D0 g5977 (.ZN(n_223), 
	.A2(n_265), 
	.A1(sub_op1[0]));
   CKND0 g5978 (.ZN(n_222), 
	.I(n_264));
   OAI221D0 g5981 (.ZN(n_221), 
	.C(n_213), 
	.B2(n_196), 
	.B1(\xi_ff[2] [0]), 
	.A2(n_369), 
	.A1(n_312));
   OAI221D0 g5982 (.ZN(n_220), 
	.C(n_214), 
	.B2(FE_OCPN1_n_418), 
	.B1(n_274), 
	.A2(n_359), 
	.A1(n_312));
   OAI22D1 g5983 (.ZN(n_219), 
	.B2(n_537), 
	.B1(x_max[2]), 
	.A2(n_194), 
	.A1(n_206));
   MAOI22D1 g5984 (.ZN(n_218), 
	.B2(n_143), 
	.B1(y_max[2]), 
	.A2(n_192), 
	.A1(n_205));
   CKND2D0 g5988 (.ZN(n_215), 
	.A2(n_208), 
	.A1(n_197));
   AOI21D0 g5989 (.ZN(n_214), 
	.B(n_209), 
	.A2(\xi_ff[2] [1]), 
	.A1(n_314));
   OA21D0 g5990 (.Z(n_213), 
	.B(n_207), 
	.A2(\yi_ff[2] [0]), 
	.A1(n_313));
   CKND0 g5996 (.ZN(n_212), 
	.I(n_261));
   OAI211D0 g6002 (.ZN(n_211), 
	.C(n_177), 
	.B(n_202), 
	.A2(n_347), 
	.A1(\yi_ff[1] [2]));
   AO221D0 g6003 (.Z(n_210), 
	.C(n_201), 
	.B2(n_332), 
	.B1(n_162), 
	.A2(\xi_ff[1] [0]), 
	.A1(n_529));
   OAI21D0 g6004 (.ZN(n_209), 
	.B(n_200), 
	.A2(n_313), 
	.A1(\yi_ff[2] [1]));
   CKND0 g6005 (.ZN(n_208), 
	.I(n_432));
   IND4D0 g6006 (.ZN(n_432), 
	.B3(n_349), 
	.B2(n_347), 
	.B1(FE_OCPN1_n_418), 
	.A1(n_529));
   AOI22D0 g6007 (.ZN(n_207), 
	.B2(n_273), 
	.B1(n_162), 
	.A2(\xi_ff[0] [0]), 
	.A1(n_195));
   MAOI222D1 g6009 (.ZN(n_205), 
	.C(n_152), 
	.B(n_541), 
	.A(y_max[1]));
   AOI221D0 g6012 (.ZN(n_202), 
	.C(n_187), 
	.B2(\xi_ff[1] [2]), 
	.B1(n_529), 
	.A2(y[2]), 
	.A1(n_161));
   AO222D0 g6013 (.Z(n_201), 
	.C2(y[0]), 
	.C1(n_161), 
	.B2(FE_OCPN0_x_0_), 
	.B1(n_164), 
	.A2(n_430), 
	.A1(n_178));
   CKND2D0 g6014 (.ZN(n_200), 
	.A2(n_195), 
	.A1(\xi_ff[0] [1]));
   NR2D0 g6017 (.ZN(n_197), 
	.A2(n_165), 
	.A1(n_416));
   OA21D0 g6018 (.Z(n_313), 
	.B(FE_PSN28_n_598), 
	.A2(n_151), 
	.A1(n_400));
   CKND0 g6019 (.ZN(n_196), 
	.I(n_314));
   OAI21D0 g6020 (.ZN(n_314), 
	.B(n_463), 
	.A2(n_398), 
	.A1(n_151));
   AOI21D0 g6021 (.ZN(n_312), 
	.B(n_167), 
	.A2(n_151), 
	.A1(n_161));
   CKND0 g6023 (.ZN(n_195), 
	.I(n_530));
   AN2XD1 g6026 (.Z(n_194), 
	.A2(n_537), 
	.A1(x_max[2]));
   ND2D1 g6027 (.ZN(n_193), 
	.A2(n_144), 
	.A1(x_max[1]));
   CKND2D1 g6028 (.ZN(n_192), 
	.A2(n_143), 
	.A1(y_max[2]));
   NR2D0 g6031 (.ZN(n_191), 
	.A2(n_151), 
	.A1(FE_OCPN2_n_169));
   NR2D0 g6032 (.ZN(n_190), 
	.A2(top_line), 
	.A1(FE_OCPN2_n_169));
   CKND2D0 g6033 (.ZN(n_416), 
	.A2(FE_OCPN2_n_169), 
	.A1(n_402));
   CKND2D0 g6034 (.ZN(n_392), 
	.A2(FE_OCPN2_n_169), 
	.A1(n_422));
   NR2D0 g6035 (.ZN(n_189), 
	.A2(AD[5]), 
	.A1(FE_OCPN1_n_418));
   NR2D0 g6036 (.ZN(n_188), 
	.A2(BC[4]), 
	.A1(FE_OCPN1_n_418));
   NR2D0 g6037 (.ZN(n_187), 
	.A2(n_368), 
	.A1(FE_OCPN1_n_418));
   NR2D0 g6038 (.ZN(n_186), 
	.A2(AD[6]), 
	.A1(FE_OCPN1_n_418));
   NR2D0 g6039 (.ZN(n_185), 
	.A2(AD[3]), 
	.A1(FE_OCPN1_n_418));
   NR2D0 g6040 (.ZN(n_184), 
	.A2(AD[4]), 
	.A1(FE_OCPN1_n_418));
   NR2D0 g6041 (.ZN(n_183), 
	.A2(BC[3]), 
	.A1(FE_OCPN1_n_418));
   NR2D0 g6042 (.ZN(n_182), 
	.A2(BC[5]), 
	.A1(FE_OCPN1_n_418));
   NR2D0 g6043 (.ZN(n_181), 
	.A2(BC[6]), 
	.A1(FE_OCPN1_n_418));
   CKND2D0 g6044 (.ZN(n_180), 
	.A2(n_165), 
	.A1(top_line));
   CKND2D0 g6045 (.ZN(n_179), 
	.A2(n_165), 
	.A1(n_151));
   CKND0 g6046 (.ZN(n_347), 
	.I(n_178));
   IND2D0 g6047 (.ZN(n_178), 
	.B1(FE_PSN28_n_598), 
	.A1(n_167));
   ND2D2 g6048 (.ZN(n_343), 
	.A2(FE_OCP_RBN13_n_470), 
	.A1(n_598));
   CKND2D0 g6049 (.ZN(n_341), 
	.A2(FE_OCP_RBN13_n_470), 
	.A1(n_398));
   NR2XD3 g6050 (.ZN(n_349), 
	.A2(n_161), 
	.A1(n_164));
   CKND2D0 g6051 (.ZN(n_177), 
	.A2(n_164), 
	.A1(x[2]));
   ND2D2 g6052 (.ZN(n_342), 
	.A2(FE_OCP_RBN13_n_470), 
	.A1(n_492));
   CKND2D1 g6053 (.ZN(n_336), 
	.A2(FE_OCP_RBN13_n_470), 
	.A1(n_402));
   CKND2D2 g6054 (.ZN(n_340), 
	.A2(FE_OCP_RBN13_n_470), 
	.A1(n_169));
   CKND2D0 g6055 (.ZN(n_345), 
	.A2(FE_OCP_RBN13_n_470), 
	.A1(n_400));
   CKND2D3 g6057 (.ZN(n_344), 
	.A2(n_463), 
	.A1(FE_OCP_RBN13_n_470));
   CKND2D0 g6058 (.ZN(n_339), 
	.A2(FE_OCP_RBN13_n_470), 
	.A1(n_422));
   CKND2D0 g6060 (.ZN(n_335), 
	.A2(n_418), 
	.A1(FE_OCP_RBN13_n_470));
   CKAN2D1 g6092 (.Z(n_351), 
	.A2(FE_OCP_RBN13_n_470), 
	.A1(n_331));
   CKAN2D1 g6093 (.Z(n_352), 
	.A2(FE_OCP_RBN13_n_470), 
	.A1(n_330));
   IND2D0 g6094 (.ZN(n_175), 
	.B1(FE_OCP_RBN13_n_470), 
	.A1(xi[0]));
   CKND2D0 g6095 (.ZN(n_174), 
	.A2(n_143), 
	.A1(FE_OCP_RBN13_n_470));
   NR2XD0 g6096 (.ZN(n_411), 
	.A2(n_537), 
	.A1(n_470));
   NR2XD0 g6097 (.ZN(n_410), 
	.A2(n_144), 
	.A1(n_470));
   CKND2D0 g6098 (.ZN(n_173), 
	.A2(n_144), 
	.A1(FE_OCP_RBN13_n_470));
   CKND2D0 g6099 (.ZN(n_172), 
	.A2(n_146), 
	.A1(FE_OCP_RBN13_n_470));
   CKND2D0 g6100 (.ZN(n_171), 
	.A2(n_541), 
	.A1(FE_OCP_RBN13_n_470));
   CKND2D0 g6101 (.ZN(n_170), 
	.A2(n_537), 
	.A1(FE_OCP_RBN13_n_470));
   CKND0 g6102 (.ZN(n_168), 
	.I(FE_OCPN2_n_169));
   CKND2D2 g6103 (.ZN(n_169), 
	.A2(n_155), 
	.A1(n_491));
   CKND0 g6105 (.ZN(n_167), 
	.I(n_492));
   CKND0 g6108 (.ZN(n_165), 
	.I(n_422));
   INVD2 g6110 (.ZN(n_164), 
	.I(n_398));
   CKND2D1 g6111 (.ZN(n_398), 
	.A2(n_155), 
	.A1(n_597));
   AN2XD1 g6113 (.Z(n_358), 
	.A2(FE_PSN25_FE_OCP_RBN13_n_470), 
	.A1(n_325));
   AN2XD1 g6114 (.Z(n_354), 
	.A2(FE_PSN25_FE_OCP_RBN13_n_470), 
	.A1(n_328));
   AN2XD1 g6115 (.Z(n_356), 
	.A2(FE_PSN25_FE_OCP_RBN13_n_470), 
	.A1(n_327));
   AN2XD1 g6116 (.Z(n_353), 
	.A2(FE_OCP_RBN13_n_470), 
	.A1(n_329));
   AN2XD1 g6117 (.Z(n_355), 
	.A2(FE_PSN25_FE_OCP_RBN13_n_470), 
	.A1(n_326));
   CKND0 g6119 (.ZN(n_162), 
	.I(FE_OCPN1_n_418));
   CKND2D1 g6120 (.ZN(n_418), 
	.A2(n_155), 
	.A1(n_524));
   INVD1 g6121 (.ZN(n_161), 
	.I(n_400));
   CKND2D4 g6122 (.ZN(n_400), 
	.A2(n_524), 
	.A1(n_502));
   INVD2 g6123 (.ZN(n_160), 
	.I(n_535));
   NR2XD0 g6125 (.ZN(n_413), 
	.A2(n_541), 
	.A1(FE_PSN26_n_470));
   NR2XD0 g6128 (.ZN(n_414), 
	.A2(n_143), 
	.A1(FE_PSN26_n_470));
   OR2D0 g6130 (.Z(n_333), 
	.A2(inc_x), 
	.A1(inc_y));
   NR2XD1 g6133 (.ZN(n_157), 
	.A2(control[1]), 
	.A1(control[3]));
   NR2XD2 g6137 (.ZN(n_155), 
	.A2(control[2]), 
	.A1(FE_OCP_RBN22_control_3_));
   ND2D2 g6159 (.ZN(n_152), 
	.A2(yi[0]), 
	.A1(n_417));
   CKND0 g6160 (.ZN(n_151), 
	.I(top_line));
   INVD6 g6162 (.ZN(n_149), 
	.I(control[2]));
   CKND1 g6166 (.ZN(n_146), 
	.I(yi[0]));
   CKND1 g6168 (.ZN(n_144), 
	.I(xi[1]));
   INVD1 g6169 (.ZN(n_143), 
	.I(yi[2]));
   DFD2 \x_max_reg[0]  (.QN(n_137), 
	.Q(x_max[0]), 
	.D(n_441), 
	.CP(rc_gclk_7536));
   IND2D2 g6185 (.ZN(n_138), 
	.B1(xi[1]), 
	.A1(x_min[1]));
   DFQD1 \AD_reg[0]  (.Q(n_332), 
	.D(n_351), 
	.CP(rc_gclk));
   DFD1 \AD_reg[1]  (.QN(n_133), 
	.Q(UNCONNECTED11), 
	.D(n_352), 
	.CP(rc_gclk));
   DFD1 \BC_reg[2]  (.QN(n_134), 
	.Q(UNCONNECTED12), 
	.D(n_353), 
	.CP(rc_gclk_7504));
   DFD1 \RLO_reg[4]  (.QN(n_132), 
	.Q(UNCONNECTED13), 
	.D(n_407), 
	.CP(rc_gclk_7492));
   DFQD1 \RLO_reg[5]  (.Q(n_131), 
	.D(n_371), 
	.CP(rc_gclk_7492));
   DFQD1 \RLO_reg[6]  (.Q(RLO[6]), 
	.D(n_408), 
	.CP(rc_gclk_7492));
   DFQD1 check_reg (.Q(check), 
	.D(n_81), 
	.CP(clk__L6_N1));
   DFQD4 \control_reg[1]  (.Q(control[1]), 
	.D(n_468), 
	.CP(rc_gclk_7532));
   DFQD4 \control_reg[2]  (.Q(control[2]), 
	.D(n_601), 
	.CP(rc_gclk_7532));
   DFQD4 \control_reg[3]  (.Q(control[3]), 
	.D(n_103), 
	.CP(rc_gclk_7532));
   DFQD1 good_reg (.Q(good), 
	.D(n_121), 
	.CP(check));
   DFQD1 inc_x_reg (.Q(inc_x), 
	.D(n_483), 
	.CP(clk__L6_N0));
   LHQD1 \mul_ans_reg[0]  (.Q(n_331), 
	.E(mul_en), 
	.D(n_384));
   LHQD1 \mul_ans_reg[1]  (.Q(n_330), 
	.E(mul_en), 
	.D(n_385));
   LHQD1 \mul_ans_reg[2]  (.Q(n_329), 
	.E(mul_en), 
	.D(n_386));
   LHQD1 \mul_ans_reg[3]  (.Q(n_328), 
	.E(mul_en), 
	.D(n_387));
   LHQD1 \mul_ans_reg[4]  (.Q(n_327), 
	.E(mul_en), 
	.D(n_388));
   LHQD1 \mul_ans_reg[5]  (.Q(n_326), 
	.E(mul_en), 
	.D(n_389));
   LHQD1 \mul_ans_reg[6]  (.Q(n_325), 
	.E(mul_en), 
	.D(n_390));
   LHQD1 mul_en_reg (.Q(mul_en), 
	.E(n_80), 
	.D(n_392));
   DFNSND2 po__reg (.SDN(1'b1), 
	.QN(UNCONNECTED14), 
	.Q(n_136), 
	.D(n_130), 
	.CPN(clk__L6_N0));
   DFNSND2 po_reg (.SDN(1'b1), 
	.QN(UNCONNECTED15), 
	.Q(po), 
	.D(n_127), 
	.CPN(clk__L6_N0));
   LHQD1 \sub_op0_reg[1]  (.Q(n_434), 
	.E(n_432), 
	.D(n_99));
   LHQD1 \sub_op1_reg[2]  (.Q(n_316), 
	.E(n_432), 
	.D(n_91));
   DFQD1 top_line_reg (.Q(top_line), 
	.D(n_518), 
	.CP(clk__L6_N1));
   SDFNSND4 \x_reg[1]  (.SI(x_min[1]), 
	.SE(inc_y), 
	.SDN(1'b1), 
	.QN(UNCONNECTED16), 
	.Q(x[1]), 
	.D(n_58), 
	.CPN(rc_gclk_7552));
   DFNSND4 \x_reg[2]  (.SDN(1'b1), 
	.QN(n_15), 
	.Q(x[2]), 
	.D(n_108), 
	.CPN(rc_gclk_7552));
   DFQD4 \xi_ff_reg[1][1]  (.Q(\xi_ff[1] [1]), 
	.D(n_410), 
	.CP(rc_gclk_7496));
   DFQD1 \xi_ff_reg[2][2]  (.Q(\xi_ff[2] [2]), 
	.D(n_411), 
	.CP(rc_gclk_7524));
   DFNSND2 \y_reg[0]  (.SDN(1'b1), 
	.QN(n_16), 
	.Q(y[0]), 
	.D(n_599), 
	.CPN(rc_gclk_7558));
   DFNSND2 \y_reg[1]  (.SDN(1'b1), 
	.QN(n_13), 
	.Q(y[1]), 
	.D(n_98), 
	.CPN(rc_gclk_7558));
   DFNSND2 \y_reg[2]  (.SDN(1'b1), 
	.QN(UNCONNECTED17), 
	.Q(y[2]), 
	.D(n_516), 
	.CPN(rc_gclk_7558));
   DFQD4 \yi_ff_reg[1][1]  (.Q(n_135), 
	.D(n_413), 
	.CP(rc_gclk_7496));
   CKND2D0 g7156 (.ZN(n_130), 
	.A2(n_124), 
	.A1(n_125));
   IOA21D1 g7161 (.ZN(n_127), 
	.B(n_125), 
	.A2(n_122), 
	.A1(po));
   OR2XD1 g7163 (.Z(n_125), 
	.A2(n_122), 
	.A1(po));
   CKND2D0 g7164 (.ZN(n_124), 
	.A2(n_123), 
	.A1(n_136));
   IND2D0 g7165 (.ZN(n_123), 
	.B1(check), 
	.A1(good));
   ND2D1 g7166 (.ZN(n_122), 
	.A2(good), 
	.A1(check));
   OAI31D0 g7168 (.ZN(n_121), 
	.B(n_120), 
	.A3(n_22), 
	.A2(n_65), 
	.A1(RLO[6]));
   AOI211D0 g7169 (.ZN(n_120), 
	.C(n_110), 
	.B(n_119), 
	.A2(n_69), 
	.A1(n_519));
   OAI32D0 g7170 (.ZN(n_119), 
	.B2(n_44), 
	.B1(n_102), 
	.A3(n_118), 
	.A2(n_440), 
	.A1(n_40));
   OAI211D0 g7171 (.ZN(n_118), 
	.C(n_28), 
	.B(n_117), 
	.A2(n_14), 
	.A1(\xi_ff[1] [1]));
   AOI211D0 g7173 (.ZN(n_117), 
	.C(n_46), 
	.B(n_112), 
	.A2(\xi_ff[1] [1]), 
	.A1(n_14));
   AN3XD1 g7179 (.Z(n_113), 
	.A3(n_458), 
	.A2(n_100), 
	.A1(n_101));
   OAI221D0 g7180 (.ZN(n_112), 
	.C(n_109), 
	.B2(n_15), 
	.B1(\xi_ff[1] [2]), 
	.A2(y[0]), 
	.A1(n_67));
   OAI32D0 g7184 (.ZN(n_110), 
	.B2(n_69), 
	.B1(n_519), 
	.A3(n_56), 
	.A2(n_52), 
	.A1(n_72));
   AOI22D0 g7185 (.ZN(n_109), 
	.B2(\xi_ff[1] [2]), 
	.B1(n_15), 
	.A2(y[0]), 
	.A1(n_94));
   MUX3D0 g7186 (.Z(n_108), 
	.S1(inc_y), 
	.S0(n_25), 
	.I2(x_min[2]), 
	.I1(x[2]), 
	.I0(n_15));
   MOAI22D1 g7194 (.ZN(n_103), 
	.B2(n_76), 
	.B1(n_85), 
	.A2(n_88), 
	.A1(n_78));
   ND4D0 g7195 (.ZN(n_102), 
	.A4(n_55), 
	.A3(n_57), 
	.A2(n_71), 
	.A1(n_86));
   ND2D1 g7196 (.ZN(n_101), 
	.A2(n_84), 
	.A1(n_519));
   OAI22D2 g7197 (.ZN(n_100), 
	.B2(y_max[2]), 
	.B1(n_7), 
	.A2(n_24), 
	.A1(n_485));
   AO221D0 g7202 (.Z(n_99), 
	.C(n_90), 
	.B2(x[1]), 
	.B1(n_164), 
	.A2(\xi_ff[1] [1]), 
	.A1(n_529));
   CKMUX2D1 g7203 (.Z(n_98), 
	.S(FE_PSN24_n_598), 
	.I1(n_54), 
	.I0(y_min[1]));
   OAI21D1 g7204 (.ZN(n_97), 
	.B(n_78), 
	.A2(n_75), 
	.A1(control[0]));
   IOA21D0 g7207 (.ZN(n_94), 
	.B(n_430), 
	.A2(n_135), 
	.A1(n_513));
   OAI21D2 g7209 (.ZN(n_92), 
	.B(n_39), 
	.A2(n_16), 
	.A1(n_66));
   AO211D0 g7211 (.Z(n_91), 
	.C(n_63), 
	.B(n_82), 
	.A2(\xi_ff[2] [2]), 
	.A1(n_314));
   OAI222D0 g7212 (.ZN(n_90), 
	.C2(n_347), 
	.C1(n_19), 
	.B2(FE_OCPN1_n_418), 
	.B1(n_133), 
	.A2(n_13), 
	.A1(n_400));
   NR3D4 g7215 (.ZN(n_88), 
	.A3(n_47), 
	.A2(n_50), 
	.A1(n_48));
   AOI221D0 g7217 (.ZN(n_86), 
	.C(n_73), 
	.B2(\yi_ff[2] [2]), 
	.B1(y[2]), 
	.A2(\xi_ff[2] [0]), 
	.A1(FE_OCPN0_x_0_));
   AO21D0 g7218 (.Z(n_85), 
	.B(control[3]), 
	.A2(control[2]), 
	.A1(n_524));
   ND3D1 g7219 (.ZN(n_84), 
	.A3(n_486), 
	.A2(n_512), 
	.A1(n_43));
   OAI222D0 g7223 (.ZN(n_82), 
	.C2(n_312), 
	.C1(\yi_ff[0] [2]), 
	.B2(n_313), 
	.B1(\yi_ff[2] [2]), 
	.A2(n_134), 
	.A1(FE_OCPN1_n_418));
   NR2XD1 g7224 (.ZN(n_81), 
	.A2(n_464), 
	.A1(n_62));
   IND4D0 g7225 (.ZN(n_80), 
	.B3(n_349), 
	.B2(FE_OCPN1_n_418), 
	.B1(n_422), 
	.A1(n_416));
   INVD1 g7227 (.ZN(n_78), 
	.I(n_77));
   NR2XD0 g7228 (.ZN(n_77), 
	.A2(n_455), 
	.A1(n_491));
   CKND2 g7229 (.ZN(n_76), 
	.I(n_75));
   OAI21D1 g7230 (.ZN(n_75), 
	.B(n_472), 
	.A2(n_491), 
	.A1(n_21));
   NR2XD0 g7231 (.ZN(n_74), 
	.A2(n_442), 
	.A1(n_51));
   OAI22D0 g7232 (.ZN(n_73), 
	.B2(\xi_ff[2] [1]), 
	.B1(n_14), 
	.A2(\xi_ff[2] [2]), 
	.A1(n_15));
   MUX2ND0 g7233 (.ZN(n_72), 
	.S(\xi_ff[0] [2]), 
	.I1(x[2]), 
	.I0(n_15));
   MAOI22D0 g7234 (.ZN(n_71), 
	.B2(\xi_ff[2] [0]), 
	.B1(FE_OCPN0_x_0_), 
	.A2(\xi_ff[2] [2]), 
	.A1(n_15));
   XNR2D0 g7236 (.ZN(n_69), 
	.A2(top_line), 
	.A1(RLO[6]));
   IOA21D2 g7237 (.ZN(n_68), 
	.B(n_38), 
	.A2(n_20), 
	.A1(\xi_ff[1] [2]));
   CKND0 g7238 (.ZN(n_67), 
	.I(n_66));
   OAI21D2 g7239 (.ZN(n_66), 
	.B(n_8), 
	.A2(n_19), 
	.A1(y[1]));
   IND4D0 g7240 (.ZN(n_65), 
	.B3(RLO[3]), 
	.B2(RLO[2]), 
	.B1(n_132), 
	.A1(n_131));
   NR2D0 g7243 (.ZN(n_63), 
	.A2(n_20), 
	.A1(n_530));
   AOI21D4 g7244 (.ZN(n_62), 
	.B(n_310), 
	.A2(check), 
	.A1(n_349));
   OAI22D0 g7249 (.ZN(n_58), 
	.B2(x[0]), 
	.B1(n_14), 
	.A2(n_12), 
	.A1(x[1]));
   MAOI22D0 g7250 (.ZN(n_57), 
	.B2(\yi_ff[2] [2]), 
	.B1(y[2]), 
	.A2(\xi_ff[2] [1]), 
	.A1(n_14));
   MUX2ND0 g7251 (.ZN(n_56), 
	.S(\xi_ff[0] [1]), 
	.I1(x[1]), 
	.I0(n_14));
   MUX2ND0 g7252 (.ZN(n_55), 
	.S(\yi_ff[2] [0]), 
	.I1(y[0]), 
	.I0(n_16));
   MUX2ND0 g7253 (.ZN(n_54), 
	.S(y[1]), 
	.I1(y[0]), 
	.I0(n_16));
   MUX2ND0 g7255 (.ZN(n_52), 
	.S(\xi_ff[0] [0]), 
	.I1(FE_OCPN0_x_0_), 
	.I0(n_12));
   OAI22D1 g7256 (.ZN(n_51), 
	.B2(n_11), 
	.B1(x[1]), 
	.A2(n_9), 
	.A1(x[2]));
   OAI22D2 g7257 (.ZN(n_50), 
	.B2(x_min[2]), 
	.B1(n_15), 
	.A2(x_min[1]), 
	.A1(n_14));
   AOI22D1 g7258 (.ZN(n_49), 
	.B2(n_9), 
	.B1(x[2]), 
	.A2(n_11), 
	.A1(x[1]));
   OAI22D4 g7259 (.ZN(n_48), 
	.B2(n_5), 
	.B1(x[1]), 
	.A2(n_4), 
	.A1(x[2]));
   MOAI22D1 g7260 (.ZN(n_47), 
	.B2(n_6), 
	.B1(x[0]), 
	.A2(n_6), 
	.A1(x[0]));
   MUX2ND0 g7261 (.ZN(n_46), 
	.S(\xi_ff[1] [0]), 
	.I1(FE_OCPN0_x_0_), 
	.I0(n_12));
   ND2D1 g7262 (.ZN(n_45), 
	.A2(y_max[1]), 
	.A1(n_484));
   MUX2ND0 g7263 (.ZN(n_44), 
	.S(\yi_ff[2] [1]), 
	.I1(n_13), 
	.I0(y[1]));
   MUX2ND0 g7265 (.ZN(n_43), 
	.S(xo[1]), 
	.I1(n_11), 
	.I0(x_max[1]));
   CKND0 g7268 (.ZN(n_40), 
	.I(n_39));
   CKND2D1 g7269 (.ZN(n_39), 
	.A2(n_19), 
	.A1(y[1]));
   CKND2D1 g7270 (.ZN(n_38), 
	.A2(\xi_ff[1] [1]), 
	.A1(n_10));
   OR2XD1 g7271 (.Z(n_37), 
	.A2(\xi_ff[1] [2]), 
	.A1(n_20));
   NR2D1 g7272 (.ZN(n_36), 
	.A2(n_10), 
	.A1(\xi_ff[1] [1]));
   CKND2D1 g7274 (.ZN(n_34), 
	.A2(inc_y), 
	.A1(n_400));
   CKND2D1 g7275 (.ZN(n_33), 
	.A2(top_line), 
	.A1(n_535));
   IND2D0 g7276 (.ZN(n_32), 
	.B1(FE_PSN27_n_457), 
	.A1(n_426));
   INR2XD0 g7277 (.ZN(n_31), 
	.B1(n_464), 
	.A1(inc_x));
   CKND2 g7279 (.ZN(n_29), 
	.I(n_28));
   CKND2D2 g7280 (.ZN(n_28), 
	.A2(\yi_ff[1] [2]), 
	.A1(y[2]));
   CKND2D1 g7283 (.ZN(n_25), 
	.A2(x[0]), 
	.A1(x[1]));
   AN2XD1 g7284 (.Z(n_24), 
	.A2(y_max[2]), 
	.A1(n_7));
   CKND2D0 g7287 (.ZN(n_22), 
	.A2(RLO[0]), 
	.A1(RLO[1]));
   CKND2D1 g7288 (.ZN(n_21), 
	.A2(control[2]), 
	.A1(control[3]));
   CKND2 g7297 (.ZN(n_20), 
	.I(\xi_ff[0] [2]));
   CKND2 g7301 (.ZN(n_19), 
	.I(n_135));
   INVD2 g7313 (.ZN(n_14), 
	.I(x[1]));
   INVD3 g7316 (.ZN(n_12), 
	.I(x[0]));
   CKND2 g7317 (.ZN(n_11), 
	.I(x_max[1]));
   CKND2 g7319 (.ZN(n_10), 
	.I(\xi_ff[0] [1]));
   CKND1 g7320 (.ZN(n_9), 
	.I(x_max[2]));
   CKND2 g7322 (.ZN(n_8), 
	.I(n_430));
   CKND2 g7323 (.ZN(n_7), 
	.I(yo[2]));
   INVD1 g7324 (.ZN(n_6), 
	.I(x_min[0]));
   CKND1 g7325 (.ZN(n_5), 
	.I(x_min[1]));
   CKND1 g7326 (.ZN(n_4), 
	.I(x_min[2]));
   IND2D1 g7327 (.ZN(n_559), 
	.B1(n_458), 
	.A1(inc_y));
   NR2D0 g7331 (.ZN(n_560), 
	.A2(n_519), 
	.A1(n_136));
   DFD4 rst_int_reg (.QN(UNCONNECTED18), 
	.Q(rst_int), 
	.D(n_113), 
	.CP(clk__L6_N0));
   OR2XD1 g7337 (.Z(n_439), 
	.A2(\yi_ff[1] [2]), 
	.A1(y[2]));
   NR2D0 g7338 (.ZN(n_440), 
	.A2(\yi_ff[1] [2]), 
	.A1(y[2]));
   AN2XD1 g7340 (.Z(n_441), 
	.A2(xi[0]), 
	.A1(n_472));
   MUX2ND0 g7341 (.ZN(n_442), 
	.S(x_max[0]), 
	.I1(x[0]), 
	.I0(n_12));
   CKND1 g620 (.ZN(n_459), 
	.I(n_458));
   NR2XD1 g621 (.ZN(n_458), 
	.A2(n_455), 
	.A1(FE_PSN27_n_457));
   IND2D2 g625 (.ZN(n_455), 
	.B1(n_472), 
	.A1(n_21));
   INVD2 g627 (.ZN(n_457), 
	.I(n_597));
   MAOI22D1 g616 (.ZN(n_465), 
	.B2(n_464), 
	.B1(n_463), 
	.A2(n_462), 
	.A1(n_460));
   CKND2D2 g626 (.ZN(n_460), 
	.A2(inc_x), 
	.A1(n_164));
   NR2D1 g618 (.ZN(n_462), 
	.A2(n_461), 
	.A1(n_34));
   ND2D1 g623 (.ZN(n_461), 
	.A2(n_472), 
	.A1(n_598));
   CKND2D2 g624 (.ZN(n_463), 
	.A2(n_502), 
	.A1(n_597));
   INVD2 g629 (.ZN(n_464), 
	.I(n_472));
   IOA21D1 g16 (.ZN(n_468), 
	.B(n_467), 
	.A2(n_32), 
	.A1(n_76));
   ND2D1 g17 (.ZN(n_467), 
	.A2(n_77), 
	.A1(n_88));
   NR2XD0 g18 (.ZN(n_471), 
	.A2(n_146), 
	.A1(FE_PSN26_n_470));
   INVD8 g19 (.ZN(n_470), 
	.I(n_469));
   NR2XD2 g21 (.ZN(n_472), 
	.A2(reset), 
	.A1(rst_int));
   OAI21D1 g23 (.ZN(n_483), 
	.B(n_482), 
	.A2(n_560), 
	.A1(n_559));
   CKND2D1 g24 (.ZN(n_482), 
	.A2(n_349), 
	.A1(n_31));
   MAOI22D1 g35 (.ZN(n_485), 
	.B2(y_max[1]), 
	.B1(n_484), 
	.A2(yo[1]), 
	.A1(n_45));
   NR2D1 g36 (.ZN(n_484), 
	.A2(n_417), 
	.A1(yo[0]));
   MOAI22D1 g15 (.ZN(n_486), 
	.B2(x_max[0]), 
	.B1(xo[0]), 
	.A2(xo[0]), 
	.A1(x_max[0]));
   CKND2D2 g14 (.ZN(n_492), 
	.A2(n_502), 
	.A1(n_491));
   MUX2ND0 g7354 (.ZN(n_496), 
	.S(control[2]), 
	.I1(n_524), 
	.I0(n_494));
   NR2XD2 g7358 (.ZN(n_502), 
	.A2(control[3]), 
	.A1(n_149));
   NR2XD1 g50 (.ZN(n_510), 
	.A2(n_509), 
	.A1(n_36));
   CKND2D2 g51 (.ZN(n_509), 
	.A2(\xi_ff[1] [0]), 
	.A1(n_508));
   CKND2 g52 (.ZN(n_508), 
	.I(\xi_ff[0] [0]));
   MOAI22D1 g13 (.ZN(n_512), 
	.B2(x_max[2]), 
	.B1(xo[2]), 
	.A2(x_max[2]), 
	.A1(xo[2]));
   CKMUX2D1 g38 (.Z(n_516), 
	.S(FE_PSN24_n_598), 
	.I1(n_515), 
	.I0(y_min[2]));
   MOAI22D1 g39 (.ZN(n_515), 
	.B2(y[2]), 
	.B1(n_513), 
	.A2(y[2]), 
	.A1(n_513));
   CKND2D2 g40 (.ZN(n_513), 
	.A2(y[0]), 
	.A1(y[1]));
   OAI32D1 g95 (.ZN(n_518), 
	.B2(n_464), 
	.B1(n_33), 
	.A3(n_464), 
	.A2(n_517), 
	.A1(n_535));
   AOI21D2 g96 (.ZN(n_517), 
	.B(n_29), 
	.A2(n_439), 
	.A1(n_92));
   OAI21D1 g126 (.ZN(n_523), 
	.B(n_465), 
	.A2(n_522), 
	.A1(n_459));
   AOI22D2 g127 (.ZN(n_522), 
	.B2(n_49), 
	.B1(n_74), 
	.A2(n_521), 
	.A1(n_520));
   CKND2 g128 (.ZN(n_520), 
	.I(n_519));
   OAI21D4 g129 (.ZN(n_519), 
	.B(n_37), 
	.A2(n_68), 
	.A1(n_510));
   CKND0 g130 (.ZN(n_521), 
	.I(good));
   OR2XD1 g104 (.Z(n_528), 
	.A2(n_470), 
	.A1(n_527));
   NR2D3 g106 (.ZN(n_527), 
	.A2(n_525), 
	.A1(n_494));
   CKND2D4 g109 (.ZN(n_525), 
	.A2(n_149), 
	.A1(FE_OCP_RBN22_control_3_));
   IND2D0 g100 (.ZN(n_529), 
	.B1(n_463), 
	.A1(FE_PSN23_n_527));
   AOI21D0 g99 (.ZN(n_530), 
	.B(FE_PSN23_n_527), 
	.A2(n_151), 
	.A1(n_164));
   AO31D4 g105 (.Z(n_532), 
	.B(n_470), 
	.A3(nt), 
	.A2(n_491), 
	.A1(n_531));
   CKND4 g108 (.ZN(n_531), 
	.I(n_525));
   IND4D1 g102 (.ZN(n_533), 
	.B3(FE_OCP_RBN13_n_470), 
	.B2(n_491), 
	.B1(n_531), 
	.A1(nt));
   IOA21D1 g103 (.ZN(n_534), 
	.B(FE_OCP_RBN13_n_470), 
	.A2(n_426), 
	.A1(n_531));
   IND2D2 g107 (.ZN(n_535), 
	.B1(n_525), 
	.A1(n_157));
   CKND1 g58 (.ZN(n_537), 
	.I(xi[2]));
   OAI21D1 g55 (.ZN(n_540), 
	.B(FE_OCP_RBN13_n_470), 
	.A2(n_539), 
	.A1(n_160));
   MOAI22D2 g56 (.ZN(n_539), 
	.B2(n_538), 
	.B1(n_602), 
	.A2(n_537), 
	.A1(x_min[2]));
   AOI22D2 g57 (.ZN(n_538), 
	.B2(n_144), 
	.B1(x_min[1]), 
	.A2(n_537), 
	.A1(x_min[2]));
   CKND3 g7360 (.ZN(n_541), 
	.I(yi[1]));
   FCICOND1 g7361 (.CON(n_545), 
	.CI(y_min[2]), 
	.B(n_143), 
	.A(n_544));
   ND2D1 g7362 (.ZN(n_544), 
	.A2(n_543), 
	.A1(n_542));
   OAI211D2 g7363 (.ZN(n_542), 
	.C(n_146), 
	.B(y_min[0]), 
	.A2(y_min[1]), 
	.A1(n_541));
   ND2D2 g7364 (.ZN(n_543), 
	.A2(n_541), 
	.A1(y_min[1]));
   DFD2 inc_y_reg (.QN(UNCONNECTED19), 
	.Q(inc_y), 
	.D(n_523), 
	.CP(clk__L6_N1));
   INR2D4 g7408 (.ZN(n_597), 
	.B1(control[1]), 
	.A1(control[0]));
   CKMUX2D1 g7409 (.Z(n_599), 
	.S(FE_PSN24_n_598), 
	.I1(n_16), 
	.I0(y_min[0]));
   ND2D3 g22 (.ZN(n_598), 
	.A2(n_502), 
	.A1(n_426));
   ND2D1 g7410 (.ZN(n_601), 
	.A2(n_600), 
	.A1(n_467));
   CKND2D1 g7411 (.ZN(n_600), 
	.A2(n_76), 
	.A1(n_496));
   IND3D2 g2 (.ZN(n_602), 
	.B2(n_138), 
	.B1(x_min[0]), 
	.A1(xi[0]));
   DFQD4 \control_reg[0]  (.Q(control[0]), 
	.D(n_97), 
	.CP(rc_gclk_7532));
   DFQD4 \xi_ff_reg[0][2]  (.Q(\xi_ff[0] [2]), 
	.D(n_411), 
	.CP(rc_gclk_7520));
endmodule

