
// Generated by Cadence Encounter(R) RTL Compiler v12.10-s012_1

// Verification Directory fv/GCC 

module GCC(CLK, RESET, X, Y, W, READY, Xc, Yc);
  input CLK, RESET;
  input [7:0] X, Y;
  input [3:0] W;
  output READY;
  output [7:0] Xc, Yc;
  wire CLK, RESET;
  wire [7:0] X, Y;
  wire [3:0] W;
  wire READY;
  wire [7:0] Xc, Yc;
endmodule

