
// Generated by Cadence Encounter(R) RTL Compiler v12.10-s012_1

// Verification Directory fv/triangle 

module RC_CG_MOD(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_1(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_10(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_11(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_12(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_13(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_14(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_15(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_16(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_17(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_451(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLHQD1 RC_CGIC_INST(.E (enable), .CPN (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_451_1(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLHQD1 RC_CGIC_INST(.E (enable), .CPN (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_2(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_3(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_4(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_5(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_6(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_7(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_8(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_9(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module mult_signed(A, B, Z);
  input [6:0] A, B;
  output [6:0] Z;
  wire [6:0] A, B;
  wire [6:0] Z;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_69, n_70, n_71, n_73, n_74, n_77;
  MOAI22D0 g1251(.A1 (n_77), .A2 (n_73), .B1 (n_77), .B2 (n_73), .ZN
       (Z[6]));
  FA1D0 g1252(.A (n_64), .B (n_65), .CI (n_74), .CO (n_77), .S (Z[5]));
  FA1D0 g1253(.A (n_66), .B (n_56), .CI (n_71), .CO (n_74), .S (Z[4]));
  MOAI22D0 g1254(.A1 (n_70), .A2 (n_69), .B1 (n_70), .B2 (n_69), .ZN
       (n_73));
  FA1D0 g1255(.A (n_59), .B (n_53), .CI (n_67), .CO (n_71), .S (Z[3]));
  MAOI22D0 g1256(.A1 (n_62), .A2 (n_63), .B1 (n_62), .B2 (n_63), .ZN
       (n_70));
  MAOI222D0 g1257(.A (n_55), .B (n_58), .C (n_50), .ZN (n_69));
  FA1D0 g1258(.A (n_47), .B (n_37), .CI (n_48), .CO (n_67), .S (Z[2]));
  FA1D0 g1259(.A (n_44), .B (n_38), .CI (n_52), .CO (n_65), .S (n_66));
  MOAI22D0 g1260(.A1 (n_61), .A2 (n_58), .B1 (n_61), .B2 (n_58), .ZN
       (n_64));
  MAOI22D0 g1261(.A1 (n_0), .A2 (n_49), .B1 (n_0), .B2 (n_49), .ZN
       (n_63));
  MOAI22D0 g1262(.A1 (n_57), .A2 (n_54), .B1 (n_57), .B2 (n_54), .ZN
       (n_62));
  MAOI22D0 g1263(.A1 (n_55), .A2 (n_51), .B1 (n_55), .B2 (n_51), .ZN
       (n_61));
  AOI21D0 g1264(.A1 (n_45), .A2 (n_23), .B (n_48), .ZN (Z[1]));
  MOAI22D0 g1265(.A1 (n_43), .A2 (n_40), .B1 (n_43), .B2 (n_40), .ZN
       (n_59));
  MOAI22D0 g1266(.A1 (n_46), .A2 (n_39), .B1 (n_46), .B2 (n_39), .ZN
       (n_58));
  MAOI22D0 g1267(.A1 (n_41), .A2 (n_32), .B1 (n_41), .B2 (n_32), .ZN
       (n_57));
  NR2D0 g1268(.A1 (n_42), .A2 (n_40), .ZN (n_56));
  OAI22D0 g1270(.A1 (n_35), .A2 (n_27), .B1 (n_18), .B2 (n_21), .ZN
       (n_55));
  OAI22D0 g1271(.A1 (n_35), .A2 (n_21), .B1 (n_18), .B2 (n_28), .ZN
       (n_54));
  OAI22D0 g1272(.A1 (n_35), .A2 (n_31), .B1 (n_18), .B2 (n_29), .ZN
       (n_53));
  OAI22D0 g1273(.A1 (n_35), .A2 (n_29), .B1 (n_18), .B2 (n_27), .ZN
       (n_52));
  CKND0 g1274(.I (n_50), .ZN (n_51));
  OAI22D0 g1275(.A1 (n_36), .A2 (n_30), .B1 (n_26), .B2 (n_24), .ZN
       (n_50));
  OA22D0 g1276(.A1 (n_36), .A2 (n_24), .B1 (n_25), .B2 (n_26), .Z
       (n_49));
  NR2D0 g1277(.A1 (n_45), .A2 (n_23), .ZN (n_48));
  OAI22D0 g1278(.A1 (n_19), .A2 (n_10), .B1 (n_17), .B2 (n_3), .ZN
       (n_47));
  OAI22D0 g1280(.A1 (n_20), .A2 (n_10), .B1 (n_16), .B2 (n_3), .ZN
       (n_46));
  OA22D0 g1281(.A1 (n_22), .A2 (n_10), .B1 (n_3), .B2 (n_19), .Z
       (n_45));
  OAI22D0 g1282(.A1 (n_15), .A2 (n_10), .B1 (n_20), .B2 (n_3), .ZN
       (n_44));
  CKND0 g1283(.I (n_43), .ZN (n_42));
  OAI22D0 g1284(.A1 (n_17), .A2 (n_10), .B1 (n_15), .B2 (n_3), .ZN
       (n_43));
  OA22D0 g1285(.A1 (n_16), .A2 (n_10), .B1 (n_3), .B2 (n_14), .Z
       (n_41));
  CKND2D0 g1286(.A1 (B[3]), .A2 (n_34), .ZN (n_40));
  CKND2D0 g1287(.A1 (B[5]), .A2 (n_33), .ZN (n_39));
  NR2D0 g1288(.A1 (n_26), .A2 (n_4), .ZN (n_38));
  NR2D0 g1289(.A1 (n_18), .A2 (n_4), .ZN (n_37));
  OAI221D0 g1290(.A1 (B[5]), .A2 (B[4]), .B1 (n_2), .B2 (n_9), .C
       (n_26), .ZN (n_36));
  OAI221D0 g1291(.A1 (B[3]), .A2 (B[2]), .B1 (n_7), .B2 (n_8), .C
       (n_18), .ZN (n_35));
  MAOI222D0 g1292(.A (B[1]), .B (A[0]), .C (B[2]), .ZN (n_34));
  MAOI222D0 g1293(.A (B[3]), .B (A[0]), .C (B[4]), .ZN (n_33));
  AOI211D0 g1294(.A1 (B[5]), .A2 (B[6]), .B (n_11), .C (n_4), .ZN
       (n_32));
  AOI22D0 g1295(.A1 (n_4), .A2 (B[3]), .B1 (n_8), .B2 (A[0]), .ZN
       (n_31));
  AOI22D0 g1296(.A1 (n_4), .A2 (B[5]), .B1 (n_9), .B2 (A[0]), .ZN
       (n_30));
  AOI22D0 g1297(.A1 (n_6), .A2 (B[3]), .B1 (n_8), .B2 (A[1]), .ZN
       (n_29));
  MAOI22D0 g1298(.A1 (n_8), .A2 (A[4]), .B1 (n_8), .B2 (A[4]), .ZN
       (n_28));
  AOI22D0 g1299(.A1 (n_5), .A2 (B[3]), .B1 (n_8), .B2 (A[2]), .ZN
       (n_27));
  AOI22D0 g1300(.A1 (B[3]), .A2 (n_2), .B1 (n_8), .B2 (B[4]), .ZN
       (n_26));
  AOI22D0 g1301(.A1 (n_5), .A2 (B[5]), .B1 (n_9), .B2 (A[2]), .ZN
       (n_25));
  AOI22D0 g1302(.A1 (n_6), .A2 (B[5]), .B1 (n_9), .B2 (A[1]), .ZN
       (n_24));
  CKND2D0 g1303(.A1 (B[1]), .A2 (n_12), .ZN (n_23));
  AOI22D0 g1304(.A1 (n_4), .A2 (B[1]), .B1 (A[0]), .B2 (n_1), .ZN
       (n_22));
  MAOI22D0 g1305(.A1 (n_8), .A2 (A[3]), .B1 (n_8), .B2 (A[3]), .ZN
       (n_21));
  MAOI22D0 g1306(.A1 (A[4]), .A2 (n_1), .B1 (A[4]), .B2 (n_1), .ZN
       (n_20));
  AOI22D0 g1307(.A1 (n_6), .A2 (B[1]), .B1 (A[1]), .B2 (n_1), .ZN
       (n_19));
  AOI22D0 g1308(.A1 (n_7), .A2 (B[1]), .B1 (B[2]), .B2 (n_1), .ZN
       (n_18));
  AOI22D0 g1309(.A1 (n_5), .A2 (B[1]), .B1 (A[2]), .B2 (n_1), .ZN
       (n_17));
  MAOI22D0 g1310(.A1 (n_1), .A2 (A[5]), .B1 (n_1), .B2 (A[5]), .ZN
       (n_16));
  MAOI22D0 g1311(.A1 (n_1), .A2 (A[3]), .B1 (n_1), .B2 (A[3]), .ZN
       (n_15));
  MAOI22D0 g1312(.A1 (n_1), .A2 (A[6]), .B1 (n_1), .B2 (A[6]), .ZN
       (n_14));
  CKND0 g1313(.I (n_12), .ZN (Z[0]));
  CKND2D0 g1314(.A1 (B[0]), .A2 (A[0]), .ZN (n_12));
  NR2D0 g1315(.A1 (B[5]), .A2 (B[6]), .ZN (n_11));
  CKND2D0 g1316(.A1 (n_3), .A2 (B[1]), .ZN (n_10));
  CKND0 g1317(.I (B[5]), .ZN (n_9));
  CKND0 g1318(.I (B[3]), .ZN (n_8));
  CKND0 g1319(.I (B[2]), .ZN (n_7));
  CKND0 g1320(.I (A[1]), .ZN (n_6));
  CKND0 g1321(.I (A[2]), .ZN (n_5));
  CKND0 g1322(.I (A[0]), .ZN (n_4));
  CKND0 g1323(.I (B[0]), .ZN (n_3));
  CKND0 g1324(.I (B[4]), .ZN (n_2));
  CKND0 g1325(.I (B[1]), .ZN (n_1));
  INR2D0 g2(.A1 (n_46), .B1 (n_39), .ZN (n_0));
endmodule

module triangle(clk, reset, nt, xi, yi, busy, po, xo, yo);
  input clk, reset, nt;
  input [2:0] xi, yi;
  output busy, po;
  output [2:0] xo, yo;
  wire clk, reset, nt;
  wire [2:0] xi, yi;
  wire busy, po;
  wire [2:0] xo, yo;
  wire [6:0] mul_op0;
  wire [6:0] mul_op1;
  wire [6:0] A;
  wire [6:0] B;
  wire [6:0] C0;
  wire [6:0] C1;
  wire [6:0] D0;
  wire [6:0] D1;
  wire [2:0] x_max;
  wire [2:0] x_min;
  wire [2:0] x;
  wire [2:0] y_max;
  wire [2:0] y_min;
  wire [2:0] y;
  wire [6:0] sub_ans;
  wire [3:0] control;
  wire [6:0] AD;
  wire [6:0] BC;
  wire [6:0] RLO;
  wire [6:0] mul_ans;
  wire [6:0] sub_op0;
  wire [6:0] sub_op1;
  wire [2:0] \xi_ff[1] ;
  wire [2:0] \xi_ff[2] ;
  wire [2:0] \yi_ff[0] ;
  wire [2:0] \yi_ff[1] ;
  wire [2:0] \yi_ff[2] ;
  wire [2:0] \xi_ff[0] ;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, check, good;
  wire inc_x, inc_y, mul_en, n_0, n_1, n_2, n_3, n_5;
  wire n_7, n_8, n_9, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_104, n_105, n_106, n_107, n_108, n_109;
  wire n_110, n_111, n_112, n_113, n_114, n_115, n_116, n_117;
  wire n_118, n_119, n_120, n_121, n_122, n_124, n_125, n_126;
  wire n_127, n_128, n_129, n_130, n_131, n_132, n_133, n_134;
  wire n_135, n_136, n_137, n_138, n_139, n_140, n_141, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_186, n_187, n_188, n_189, n_190, n_191, n_192;
  wire n_193, n_194, n_195, n_196, n_198, n_199, n_200, n_201;
  wire n_202, n_203, n_204, n_205, n_206, n_207, n_208, n_209;
  wire n_210, n_211, n_212, n_213, n_214, n_215, n_216, n_217;
  wire n_218, n_219, n_220, n_221, n_222, n_225, n_226, n_227;
  wire n_228, n_229, n_230, n_231, n_232, n_233, n_234, n_235;
  wire n_236, n_237, n_238, n_239, n_240, n_241, n_242, n_243;
  wire n_244, n_245, n_246, n_247, n_248, n_249, n_250, n_251;
  wire n_252, n_253, n_254, n_255, n_256, n_258, n_259, n_260;
  wire n_261, n_262, n_263, n_264, n_265, n_266, n_267, n_268;
  wire n_269, n_270, n_271, n_272, n_273, n_274, n_275, n_276;
  wire n_277, n_278, n_279, n_280, n_281, n_282, n_283, n_284;
  wire n_285, n_286, n_287, n_288, n_289, n_290, n_291, n_292;
  wire n_293, n_294, n_295, n_296, n_297, n_298, n_299, n_300;
  wire n_301, n_302, n_303, n_304, n_305, n_306, n_307, n_308;
  wire n_309, n_310, n_311, n_312, n_313, n_314, n_315, n_317;
  wire n_318, n_319, n_320, n_321, n_322, n_323, n_324, n_325;
  wire n_326, n_327, n_328, n_329, n_330, n_331, n_332, n_333;
  wire n_334, n_335, n_336, n_337, n_339, n_340, n_343, n_354;
  wire n_357, n_358, n_359, n_360, n_361, n_362, n_363, n_364;
  wire n_365, n_366, n_367, n_368, n_371, n_372, n_374, n_375;
  wire n_376, n_377, n_378, n_380, n_381, rc_gclk, rc_gclk_7484,
       rc_gclk_7488;
  wire rc_gclk_7492, rc_gclk_7496, rc_gclk_7500, rc_gclk_7504,
       rc_gclk_7508, rc_gclk_7512, rc_gclk_7516, rc_gclk_7520;
  wire rc_gclk_7524, rc_gclk_7528, rc_gclk_7532, rc_gclk_7536,
       rc_gclk_7540, rc_gclk_7544, rc_gclk_7548, rc_gclk_7552;
  wire rc_gclk_7558, rst_int, sub_en, top_line;
  RC_CG_MOD RC_CG_HIER_INST0(.enable (n_314), .ck_in (clk), .ck_out
       (rc_gclk), .test (1'b0));
  RC_CG_MOD_1 RC_CG_HIER_INST1(.enable (n_313), .ck_in (clk), .ck_out
       (rc_gclk_7484), .test (1'b0));
  RC_CG_MOD_10 RC_CG_HIER_INST10(.enable (n_312), .ck_in (clk), .ck_out
       (rc_gclk_7520), .test (1'b0));
  RC_CG_MOD_11 RC_CG_HIER_INST11(.enable (n_311), .ck_in (clk), .ck_out
       (rc_gclk_7524), .test (1'b0));
  RC_CG_MOD_12 RC_CG_HIER_INST12(.enable (n_310), .ck_in (clk), .ck_out
       (rc_gclk_7528), .test (1'b0));
  RC_CG_MOD_13 RC_CG_HIER_INST13(.enable (n_297), .ck_in (clk), .ck_out
       (rc_gclk_7532), .test (1'b0));
  RC_CG_MOD_14 RC_CG_HIER_INST14(.enable (n_301), .ck_in (clk), .ck_out
       (rc_gclk_7536), .test (1'b0));
  RC_CG_MOD_15 RC_CG_HIER_INST15(.enable (n_300), .ck_in (clk), .ck_out
       (rc_gclk_7540), .test (1'b0));
  RC_CG_MOD_16 RC_CG_HIER_INST16(.enable (n_299), .ck_in (clk), .ck_out
       (rc_gclk_7544), .test (1'b0));
  RC_CG_MOD_17 RC_CG_HIER_INST17(.enable (n_298), .ck_in (clk), .ck_out
       (rc_gclk_7548), .test (1'b0));
  RC_CG_MOD_451 RC_CG_HIER_INST18(.enable (n_315), .ck_in (clk),
       .ck_out (rc_gclk_7552), .test (1'b0));
  RC_CG_MOD_451_1 RC_CG_HIER_INST19(.enable (inc_y), .ck_in (clk),
       .ck_out (rc_gclk_7558), .test (1'b0));
  RC_CG_MOD_2 RC_CG_HIER_INST2(.enable (n_309), .ck_in (clk), .ck_out
       (rc_gclk_7488), .test (1'b0));
  RC_CG_MOD_3 RC_CG_HIER_INST3(.enable (n_308), .ck_in (clk), .ck_out
       (rc_gclk_7492), .test (1'b0));
  RC_CG_MOD_4 RC_CG_HIER_INST4(.enable (n_307), .ck_in (clk), .ck_out
       (rc_gclk_7496), .test (1'b0));
  RC_CG_MOD_5 RC_CG_HIER_INST5(.enable (n_306), .ck_in (clk), .ck_out
       (rc_gclk_7500), .test (1'b0));
  RC_CG_MOD_6 RC_CG_HIER_INST6(.enable (n_305), .ck_in (clk), .ck_out
       (rc_gclk_7504), .test (1'b0));
  RC_CG_MOD_7 RC_CG_HIER_INST7(.enable (n_304), .ck_in (clk), .ck_out
       (rc_gclk_7508), .test (1'b0));
  RC_CG_MOD_8 RC_CG_HIER_INST8(.enable (n_303), .ck_in (clk), .ck_out
       (rc_gclk_7512), .test (1'b0));
  RC_CG_MOD_9 RC_CG_HIER_INST9(.enable (n_302), .ck_in (clk), .ck_out
       (rc_gclk_7516), .test (1'b0));
  mult_signed mul_211_31(.A (mul_op0), .B (mul_op1), .Z ({n_357, n_358,
       n_360, n_361, n_362, n_363, n_364}));
  CKND0 g3650(.I (n_331), .ZN (n_297));
  DFQD1 \A_reg[3] (.CP (rc_gclk_7484), .D (n_325), .Q (A[3]));
  DFQD1 \A_reg[6] (.CP (rc_gclk_7484), .D (n_323), .Q (A[6]));
  DFQD1 \B_reg[3] (.CP (rc_gclk_7488), .D (n_325), .Q (B[3]));
  DFQD1 \B_reg[6] (.CP (rc_gclk_7488), .D (n_323), .Q (B[6]));
  DFQD1 \C0_reg[0] (.CP (rc_gclk_7500), .D (n_327), .Q (C0[0]));
  DFQD1 \C0_reg[1] (.CP (rc_gclk_7500), .D (n_326), .Q (C0[1]));
  DFQD1 \C0_reg[4] (.CP (rc_gclk_7500), .D (n_324), .Q (C0[4]));
  DFQD1 \C0_reg[6] (.CP (rc_gclk_7500), .D (n_323), .Q (C0[6]));
  DFQD1 \C1_reg[0] (.CP (rc_gclk_7508), .D (n_327), .Q (C1[0]));
  DFQD1 \C1_reg[1] (.CP (rc_gclk_7508), .D (n_326), .Q (C1[1]));
  DFQD1 \C1_reg[4] (.CP (rc_gclk_7508), .D (n_324), .Q (C1[4]));
  DFQD1 \C1_reg[6] (.CP (rc_gclk_7508), .D (n_323), .Q (C1[6]));
  SDFQND0 \D0_reg[0] (.CP (rc_gclk_7512), .D (n_327), .SI (1'b0), .SE
       (1'b0), .QN (D0[0]));
  SDFQND0 \D0_reg[1] (.CP (rc_gclk_7512), .D (n_326), .SI (1'b0), .SE
       (1'b0), .QN (D0[1]));
  SDFQND0 \D0_reg[4] (.CP (rc_gclk_7512), .D (n_324), .SI (1'b0), .SE
       (1'b0), .QN (D0[4]));
  SDFQND0 \D0_reg[6] (.CP (rc_gclk_7512), .D (n_323), .SI (1'b0), .SE
       (1'b0), .QN (D0[6]));
  SDFQND0 \D1_reg[0] (.CP (rc_gclk_7516), .D (n_327), .SI (1'b0), .SE
       (1'b0), .QN (D1[0]));
  SDFQND0 \D1_reg[1] (.CP (rc_gclk_7516), .D (n_326), .SI (1'b0), .SE
       (1'b0), .QN (D1[1]));
  SDFQND0 \D1_reg[4] (.CP (rc_gclk_7516), .D (n_324), .SI (1'b0), .SE
       (1'b0), .QN (D1[4]));
  SDFQND0 \D1_reg[6] (.CP (rc_gclk_7516), .D (n_323), .SI (1'b0), .SE
       (1'b0), .QN (D1[6]));
  DFQD1 busy_reg(.CP (rc_gclk_7496), .D (n_329), .Q (busy));
  LHQD1 \mul_op0_reg[3] (.E (n_354), .D (n_275), .Q (mul_op0[3]));
  LHQD1 \mul_op0_reg[6] (.E (n_354), .D (n_274), .Q (mul_op0[6]));
  LHQD1 \mul_op1_reg[0] (.E (n_354), .D (n_287), .Q (mul_op1[0]));
  LHQD1 \mul_op1_reg[1] (.E (n_354), .D (n_286), .Q (mul_op1[1]));
  LHQD1 \mul_op1_reg[4] (.E (n_354), .D (n_285), .Q (mul_op1[4]));
  LHQD1 \mul_op1_reg[6] (.E (n_354), .D (n_284), .Q (mul_op1[6]));
  DFQD4 \x_max_reg[0] (.CP (rc_gclk_7536), .D (n_322), .Q (x_max[0]));
  DFQD1 \x_max_reg[1] (.CP (rc_gclk_7536), .D (n_321), .Q (x_max[1]));
  DFQD1 \x_max_reg[2] (.CP (rc_gclk_7536), .D (n_320), .Q (x_max[2]));
  DFQD2 \x_min_reg[0] (.CP (rc_gclk_7540), .D (n_250), .Q (x_min[0]));
  DFQD1 \x_min_reg[1] (.CP (rc_gclk_7540), .D (n_255), .Q (x_min[1]));
  DFQD1 \x_min_reg[2] (.CP (rc_gclk_7540), .D (n_252), .Q (x_min[2]));
  DFKCNQD1 \xo_reg[0] (.CP (rc_gclk_7528), .CN (x[0]), .D (n_329), .Q
       (xo[0]));
  DFKCNQD1 \xo_reg[1] (.CP (rc_gclk_7528), .CN (x[1]), .D (n_329), .Q
       (xo[1]));
  DFKCNQD1 \xo_reg[2] (.CP (rc_gclk_7528), .CN (x[2]), .D (n_329), .Q
       (xo[2]));
  SDFQND0 \y_max_reg[0] (.CP (rc_gclk_7544), .D (n_319), .SI (1'b0),
       .SE (1'b0), .QN (n_296));
  DFQD1 \y_max_reg[1] (.CP (rc_gclk_7544), .D (n_318), .Q (y_max[1]));
  DFQD1 \y_max_reg[2] (.CP (rc_gclk_7544), .D (n_317), .Q (y_max[2]));
  DFQD1 \y_min_reg[0] (.CP (rc_gclk_7548), .D (n_251), .Q (y_min[0]));
  DFQD1 \y_min_reg[1] (.CP (rc_gclk_7548), .D (n_253), .Q (y_min[1]));
  DFQD1 \y_min_reg[2] (.CP (rc_gclk_7548), .D (n_254), .Q (y_min[2]));
  DFKCNQD1 \yo_reg[0] (.CP (rc_gclk_7528), .CN (y[0]), .D (n_329), .Q
       (yo[0]));
  DFKCNQD1 \yo_reg[1] (.CP (rc_gclk_7528), .CN (y[1]), .D (n_329), .Q
       (yo[1]));
  DFKCNQD1 \yo_reg[2] (.CP (rc_gclk_7528), .CN (y[2]), .D (n_329), .Q
       (yo[2]));
  NR2XD0 g4900(.A1 (n_294), .A2 (n_259), .ZN (n_301));
  NR2XD0 g4901(.A1 (n_295), .A2 (n_259), .ZN (n_299));
  NR2XD0 g4902(.A1 (n_259), .A2 (n_293), .ZN (n_300));
  NR2D0 g4903(.A1 (n_259), .A2 (n_292), .ZN (n_298));
  NR2D0 g4904(.A1 (n_290), .A2 (n_272), .ZN (n_295));
  NR2D0 g4905(.A1 (n_291), .A2 (n_270), .ZN (n_294));
  NR2XD0 g4906(.A1 (n_273), .A2 (n_289), .ZN (n_293));
  NR2D0 g4907(.A1 (n_271), .A2 (n_288), .ZN (n_292));
  AOI211XD1 g4908(.A1 (n_380), .A2 (x_max[1]), .B (n_283), .C (n_263),
       .ZN (n_291));
  AOI211XD0 g4909(.A1 (n_265), .A2 (y_max[1]), .B (n_282), .C (n_264),
       .ZN (n_290));
  AOI21D0 g4910(.A1 (n_266), .A2 (xi[1]), .B (n_281), .ZN (n_289));
  AOI21D1 g4911(.A1 (n_267), .A2 (yi[1]), .B (n_280), .ZN (n_288));
  OAI221D0 g4916(.A1 (n_260), .A2 (D0[0]), .B1 (D1[0]), .B2 (n_261), .C
       (n_279), .ZN (n_287));
  OAI221D0 g4917(.A1 (n_260), .A2 (D0[1]), .B1 (D1[1]), .B2 (n_261), .C
       (n_278), .ZN (n_286));
  OAI221D0 g4918(.A1 (n_260), .A2 (D0[4]), .B1 (D1[4]), .B2 (n_261), .C
       (n_277), .ZN (n_285));
  OAI221D0 g4919(.A1 (n_260), .A2 (D0[6]), .B1 (D1[6]), .B2 (n_261), .C
       (n_276), .ZN (n_284));
  NR2D1 g4920(.A1 (n_269), .A2 (xi[1]), .ZN (n_283));
  NR2D0 g4921(.A1 (n_268), .A2 (yi[1]), .ZN (n_282));
  OAI22D1 g4922(.A1 (n_226), .A2 (x_min[1]), .B1 (x_min[2]), .B2
       (n_228), .ZN (n_281));
  OAI22D0 g4923(.A1 (n_225), .A2 (y_min[1]), .B1 (y_min[2]), .B2
       (n_227), .ZN (n_280));
  AOI22D0 g4926(.A1 (n_367), .A2 (C0[0]), .B1 (n_368), .B2 (C1[0]), .ZN
       (n_279));
  AOI22D0 g4927(.A1 (n_367), .A2 (C0[1]), .B1 (n_368), .B2 (C1[1]), .ZN
       (n_278));
  AOI22D0 g4928(.A1 (n_367), .A2 (C0[4]), .B1 (n_368), .B2 (C1[4]), .ZN
       (n_277));
  AOI22D0 g4929(.A1 (n_367), .A2 (C0[6]), .B1 (n_368), .B2 (C1[6]), .ZN
       (n_276));
  AO22D0 g4930(.A1 (n_335), .A2 (B[3]), .B1 (A[3]), .B2 (n_340), .Z
       (n_275));
  AO22D0 g4931(.A1 (n_335), .A2 (B[6]), .B1 (A[6]), .B2 (n_340), .Z
       (n_274));
  IOA21D0 g4932(.A1 (x_min[2]), .A2 (n_228), .B (n_329), .ZN (n_273));
  OAI21D0 g4933(.A1 (n_227), .A2 (y_max[2]), .B (n_329), .ZN (n_272));
  IOA21D0 g4934(.A1 (y_min[2]), .A2 (n_227), .B (n_329), .ZN (n_271));
  OAI21D0 g4935(.A1 (n_228), .A2 (x_max[2]), .B (n_329), .ZN (n_270));
  NR2XD0 g4936(.A1 (n_380), .A2 (x_max[1]), .ZN (n_269));
  NR2XD0 g4937(.A1 (n_265), .A2 (y_max[1]), .ZN (n_268));
  CKND2D0 g4938(.A1 (y_min[1]), .A2 (n_225), .ZN (n_267));
  CKND2D0 g4939(.A1 (x_min[1]), .A2 (n_226), .ZN (n_266));
  NR2D0 g4940(.A1 (n_262), .A2 (n_241), .ZN (n_331));
  OAI21D0 g4941(.A1 (n_229), .A2 (n_343), .B (n_329), .ZN (n_312));
  CKND2D0 g4943(.A1 (yi[0]), .A2 (n_296), .ZN (n_265));
  NR2D0 g4944(.A1 (n_258), .A2 (yi[2]), .ZN (n_264));
  NR2D0 g4945(.A1 (n_256), .A2 (xi[2]), .ZN (n_263));
  CKND2D0 g4948(.A1 (n_329), .A2 (n_337), .ZN (n_309));
  CKND2D0 g4949(.A1 (n_329), .A2 (n_333), .ZN (n_304));
  CKND2D0 g4950(.A1 (n_329), .A2 (n_248), .ZN (n_302));
  CKND2D0 g4951(.A1 (n_329), .A2 (n_249), .ZN (n_303));
  CKND2D0 g4952(.A1 (n_229), .A2 (n_247), .ZN (n_262));
  CKND2D0 g4953(.A1 (n_329), .A2 (n_339), .ZN (n_313));
  CKND2D0 g4954(.A1 (n_329), .A2 (n_245), .ZN (n_305));
  CKND2D0 g4955(.A1 (n_329), .A2 (n_246), .ZN (n_314));
  IOA21D0 g4956(.A1 (n_237), .A2 (n_239), .B (n_329), .ZN (n_311));
  IOA21D0 g4957(.A1 (n_234), .A2 (n_239), .B (n_329), .ZN (n_307));
  CKAN2D0 g4958(.A1 (n_335), .A2 (top_line), .Z (n_368));
  NR2D0 g4959(.A1 (n_245), .A2 (top_line), .ZN (n_367));
  CKND0 g4960(.I (n_261), .ZN (n_366));
  CKND2D0 g4961(.A1 (top_line), .A2 (n_340), .ZN (n_261));
  CKND0 g4962(.I (n_365), .ZN (n_260));
  NR2D0 g4963(.A1 (n_246), .A2 (top_line), .ZN (n_365));
  CKND2D0 g4964(.A1 (n_245), .A2 (n_246), .ZN (n_354));
  CKND2D0 g4965(.A1 (n_329), .A2 (n_332), .ZN (n_310));
  CKND2D0 g4966(.A1 (n_329), .A2 (n_243), .ZN (n_308));
  CKND2D0 g4967(.A1 (n_329), .A2 (n_244), .ZN (n_306));
  NR2D1 g4968(.A1 (n_241), .A2 (n_242), .ZN (n_259));
  CKND0 g4971(.I (y_max[2]), .ZN (n_258));
  CKND0 g5007(.I (n_296), .ZN (y_max[0]));
  CKND0 g5011(.I (x_max[2]), .ZN (n_256));
  IND2D0 g5013(.A1 (xi[1]), .B1 (n_329), .ZN (n_255));
  CKAN2D0 g5014(.A1 (n_329), .A2 (xi[1]), .Z (n_321));
  NR2D0 g5015(.A1 (n_241), .A2 (n_228), .ZN (n_320));
  CKND2D0 g5016(.A1 (n_227), .A2 (n_329), .ZN (n_254));
  IND2D0 g5017(.A1 (yi[1]), .B1 (n_329), .ZN (n_253));
  CKND2D0 g5018(.A1 (n_228), .A2 (n_329), .ZN (n_252));
  IND2D0 g5019(.A1 (yi[0]), .B1 (n_329), .ZN (n_251));
  IND2D0 g5020(.A1 (xi[0]), .B1 (n_329), .ZN (n_250));
  INR2XD1 g5021(.A1 (sub_ans[4]), .B1 (n_241), .ZN (n_324));
  INR2XD1 g5022(.A1 (sub_ans[6]), .B1 (n_241), .ZN (n_323));
  CKAN2D1 g5023(.A1 (n_329), .A2 (sub_ans[3]), .Z (n_325));
  CKAN2D0 g5024(.A1 (n_329), .A2 (xi[0]), .Z (n_322));
  NR2XD0 g5026(.A1 (n_241), .A2 (n_227), .ZN (n_317));
  CKAN2D0 g5027(.A1 (n_329), .A2 (yi[0]), .Z (n_319));
  ND2D1 g5028(.A1 (n_235), .A2 (n_238), .ZN (n_337));
  CKND0 g5029(.I (n_249), .ZN (n_330));
  CKND2D0 g5030(.A1 (n_240), .A2 (n_235), .ZN (n_249));
  CKND2D0 g5031(.A1 (n_235), .A2 (n_234), .ZN (n_333));
  CKND2 g5032(.I (n_248), .ZN (n_328));
  ND2D1 g5033(.A1 (n_235), .A2 (n_237), .ZN (n_248));
  CKND0 g5034(.I (n_343), .ZN (n_247));
  CKND2D0 g5035(.A1 (n_240), .A2 (n_239), .ZN (n_343));
  CKND0 g5036(.I (n_246), .ZN (n_340));
  CKND2D0 g5037(.A1 (n_237), .A2 (n_236), .ZN (n_246));
  CKND0 g5038(.I (n_245), .ZN (n_335));
  CKND2D0 g5039(.A1 (n_236), .A2 (n_240), .ZN (n_245));
  ND2D2 g5040(.A1 (n_236), .A2 (n_234), .ZN (n_339));
  CKAN2D1 g5041(.A1 (n_329), .A2 (sub_ans[1]), .Z (n_326));
  CKAN2D1 g5042(.A1 (n_329), .A2 (sub_ans[0]), .Z (n_327));
  ND3D0 g5043(.A1 (n_240), .A2 (control[2]), .A3 (control[3]), .ZN
       (n_332));
  CKND0 g5044(.I (n_244), .ZN (n_334));
  CKND2D0 g5045(.A1 (n_239), .A2 (n_238), .ZN (n_244));
  CKND0 g5046(.I (n_243), .ZN (n_336));
  CKND2D0 g5047(.A1 (n_236), .A2 (n_238), .ZN (n_243));
  CKND0 g5048(.I (n_242), .ZN (n_359));
  AOI21D0 g5049(.A1 (control[2]), .A2 (control[1]), .B (control[3]),
       .ZN (n_242));
  CKND2 g5051(.I (n_329), .ZN (n_241));
  NR2XD8 g5052(.A1 (rst_int), .A2 (reset), .ZN (n_329));
  OR2D0 g5053(.A1 (inc_x), .A2 (inc_y), .Z (n_315));
  NR2XD1 g5054(.A1 (control[1]), .A2 (control[0]), .ZN (n_240));
  NR2XD1 g5055(.A1 (control[3]), .A2 (control[2]), .ZN (n_239));
  AN2XD1 g5056(.A1 (control[1]), .A2 (control[0]), .Z (n_238));
  NR2D1 g5057(.A1 (n_232), .A2 (control[0]), .ZN (n_237));
  NR2D2 g5058(.A1 (n_230), .A2 (control[2]), .ZN (n_236));
  NR2D2 g5059(.A1 (n_233), .A2 (control[3]), .ZN (n_235));
  NR2XD1 g5060(.A1 (n_231), .A2 (control[1]), .ZN (n_234));
  CKND2 g5061(.I (control[2]), .ZN (n_233));
  CKND1 g5062(.I (control[1]), .ZN (n_232));
  CKND1 g5063(.I (control[0]), .ZN (n_231));
  CKND1 g5064(.I (control[3]), .ZN (n_230));
  CKND0 g5065(.I (nt), .ZN (n_229));
  CKND0 g5066(.I (xi[2]), .ZN (n_228));
  CKND0 g5067(.I (yi[2]), .ZN (n_227));
  INR2XD0 g2(.A1 (x_min[0]), .B1 (xi[0]), .ZN (n_226));
  DFQD1 \AD_reg[0] (.CP (rc_gclk), .D (n_53), .Q (AD[0]));
  DFQD1 \AD_reg[1] (.CP (rc_gclk), .D (n_52), .Q (AD[1]));
  SDFQND0 \AD_reg[2] (.CP (rc_gclk), .D (n_51), .SI (1'b0), .SE (1'b0),
       .QN (AD[2]));
  SDFQND0 \AD_reg[3] (.CP (rc_gclk), .D (n_50), .SI (1'b0), .SE (1'b0),
       .QN (AD[3]));
  SDFQND0 \AD_reg[4] (.CP (rc_gclk), .D (n_48), .SI (1'b0), .SE (1'b0),
       .QN (AD[4]));
  SDFQND0 \AD_reg[5] (.CP (rc_gclk), .D (n_49), .SI (1'b0), .SE (1'b0),
       .QN (AD[5]));
  SDFQND0 \AD_reg[6] (.CP (rc_gclk), .D (n_47), .SI (1'b0), .SE (1'b0),
       .QN (AD[6]));
  DFQD1 \A_reg[0] (.CP (rc_gclk_7484), .D (n_327), .Q (A[0]));
  DFQD1 \A_reg[1] (.CP (rc_gclk_7484), .D (n_326), .Q (A[1]));
  DFQD1 \A_reg[2] (.CP (rc_gclk_7484), .D (n_46), .Q (A[2]));
  DFQD1 \A_reg[4] (.CP (rc_gclk_7484), .D (n_324), .Q (A[4]));
  DFQD1 \A_reg[5] (.CP (rc_gclk_7484), .D (n_45), .Q (A[5]));
  DFQD1 \BC_reg[0] (.CP (rc_gclk_7504), .D (n_53), .Q (BC[0]));
  DFQD1 \BC_reg[1] (.CP (rc_gclk_7504), .D (n_52), .Q (BC[1]));
  DFQD1 \BC_reg[2] (.CP (rc_gclk_7504), .D (n_51), .Q (BC[2]));
  SDFQND0 \BC_reg[3] (.CP (rc_gclk_7504), .D (n_50), .SI (1'b0), .SE
       (1'b0), .QN (BC[3]));
  SDFQND0 \BC_reg[4] (.CP (rc_gclk_7504), .D (n_48), .SI (1'b0), .SE
       (1'b0), .QN (BC[4]));
  SDFQND0 \BC_reg[5] (.CP (rc_gclk_7504), .D (n_49), .SI (1'b0), .SE
       (1'b0), .QN (BC[5]));
  SDFQND0 \BC_reg[6] (.CP (rc_gclk_7504), .D (n_47), .SI (1'b0), .SE
       (1'b0), .QN (BC[6]));
  DFQD1 \B_reg[0] (.CP (rc_gclk_7488), .D (n_327), .Q (B[0]));
  DFQD1 \B_reg[1] (.CP (rc_gclk_7488), .D (n_326), .Q (B[1]));
  DFQD1 \B_reg[2] (.CP (rc_gclk_7488), .D (n_46), .Q (B[2]));
  DFQD1 \B_reg[4] (.CP (rc_gclk_7488), .D (n_324), .Q (B[4]));
  DFQD1 \B_reg[5] (.CP (rc_gclk_7488), .D (n_45), .Q (B[5]));
  DFQD1 \C0_reg[2] (.CP (rc_gclk_7500), .D (n_46), .Q (C0[2]));
  DFQD1 \C0_reg[3] (.CP (rc_gclk_7500), .D (n_325), .Q (C0[3]));
  DFQD1 \C0_reg[5] (.CP (rc_gclk_7500), .D (n_45), .Q (C0[5]));
  DFQD1 \C1_reg[2] (.CP (rc_gclk_7508), .D (n_46), .Q (C1[2]));
  DFQD1 \C1_reg[3] (.CP (rc_gclk_7508), .D (n_325), .Q (C1[3]));
  DFQD1 \C1_reg[5] (.CP (rc_gclk_7508), .D (n_45), .Q (C1[5]));
  DFQD1 \D0_reg[2] (.CP (rc_gclk_7512), .D (n_46), .Q (D0[2]));
  DFQD1 \D0_reg[3] (.CP (rc_gclk_7512), .D (n_325), .Q (D0[3]));
  DFQD1 \D0_reg[5] (.CP (rc_gclk_7512), .D (n_45), .Q (D0[5]));
  DFQD1 \D1_reg[2] (.CP (rc_gclk_7516), .D (n_46), .Q (D1[2]));
  DFQD1 \D1_reg[3] (.CP (rc_gclk_7516), .D (n_325), .Q (D1[3]));
  DFQD1 \D1_reg[5] (.CP (rc_gclk_7516), .D (n_45), .Q (D1[5]));
  SDFQND0 \RLO_reg[0] (.CP (rc_gclk_7492), .D (n_327), .SI (1'b0), .SE
       (1'b0), .QN (RLO[0]));
  SDFQND0 \RLO_reg[1] (.CP (rc_gclk_7492), .D (n_326), .SI (1'b0), .SE
       (1'b0), .QN (RLO[1]));
  SDFQND1 \RLO_reg[2] (.CP (rc_gclk_7492), .D (n_46), .SI (1'b0), .SE
       (1'b0), .QN (RLO[2]));
  SDFQND0 \RLO_reg[3] (.CP (rc_gclk_7492), .D (n_325), .SI (1'b0), .SE
       (1'b0), .QN (RLO[3]));
  DFQD1 \RLO_reg[4] (.CP (rc_gclk_7492), .D (n_324), .Q (RLO[4]));
  DFQD1 \RLO_reg[5] (.CP (rc_gclk_7492), .D (n_45), .Q (RLO[5]));
  DFQD1 \RLO_reg[6] (.CP (rc_gclk_7492), .D (n_323), .Q (RLO[6]));
  DFQD1 check_reg(.CP (clk), .D (n_156), .Q (check));
  DFQD4 \control_reg[0] (.CP (rc_gclk_7532), .D (n_171), .Q
       (control[0]));
  DFQD4 \control_reg[1] (.CP (rc_gclk_7532), .D (n_186), .Q
       (control[1]));
  DFQD4 \control_reg[2] (.CP (rc_gclk_7532), .D (n_187), .Q
       (control[2]));
  DFQD4 \control_reg[3] (.CP (rc_gclk_7532), .D (n_381), .Q
       (control[3]));
  DFQD1 good_reg(.CP (check), .D (n_209), .Q (good));
  DFQD1 inc_x_reg(.CP (clk), .D (n_200), .Q (inc_x));
  LHQD1 \mul_ans_reg[0] (.E (mul_en), .D (n_364), .Q (mul_ans[0]));
  LHQD1 \mul_ans_reg[1] (.E (mul_en), .D (n_363), .Q (mul_ans[1]));
  LHQD1 \mul_ans_reg[2] (.E (mul_en), .D (n_362), .Q (mul_ans[2]));
  LHQD1 \mul_ans_reg[3] (.E (mul_en), .D (n_361), .Q (mul_ans[3]));
  LHQD1 \mul_ans_reg[4] (.E (mul_en), .D (n_360), .Q (mul_ans[4]));
  LHQD1 \mul_ans_reg[5] (.E (mul_en), .D (n_358), .Q (mul_ans[5]));
  LHQD1 \mul_ans_reg[6] (.E (mul_en), .D (n_357), .Q (mul_ans[6]));
  LNQD1 mul_en_reg(.EN (n_155), .D (n_354), .Q (mul_en));
  LHQD1 \mul_op0_reg[0] (.E (n_354), .D (n_126), .Q (mul_op0[0]));
  LHQD1 \mul_op0_reg[1] (.E (n_354), .D (n_125), .Q (mul_op0[1]));
  LHQD1 \mul_op0_reg[2] (.E (n_354), .D (n_148), .Q (mul_op0[2]));
  LHQD1 \mul_op0_reg[4] (.E (n_354), .D (n_127), .Q (mul_op0[4]));
  LHQD1 \mul_op0_reg[5] (.E (n_354), .D (n_147), .Q (mul_op0[5]));
  LHQD1 \mul_op1_reg[2] (.E (n_354), .D (n_178), .Q (mul_op1[2]));
  LHQD1 \mul_op1_reg[3] (.E (n_354), .D (n_160), .Q (mul_op1[3]));
  LHQD1 \mul_op1_reg[5] (.E (n_354), .D (n_176), .Q (mul_op1[5]));
  DFNSND1 po__reg(.SDN (1'b1), .CPN (clk), .D (n_221), .Q (n_0), .QN
       (UNCONNECTED));
  DFNSND1 po_reg(.SDN (1'b1), .CPN (clk), .D (n_218), .Q (po), .QN
       (UNCONNECTED0));
  DFQD4 rst_int_reg(.CP (clk), .D (n_198), .Q (rst_int));
  LHQD1 \sub_ans_reg[0] (.E (sub_en), .D (n_83), .Q (sub_ans[0]));
  LHQD1 \sub_ans_reg[1] (.E (sub_en), .D (n_182), .Q (sub_ans[1]));
  LHQD1 \sub_ans_reg[2] (.E (sub_en), .D (n_202), .Q (sub_ans[2]));
  LHQD1 \sub_ans_reg[3] (.E (sub_en), .D (n_207), .Q (sub_ans[3]));
  LHQD1 \sub_ans_reg[4] (.E (sub_en), .D (n_210), .Q (sub_ans[4]));
  LHQD1 \sub_ans_reg[5] (.E (sub_en), .D (n_217), .Q (sub_ans[5]));
  LHQD1 \sub_ans_reg[6] (.E (sub_en), .D (n_222), .Q (sub_ans[6]));
  LNQD1 sub_en_reg(.EN (n_180), .D (n_60), .Q (sub_en));
  LNQD1 \sub_op0_reg[0] (.EN (n_158), .D (n_159), .Q (sub_op0[0]));
  LNQD1 \sub_op0_reg[1] (.EN (n_158), .D (n_177), .Q (sub_op0[1]));
  LNQD1 \sub_op0_reg[2] (.EN (n_158), .D (n_175), .Q (sub_op0[2]));
  LNQD1 \sub_op0_reg[3] (.EN (n_158), .D (n_122), .Q (sub_op0[3]));
  LNQD1 \sub_op0_reg[4] (.EN (n_158), .D (n_121), .Q (sub_op0[4]));
  LNQD1 \sub_op0_reg[5] (.EN (n_158), .D (n_120), .Q (sub_op0[5]));
  LNQD1 \sub_op0_reg[6] (.EN (n_158), .D (n_119), .Q (sub_op0[6]));
  LNQD1 \sub_op1_reg[0] (.EN (n_158), .D (n_190), .Q (sub_op1[0]));
  LNQD1 \sub_op1_reg[1] (.EN (n_158), .D (n_189), .Q (sub_op1[1]));
  LNQD1 \sub_op1_reg[2] (.EN (n_158), .D (n_188), .Q (sub_op1[2]));
  LNQD1 \sub_op1_reg[3] (.EN (n_158), .D (n_117), .Q (sub_op1[3]));
  LNQD1 \sub_op1_reg[4] (.EN (n_158), .D (n_116), .Q (sub_op1[4]));
  LNQD1 \sub_op1_reg[5] (.EN (n_158), .D (n_114), .Q (sub_op1[5]));
  LNQD1 \sub_op1_reg[6] (.EN (n_158), .D (n_115), .Q (sub_op1[6]));
  SDFNSND4 \x_reg[0] (.SDN (1'b1), .CPN (rc_gclk_7552), .D (n_23), .SI
       (x_min[0]), .SE (inc_y), .Q (x[0]), .QN (UNCONNECTED1));
  DFNSND4 \x_reg[1] (.SDN (1'b1), .CPN (rc_gclk_7552), .D (n_169), .Q
       (x[1]), .QN (n_25));
  DFNSND4 \x_reg[2] (.SDN (1'b1), .CPN (rc_gclk_7552), .D (n_194), .Q
       (x[2]), .QN (n_24));
  DFQD1 \xi_ff_reg[1][1] (.CP (rc_gclk_7496), .D (n_321), .Q
       (\xi_ff[1] [1]));
  SDFQND1 \xi_ff_reg[2][0] (.CP (rc_gclk_7524), .D (n_322), .SI (1'b0),
       .SE (1'b0), .QN (\xi_ff[2] [0]));
  DFQD1 \xi_ff_reg[2][1] (.CP (rc_gclk_7524), .D (n_321), .Q
       (\xi_ff[2] [1]));
  DFQD1 \xi_ff_reg[2][2] (.CP (rc_gclk_7524), .D (n_320), .Q
       (\xi_ff[2] [2]));
  DFNSND4 \y_reg[0] (.SDN (1'b1), .CPN (rc_gclk_7558), .D (n_95), .Q
       (y[0]), .QN (n_21));
  DFNSND4 \y_reg[1] (.SDN (1'b1), .CPN (rc_gclk_7558), .D (n_170), .Q
       (y[1]), .QN (n_22));
  DFNSND2 \y_reg[2] (.SDN (1'b1), .CPN (rc_gclk_7558), .D (n_192), .Q
       (y[2]), .QN (UNCONNECTED2));
  SDFQND0 \yi_ff_reg[0][0] (.CP (rc_gclk_7520), .D (n_319), .SI (1'b0),
       .SE (1'b0), .QN (\yi_ff[0] [0]));
  SDFQND0 \yi_ff_reg[0][1] (.CP (rc_gclk_7520), .D (n_318), .SI (1'b0),
       .SE (1'b0), .QN (\yi_ff[0] [1]));
  SDFQND0 \yi_ff_reg[0][2] (.CP (rc_gclk_7520), .D (n_317), .SI (1'b0),
       .SE (1'b0), .QN (\yi_ff[0] [2]));
  SDFQND0 \yi_ff_reg[1][2] (.CP (rc_gclk_7496), .D (n_317), .SI (1'b0),
       .SE (1'b0), .QN (\yi_ff[1] [2]));
  SDFQND0 \yi_ff_reg[2][0] (.CP (rc_gclk_7524), .D (n_319), .SI (1'b0),
       .SE (1'b0), .QN (\yi_ff[2] [0]));
  SDFQND0 \yi_ff_reg[2][1] (.CP (rc_gclk_7524), .D (n_318), .SI (1'b0),
       .SE (1'b0), .QN (\yi_ff[2] [1]));
  SDFQND0 \yi_ff_reg[2][2] (.CP (rc_gclk_7524), .D (n_317), .SI (1'b0),
       .SE (1'b0), .QN (\yi_ff[2] [2]));
  MOAI22D0 g11297(.A1 (n_216), .A2 (n_74), .B1 (n_216), .B2 (n_74), .ZN
       (n_222));
  AO21D0 g11298(.A1 (n_0), .A2 (n_213), .B (n_215), .Z (n_221));
  CKND2D1 g11301(.A1 (n_172), .A2 (n_219), .ZN (n_220));
  OAI21D1 g11303(.A1 (n_374), .A2 (n_214), .B (n_164), .ZN (n_219));
  AO21D0 g11304(.A1 (po), .A2 (n_212), .B (n_215), .Z (n_218));
  MOAI22D0 g11305(.A1 (n_211), .A2 (n_77), .B1 (n_211), .B2 (n_77), .ZN
       (n_217));
  MAOI222D0 g11306(.A (n_211), .B (n_14), .C (sub_op0[5]), .ZN (n_216));
  NR2D0 g11307(.A1 (po), .A2 (n_212), .ZN (n_215));
  NR2XD0 g11308(.A1 (n_184), .A2 (good), .ZN (n_214));
  IND2D0 g11309(.A1 (good), .B1 (check), .ZN (n_213));
  CKND2D0 g11310(.A1 (good), .A2 (check), .ZN (n_212));
  FA1D0 g11313(.A (n_13), .B (sub_op0[4]), .CI (n_206), .CO (n_211), .S
       (n_210));
  AO211D0 g11314(.A1 (n_184), .A2 (n_104), .B (n_208), .C (n_183), .Z
       (n_209));
  OAI211D0 g11316(.A1 (n_104), .A2 (n_184), .B (n_205), .C (n_199), .ZN
       (n_208));
  FA1D0 g11317(.A (n_16), .B (sub_op0[3]), .CI (n_201), .CO (n_206), .S
       (n_207));
  AOI33D0 g11319(.A1 (n_195), .A2 (n_112), .A3 (n_68), .B1 (n_110), .B2
       (n_111), .B3 (n_106), .ZN (n_205));
  NR2XD0 g11320(.A1 (n_203), .A2 (n_27), .ZN (n_204));
  AOI32D1 g11322(.A1 (n_191), .A2 (n_67), .A3 (n_359), .B1 (top_line),
       .B2 (n_242), .ZN (n_203));
  FA1D0 g11325(.A (n_12), .B (sub_op0[2]), .CI (n_181), .CO (n_201), .S
       (n_202));
  ND2D0 g11326(.A1 (n_196), .A2 (n_193), .ZN (n_200));
  ND4D0 g11327(.A1 (n_168), .A2 (n_109), .A3 (n_101), .A4 (n_105), .ZN
       (n_199));
  AOI211XD1 g11328(.A1 (n_184), .A2 (n_143), .B (n_140), .C (n_163),
       .ZN (n_198));
  AOI32D1 g11333(.A1 (n_57), .A2 (n_329), .A3 (inc_x), .B1 (n_164), .B2
       (n_378), .ZN (n_196));
  AN4D0 g11334(.A1 (n_376), .A2 (n_141), .A3 (n_67), .A4 (n_66), .Z
       (n_195));
  MOAI22D0 g11335(.A1 (n_167), .A2 (inc_y), .B1 (inc_y), .B2
       (x_min[2]), .ZN (n_194));
  ND3D1 g11336(.A1 (n_164), .A2 (n_17), .A3 (n_184), .ZN (n_193));
  MOAI22D1 g11337(.A1 (n_165), .A2 (n_328), .B1 (n_328), .B2
       (y_min[2]), .ZN (n_192));
  OAI21D1 g11338(.A1 (n_162), .A2 (n_99), .B (n_68), .ZN (n_191));
  OAI221D0 g11345(.A1 (n_88), .A2 (n_32), .B1 (\xi_ff[2] [0]), .B2
       (n_89), .C (n_179), .ZN (n_190));
  OAI221D0 g11346(.A1 (n_94), .A2 (\yi_ff[0] [1]), .B1 (\yi_ff[2] [1]),
       .B2 (n_92), .C (n_173), .ZN (n_189));
  OAI221D0 g11347(.A1 (n_88), .A2 (n_38), .B1 (\yi_ff[2] [2]), .B2
       (n_92), .C (n_174), .ZN (n_188));
  IOA21D0 g11348(.A1 (n_124), .A2 (n_100), .B (n_5), .ZN (n_187));
  IOA21D0 g11349(.A1 (n_124), .A2 (n_63), .B (n_5), .ZN (n_186));
  CKND2D2 g11351(.A1 (n_166), .A2 (n_62), .ZN (n_184));
  NR4D0 g11352(.A1 (n_137), .A2 (RLO[6]), .A3 (RLO[4]), .A4 (RLO[5]),
       .ZN (n_183));
  FA1D0 g11361(.A (n_15), .B (sub_op0[1]), .CI (n_42), .CO (n_181), .S
       (n_182));
  NR3D0 g11362(.A1 (n_157), .A2 (n_3), .A3 (n_340), .ZN (n_180));
  OA221D0 g11363(.A1 (n_92), .A2 (\yi_ff[2] [0]), .B1 (\yi_ff[0] [0]),
       .B2 (n_94), .C (n_118), .Z (n_179));
  CKND2D0 g11364(.A1 (n_152), .A2 (n_154), .ZN (n_178));
  AO221D0 g11365(.A1 (n_336), .A2 (AD[1]), .B1 (n_58), .B2
       (\xi_ff[1] [1]), .C (n_134), .Z (n_177));
  CKND2D0 g11366(.A1 (n_151), .A2 (n_153), .ZN (n_176));
  OAI221D0 g11367(.A1 (n_59), .A2 (\yi_ff[1] [2]), .B1 (AD[2]), .B2
       (n_29), .C (n_131), .ZN (n_175));
  AOI221D0 g11368(.A1 (n_90), .A2 (\xi_ff[2] [2]), .B1 (n_336), .B2
       (BC[2]), .C (n_132), .ZN (n_174));
  AOI221D0 g11369(.A1 (n_90), .A2 (\xi_ff[2] [1]), .B1 (n_336), .B2
       (BC[1]), .C (n_129), .ZN (n_173));
  CKND2D1 g11370(.A1 (n_150), .A2 (n_329), .ZN (n_172));
  OAI31D0 g11371(.A1 (reset), .A2 (rst_int), .A3 (n_372), .B (n_149),
       .ZN (n_171));
  MOAI22D0 g11374(.A1 (n_328), .A2 (n_82), .B1 (n_328), .B2 (y_min[1]),
       .ZN (n_170));
  MOAI22D0 g11375(.A1 (n_86), .A2 (inc_y), .B1 (inc_y), .B2 (x_min[1]),
       .ZN (n_169));
  NR2D0 g11376(.A1 (n_144), .A2 (n_107), .ZN (n_168));
  MAOI22D0 g11377(.A1 (n_44), .A2 (x[2]), .B1 (n_44), .B2 (x[2]), .ZN
       (n_167));
  CKND2D1 g11378(.A1 (n_139), .A2 (n_138), .ZN (n_166));
  MAOI22D1 g11379(.A1 (n_97), .A2 (y[2]), .B1 (n_97), .B2 (y[2]), .ZN
       (n_165));
  CKND1 g11380(.I (n_163), .ZN (n_164));
  CKND2D1 g11381(.A1 (n_329), .A2 (n_136), .ZN (n_163));
  OAI22D1 g11382(.A1 (n_43), .A2 (n_37), .B1 (y[1]), .B2 (y[0]), .ZN
       (n_162));
  OAI21D0 g11383(.A1 (n_233), .A2 (n_40), .B (n_230), .ZN (n_161));
  CKND2D0 g11398(.A1 (n_133), .A2 (n_135), .ZN (n_160));
  OAI211D0 g11399(.A1 (n_35), .A2 (n_59), .B (n_61), .C (n_130), .ZN
       (n_159));
  CKND0 g11400(.I (n_157), .ZN (n_158));
  IND4D0 g11401(.A1 (n_58), .B1 (n_29), .B2 (n_57), .B3 (n_59), .ZN
       (n_157));
  AOI21D0 g11402(.A1 (n_96), .A2 (n_332), .B (n_27), .ZN (n_156));
  NR4D0 g11403(.A1 (n_3), .A2 (n_56), .A3 (n_336), .A4 (n_340), .ZN
       (n_155));
  AOI22D0 g11404(.A1 (n_368), .A2 (C1[2]), .B1 (n_367), .B2 (C0[2]),
       .ZN (n_154));
  AOI22D0 g11405(.A1 (n_368), .A2 (C1[5]), .B1 (n_367), .B2 (C0[5]),
       .ZN (n_153));
  AOI22D0 g11406(.A1 (n_366), .A2 (D1[2]), .B1 (n_365), .B2 (D0[2]),
       .ZN (n_152));
  AOI22D0 g11407(.A1 (n_366), .A2 (D1[5]), .B1 (n_365), .B2 (D0[5]),
       .ZN (n_151));
  CKND2D1 g11408(.A1 (n_128), .A2 (n_333), .ZN (n_150));
  CKND2D0 g11409(.A1 (n_9), .A2 (n_124), .ZN (n_149));
  AO22D0 g11410(.A1 (n_335), .A2 (B[2]), .B1 (A[2]), .B2 (n_340), .Z
       (n_148));
  AO22D0 g11411(.A1 (n_335), .A2 (B[5]), .B1 (A[5]), .B2 (n_340), .Z
       (n_147));
  ND3D1 g11412(.A1 (n_84), .A2 (n_81), .A3 (n_80), .ZN (n_146));
  NR2XD1 g11413(.A1 (n_113), .A2 (n_85), .ZN (n_145));
  OAI211D0 g11414(.A1 (y[2]), .A2 (\yi_ff[2] [2]), .B (n_108), .C
       (n_69), .ZN (n_144));
  ND3D0 g11415(.A1 (n_72), .A2 (n_71), .A3 (n_73), .ZN (n_143));
  AOI221D0 g11417(.A1 (x[2]), .A2 (n_34), .B1 (y[0]), .B2 (n_35), .C
       (n_102), .ZN (n_141));
  AOI22D0 g11418(.A1 (n_75), .A2 (n_76), .B1 (n_20), .B2 (yo[2]), .ZN
       (n_140));
  CKND2D1 g11419(.A1 (n_98), .A2 (\xi_ff[1] [1]), .ZN (n_139));
  AOI22D1 g11420(.A1 (n_65), .A2 (\xi_ff[1] [0]), .B1 (n_38), .B2
       (\xi_ff[1] [2]), .ZN (n_138));
  ND4D0 g11421(.A1 (RLO[0]), .A2 (RLO[1]), .A3 (RLO[2]), .A4 (RLO[3]),
       .ZN (n_137));
  NR2XD1 g11422(.A1 (n_1), .A2 (n_41), .ZN (n_136));
  AOI22D0 g11427(.A1 (n_368), .A2 (C1[3]), .B1 (n_367), .B2 (C0[3]),
       .ZN (n_135));
  OAI222D0 g11428(.A1 (n_59), .A2 (n_37), .B1 (n_25), .B2 (n_339), .C1
       (n_22), .C2 (n_337), .ZN (n_134));
  AOI22D0 g11429(.A1 (n_366), .A2 (D1[3]), .B1 (n_365), .B2 (D0[3]),
       .ZN (n_133));
  NR2D0 g11430(.A1 (n_94), .A2 (\yi_ff[0] [2]), .ZN (n_132));
  AOI222D0 g11431(.A1 (n_30), .A2 (x[2]), .B1 (n_31), .B2 (y[2]), .C1
       (\xi_ff[1] [2]), .C2 (n_58), .ZN (n_131));
  AOI222D0 g11432(.A1 (n_30), .A2 (x[0]), .B1 (n_31), .B2 (y[0]), .C1
       (\xi_ff[1] [0]), .C2 (n_58), .ZN (n_130));
  NR2D0 g11433(.A1 (n_88), .A2 (n_36), .ZN (n_129));
  CKND2D1 g11434(.A1 (n_91), .A2 (n_93), .ZN (n_128));
  AO22D0 g11435(.A1 (n_340), .A2 (A[4]), .B1 (B[4]), .B2 (n_335), .Z
       (n_127));
  AO22D0 g11436(.A1 (n_335), .A2 (B[0]), .B1 (A[0]), .B2 (n_340), .Z
       (n_126));
  AO22D0 g11437(.A1 (n_335), .A2 (B[1]), .B1 (A[1]), .B2 (n_340), .Z
       (n_125));
  NR2XD1 g11438(.A1 (n_371), .A2 (n_64), .ZN (n_124));
  NR2D0 g11441(.A1 (n_29), .A2 (AD[3]), .ZN (n_122));
  NR2D0 g11442(.A1 (n_29), .A2 (AD[4]), .ZN (n_121));
  NR2D0 g11443(.A1 (n_29), .A2 (AD[5]), .ZN (n_120));
  NR2D0 g11444(.A1 (n_29), .A2 (AD[6]), .ZN (n_119));
  CKND2D0 g11445(.A1 (BC[0]), .A2 (n_336), .ZN (n_118));
  NR2D0 g11446(.A1 (n_29), .A2 (BC[3]), .ZN (n_117));
  NR2D0 g11447(.A1 (n_29), .A2 (BC[4]), .ZN (n_116));
  NR2D0 g11448(.A1 (n_29), .A2 (BC[6]), .ZN (n_115));
  NR2D0 g11449(.A1 (n_29), .A2 (BC[5]), .ZN (n_114));
  CKND2D1 g11450(.A1 (n_79), .A2 (n_78), .ZN (n_113));
  MAOI22D0 g11451(.A1 (n_25), .A2 (\xi_ff[1] [1]), .B1 (n_25), .B2
       (\xi_ff[1] [1]), .ZN (n_112));
  MOAI22D0 g11452(.A1 (n_25), .A2 (n_36), .B1 (n_25), .B2 (n_36), .ZN
       (n_111));
  MAOI22D0 g11453(.A1 (x[0]), .A2 (n_32), .B1 (x[0]), .B2 (n_32), .ZN
       (n_110));
  MAOI22D0 g11454(.A1 (x[0]), .A2 (\xi_ff[2] [0]), .B1 (x[0]), .B2
       (\xi_ff[2] [0]), .ZN (n_109));
  AOI22D0 g11455(.A1 (n_24), .A2 (\xi_ff[2] [2]), .B1 (n_25), .B2
       (\xi_ff[2] [1]), .ZN (n_108));
  OAI22D0 g11456(.A1 (n_25), .A2 (\xi_ff[2] [1]), .B1 (n_24), .B2
       (\xi_ff[2] [2]), .ZN (n_107));
  MOAI22D0 g11457(.A1 (n_24), .A2 (n_38), .B1 (n_24), .B2 (n_38), .ZN
       (n_106));
  MOAI22D0 g11458(.A1 (n_21), .A2 (\yi_ff[2] [0]), .B1 (n_21), .B2
       (\yi_ff[2] [0]), .ZN (n_105));
  MAOI22D0 g11459(.A1 (n_26), .A2 (RLO[6]), .B1 (n_26), .B2 (RLO[6]),
       .ZN (n_104));
  OAI22D0 g11461(.A1 (n_37), .A2 (y[1]), .B1 (y[0]), .B2 (n_35), .ZN
       (n_102));
  MOAI22D0 g11462(.A1 (n_22), .A2 (\yi_ff[2] [1]), .B1 (n_22), .B2
       (\yi_ff[2] [1]), .ZN (n_101));
  MOAI22D0 g11463(.A1 (n_40), .A2 (control[2]), .B1 (n_40), .B2
       (control[2]), .ZN (n_100));
  AOI21D0 g11464(.A1 (n_37), .A2 (y[1]), .B (n_35), .ZN (n_99));
  OAI21D1 g11465(.A1 (n_33), .A2 (\xi_ff[0] [0]), .B (\xi_ff[0] [1]),
       .ZN (n_98));
  CKND0 g11468(.I (n_43), .ZN (n_97));
  CKND2D1 g11469(.A1 (check), .A2 (n_57), .ZN (n_96));
  MOAI22D0 g11470(.A1 (n_328), .A2 (y[0]), .B1 (n_328), .B2 (y_min[0]),
       .ZN (n_95));
  AOI21D0 g11471(.A1 (n_31), .A2 (n_26), .B (n_330), .ZN (n_94));
  NR2XD0 g11472(.A1 (n_2), .A2 (n_17), .ZN (n_93));
  AOI21D0 g11473(.A1 (n_31), .A2 (top_line), .B (n_328), .ZN (n_92));
  NR2D1 g11474(.A1 (n_31), .A2 (n_328), .ZN (n_91));
  CKND0 g11475(.I (n_90), .ZN (n_89));
  OAI21D0 g11476(.A1 (n_26), .A2 (n_339), .B (n_333), .ZN (n_90));
  AOI21D0 g11477(.A1 (n_30), .A2 (n_26), .B (n_334), .ZN (n_88));
  AOI22D0 g11479(.A1 (n_23), .A2 (x[1]), .B1 (n_25), .B2 (x[0]), .ZN
       (n_86));
  MUX2ND0 g11480(.I0 (n_23), .I1 (x[0]), .S (x_min[0]), .ZN (n_85));
  MUX2ND0 g11481(.I0 (x[1]), .I1 (n_25), .S (x_max[1]), .ZN (n_84));
  OAI21D0 g11482(.A1 (sub_op1[0]), .A2 (n_11), .B (n_42), .ZN (n_83));
  AOI22D0 g11483(.A1 (n_21), .A2 (y[1]), .B1 (n_22), .B2 (y[0]), .ZN
       (n_82));
  MUX2ND0 g11484(.I0 (x[2]), .I1 (n_24), .S (x_max[2]), .ZN (n_81));
  MUX2ND0 g11485(.I0 (x[0]), .I1 (n_23), .S (x_max[0]), .ZN (n_80));
  IAO22D1 g11486(.A1 (x[2]), .A2 (n_7), .B1 (n_25), .B2 (x_min[1]), .ZN
       (n_79));
  AOI22D0 g11487(.A1 (x[1]), .A2 (n_8), .B1 (x[2]), .B2 (n_7), .ZN
       (n_78));
  MAOI22D0 g11488(.A1 (sub_op0[5]), .A2 (sub_op1[5]), .B1 (sub_op1[5]),
       .B2 (sub_op0[5]), .ZN (n_77));
  OAI211D0 g11489(.A1 (y_max[1]), .A2 (n_19), .B (n_18), .C (y_max[0]),
       .ZN (n_76));
  IAO22D0 g11490(.A1 (n_20), .A2 (yo[2]), .B1 (n_19), .B2 (y_max[1]),
       .ZN (n_75));
  MOAI22D0 g11491(.A1 (sub_op1[6]), .A2 (sub_op0[6]), .B1 (sub_op1[6]),
       .B2 (sub_op0[6]), .ZN (n_74));
  MOAI22D0 g11492(.A1 (x_max[0]), .A2 (xo[0]), .B1 (x_max[0]), .B2
       (xo[0]), .ZN (n_73));
  MOAI22D0 g11493(.A1 (x_max[2]), .A2 (xo[2]), .B1 (x_max[2]), .B2
       (xo[2]), .ZN (n_72));
  MOAI22D0 g11494(.A1 (x_max[1]), .A2 (xo[1]), .B1 (x_max[1]), .B2
       (xo[1]), .ZN (n_71));
  CKND2D0 g11496(.A1 (y[2]), .A2 (\yi_ff[2] [2]), .ZN (n_69));
  CKND2D0 g11497(.A1 (y[2]), .A2 (\yi_ff[1] [2]), .ZN (n_68));
  OR2D0 g11498(.A1 (\yi_ff[1] [2]), .A2 (y[2]), .Z (n_67));
  CKND2D0 g11499(.A1 (y[1]), .A2 (n_37), .ZN (n_66));
  NR2XD0 g11500(.A1 (\xi_ff[0] [0]), .A2 (\xi_ff[0] [1]), .ZN (n_65));
  NR2XD0 g11501(.A1 (n_39), .A2 (n_41), .ZN (n_64));
  IOA21D0 g11502(.A1 (control[1]), .A2 (n_9), .B (n_1), .ZN (n_63));
  CKND2D0 g11503(.A1 (n_34), .A2 (\xi_ff[0] [2]), .ZN (n_62));
  CKND2D0 g11532(.A1 (AD[0]), .A2 (n_336), .ZN (n_61));
  INR2D0 g11534(.A1 (n_332), .B1 (n_354), .ZN (n_60));
  NR2D0 g11535(.A1 (n_330), .A2 (n_328), .ZN (n_59));
  IND2D0 g11536(.A1 (n_334), .B1 (n_333), .ZN (n_58));
  CKND0 g11537(.I (n_57), .ZN (n_56));
  NR2XD1 g11538(.A1 (n_31), .A2 (n_30), .ZN (n_57));
  CKAN2D0 g11543(.A1 (n_329), .A2 (mul_ans[0]), .Z (n_53));
  CKAN2D0 g11544(.A1 (n_329), .A2 (mul_ans[1]), .Z (n_52));
  CKAN2D0 g11545(.A1 (n_329), .A2 (mul_ans[2]), .Z (n_51));
  CKAN2D0 g11546(.A1 (n_329), .A2 (mul_ans[3]), .Z (n_50));
  CKAN2D0 g11547(.A1 (n_329), .A2 (mul_ans[5]), .Z (n_49));
  CKAN2D0 g11548(.A1 (n_329), .A2 (mul_ans[4]), .Z (n_48));
  CKAN2D0 g11549(.A1 (n_329), .A2 (mul_ans[6]), .Z (n_47));
  INR2XD1 g11550(.A1 (sub_ans[2]), .B1 (n_27), .ZN (n_46));
  CKAN2D0 g11551(.A1 (n_329), .A2 (sub_ans[5]), .Z (n_45));
  CKND2D0 g11552(.A1 (x[0]), .A2 (x[1]), .ZN (n_44));
  NR2XD1 g11553(.A1 (n_22), .A2 (n_21), .ZN (n_43));
  CKND2D0 g11554(.A1 (sub_op1[0]), .A2 (n_11), .ZN (n_42));
  CKND2D1 g11555(.A1 (control[2]), .A2 (control[3]), .ZN (n_41));
  CKND2D0 g11556(.A1 (control[1]), .A2 (control[0]), .ZN (n_40));
  NR2D0 g11558(.A1 (control[1]), .A2 (control[0]), .ZN (n_39));
  CKND2 g11607(.I (n_337), .ZN (n_31));
  CKND1 g11608(.I (n_339), .ZN (n_30));
  CKND0 g11609(.I (n_336), .ZN (n_29));
  CKND0 g11611(.I (n_329), .ZN (n_27));
  CKND0 g11615(.I (x[0]), .ZN (n_23));
  CKND0 g11619(.I (y_max[2]), .ZN (n_20));
  CKND0 g11620(.I (yo[1]), .ZN (n_19));
  CKND0 g11621(.I (yo[0]), .ZN (n_18));
  CKND0 g11623(.I (sub_op1[3]), .ZN (n_16));
  CKND0 g11624(.I (sub_op1[1]), .ZN (n_15));
  CKND0 g11625(.I (sub_op1[5]), .ZN (n_14));
  CKND0 g11626(.I (sub_op1[4]), .ZN (n_13));
  CKND0 g11627(.I (sub_op1[2]), .ZN (n_12));
  CKND0 g11628(.I (sub_op0[0]), .ZN (n_11));
  CKND0 g11631(.I (control[0]), .ZN (n_9));
  CKND0 g11632(.I (x_min[1]), .ZN (n_8));
  CKND0 g11633(.I (x_min[2]), .ZN (n_7));
  DFD1 inc_y_reg(.CP (clk), .D (n_220), .Q (inc_y), .QN (n_17));
  DFD1 top_line_reg(.CP (clk), .D (n_204), .Q (top_line), .QN (n_26));
  DFD1 \xi_ff_reg[0][0] (.CP (rc_gclk_7520), .D (n_322), .Q
       (\xi_ff[0] [0]), .QN (n_32));
  DFD1 \xi_ff_reg[0][1] (.CP (rc_gclk_7520), .D (n_321), .Q
       (\xi_ff[0] [1]), .QN (n_36));
  DFD1 \xi_ff_reg[0][2] (.CP (rc_gclk_7520), .D (n_320), .Q
       (\xi_ff[0] [2]), .QN (n_38));
  DFD1 \xi_ff_reg[1][0] (.CP (rc_gclk_7496), .D (n_322), .Q
       (\xi_ff[1] [0]), .QN (n_33));
  DFD1 \xi_ff_reg[1][2] (.CP (rc_gclk_7496), .D (n_320), .Q
       (\xi_ff[1] [2]), .QN (n_34));
  DFD1 \yi_ff_reg[1][0] (.CP (rc_gclk_7496), .D (n_319), .Q
       (UNCONNECTED3), .QN (n_35));
  DFD1 \yi_ff_reg[1][1] (.CP (rc_gclk_7496), .D (n_318), .Q
       (UNCONNECTED4), .QN (n_37));
  IND2D1 g5070(.A1 (n_377), .B1 (n_145), .ZN (n_5));
  IND2D0 g11636(.A1 (n_335), .B1 (n_332), .ZN (n_3));
  INR2XD0 g11637(.A1 (inc_x), .B1 (n_339), .ZN (n_2));
  IND2D1 g11638(.A1 (control[1]), .B1 (control[0]), .ZN (n_1));
  CKND0 g11659(.I (n_329), .ZN (n_371));
  CKND0 g11660(.I (n_64), .ZN (n_372));
  CKND0 g11662(.I (n_146), .ZN (n_374));
  AOI21D0 g11663(.A1 (n_24), .A2 (\xi_ff[1] [2]), .B (n_375), .ZN
       (n_376));
  XNR2D0 g3(.A1 (x[0]), .A2 (n_33), .ZN (n_375));
  CKND2D0 g11664(.A1 (n_329), .A2 (n_64), .ZN (n_377));
  CKAN2D0 g11665(.A1 (n_0), .A2 (n_17), .Z (n_378));
  INR2D1 g11668(.A1 (y_min[0]), .B1 (yi[0]), .ZN (n_225));
  IND2D1 g11669(.A1 (x_max[0]), .B1 (xi[0]), .ZN (n_380));
  MOAI22D0 g11670(.A1 (n_145), .A2 (n_377), .B1 (n_161), .B2 (n_124),
       .ZN (n_381));
  AN2D0 g11671(.A1 (n_329), .A2 (yi[1]), .Z (n_318));
endmodule

